### ISSUE TITLE
Documentation for $nutrition

### ISSUE THREAD

**Issue by Soulcyber** [daniel-nagy/md-data-table#102]
In the Usage and Installation section of the README, there is no mention to $nutrition, which you then add as dependency in the example controller.

**Comment by daniel-nagy** [comment]
`$nutrition` is just an Angular service I wrote for the demo application to communicate with the nutrition database. It is an example of how you can grab data from the server when the user interacts with the table. The actual contents of the `$nutrition` service are irrelevant but you can always look at the [source code](https://github.com/daniel-nagy/md-data-table/blob/gh-pages/scripts/nutritionResource.js).
