### ISSUE TITLE
order by type asc or desc

### ISSUE THREAD

**Issue by dleitee** [daniel-nagy/md-data-table#107]
The request should send a parameter to the type of order.

Example:
http://localhost/api/v1/users?filter=&limit=10&order=name&ordertype=asc&page=1

**Comment by daniel-nagy** [comment]
If your query language doesn't recognize the minus `-` sign to mean descending then you can just parse the string in your trigger function and send an additional parameter.

```javascript
$scope.triggerHandler = function (order) {
  var direction = 'asc';

  if(order.charAt(0) === '-') {
    direction = 'desc';
    order = order.slice(1);
  }
  
  // make request to server
}
```

This module doesn't send requests to the server for you.
