### ISSUE TITLE
There is some css class for secondary functions?

### ISSUE THREAD

**Issue by dleitee** [daniel-nagy/md-data-table#113]
Example: [Image](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3mOPoJlxiFhazJZa2VmSU5ldTQ/components_datatables_interaction_editing4.png) from [Google Material - Data Tables](https://www.google.com/design/spec/components/data-tables.html#data-tables-interaction)

**Comment by daniel-nagy** [comment]
I have not yet worked on any type of cell editing. This is a high priority issue; however, so hopefully I will get a chance to work on it in the near future.

**Comment by dleitee** [comment]
Of course. If you need help, you might collaborate. 
Thank you
