### ISSUE TITLE
Scrollable rows; fixed table height

### ISSUE THREAD

**Issue by jwmay2012** [daniel-nagy/md-data-table#116]
Currently the whole table grows with the number of rows. 
I would love the ability to have the table take up a fixed space or flex to the page while the content rows become scrollable. This can almost be achieved with the right combination of layout-fill's and layout's but I can't get the <thead> to remain stationary while the data scrolls.
If I make <thead> position: absolute it breaks the spacing of the columns.
I'm afraid I don't have time at the moment to properly investigate and contribute code. But if anyone has successfully done this or could take the time, I would greatly appreciate it.

**Comment by daniel-nagy** [comment]
You should be able to make the `md-data-table-container` element scroll vertically, either by setting a max height on it or flexing it so it can grow and shrink with the screen.

If you want the rows to scroll vertically while the header remains fixed, this is not something that can be achieved using HTML and CSS alone. This is actually something that is very difficult to do. I wrote an Angular module in the past that could do this but ultimately decided it was more trouble than it was worth. I have no intention of adding this functionality and I would warn anyone who wanted to attempt it that it is very difficult to get right.

**Comment by daniel-nagy** [comment]
#184
