### ISSUE TITLE
Ordering not working as expected

### ISSUE THREAD

**Issue by jonarobi** [daniel-nagy/md-data-table#117]
The reordering event 'md-trigger' gets triggered before the binded property 'order-by' gets updated. As a result, the reordering does not take place on the first click and the results are always one behind thereafter. This is happening in the current demo.

**Comment by daniel-nagy** [comment]
I noticed this a few days ago. I explicitly wrap the trigger function in a timeout to wait for the next digest in the [setOrder](https://github.com/daniel-nagy/md-data-table/blob/master/app/md-data-table/scripts/mdColumnHeader.js#L28) function so I'm not sure why the scope is still stale when the function gets called.

One thing that has changed is I'm no longer using `ng-click` and instead I'm using `element.on('click' ...)`. I believe the `ng-click` directive forces a digest but the latter may not. I may have to use `scope.$apply` in the `setOrder` function to force a digest.

**Comment by daniel-nagy** [comment]
@jonarobi can you please confirm that v0.8.10 solves this issue?

**Comment by jonarobi** [comment]
Yup! It's working for me now.
Thanks a lot.
