### ISSUE TITLE
Client-side ordering doesn't work without md-trigger

### ISSUE THREAD

**Issue by videege** [daniel-nagy/md-data-table#119]
Hello,

I noticed that when I'm trying to do client-side ordering, I must provide an md-trigger attribute or else the orderBy target isn't updated until I trigger a digest elsewhere on the page (for example, by selecting a row).  Here's the code setup (with the `noop` function for the trigger):

    <md-data-table-container>
                <table md-data-table md-row-select="vm.selected">
                    <thead md-order="vm.order" md-trigger="vm.noop">
                        <tr>
                            <th order-by="code" name="Code"></th>
                            <th order-by="clientName" name="Name"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="client in vm.clients | orderBy: vm.order | limitTo: vm.limit: (vm.page - 1) * vm.limit" md-auto-select>
                            <td>{{client.code}}</td>
                            <td>{{client.clientName}}</td>                           
                        </tr>
                    </tbody>
                </table>
            </md-data-table-container>

Is this intentional?  The docs seem to indicate that you can omit the md-trigger attribute when doing client-side ordering.

**Comment by daniel-nagy** [comment]
No this is not intentional. I think after switching from using `ng-click` to `element.on('click')` I need to force a digest using `scope.$apply`. #117 related. I will try to do this tonight.

**Comment by daniel-nagy** [comment]
@videege can you please confirm that v0.8.10 solves this issue?

**Comment by videege** [comment]
@daniel-nagy Looks good now, thanks for the quick fix!
