### ISSUE TITLE
Select only filtered results when clicking on the 'select all' checkbox

### ISSUE THREAD

**Issue by leseulsteve** [daniel-nagy/md-data-table#120]
When there's filters applied on the ng-repeat directive in the table, even the 'filtered-out' lines are selected when we click on the select-all checkbox

![untitled](https://cloud.githubusercontent.com/assets/6606025/9609865/18da9adc-50a4-11e5-893a-a5586e0f93d5.png)

**Comment by daniel-nagy** [comment]
That's a problem! Some changes will need to be made to make sure filtered items are not selected.

**Comment by leseulsteve** [comment]
You know what? I think the problem was on my side... I refracted how I use your amazing lib, and I can't reproduce it!! :)

Sorry about that!

**Comment by apat183** [comment]
Do you mind sharing how you resolved? I'm using basic filter like so, when selecting all, it also selects filtered items:

```
tr ng-repeat="assignment in assignCtrl.assignments | orderBy: assignCtrl.query.order |  filter:{$: assignCtrl.search} | limitTo: assignCtrl.query.limit : (assignCtrl.query.page -1) * assignCtrl.query.limit" ng-click="assignCtrl.openAssignment(assignment)">
                        <td>{{assignment.attributes.title}}</td>
                        <td>{{assignment.attributes.clientID.attributes.name}}</td>
                        <td>{{assignment.attributes.status}}</td>
                        <td>{{assignment.progress | number : 1}}</td>
                        <td>{{assignment.issues}}</td>
                        <td>{{assignment.attributes.startDate | date : shortDate}}</td>
                        <td>{{assignment.attributes.deliveryDate | date : shortDate}}</td>
             </tr>

Thanks,
Anand

**Comment by daniel-nagy** [comment]
@apat183 Try assigning a variable to the result of the filter. Let me know if this works for you.

```html
<tr ng-repeat="assignment in results = (assignCtrl.assignments | orderBy: assignCtrl.query.order | filter: {$: assignCtrl.search} | limitTo: assignCtrl.query.limit : (assignCtrl.query.page -1) * assignCtrl.query.limit)" ng-click="assignCtrl.openAssignment(assignment)">
```

**Comment by apat183** [comment]
Doing it the way above produces the following error:
```
Error: [$parse:ueoe] http://errors.angularjs.org/1.4.4/$parse/ueoe?p0=results%3D(assignCtrl.assignments
```
https://docs.angularjs.org/error/$parse/ueoe?p0=results%3D(assignCtrl.assignments

I tried moving the brackets to just around the results but then it functions the same as before (all filtered results get selected). 

```
<tr ng-repeat="assignment in (results = assignCtrl.assignments) | orderBy: assignCtrl.query.order | filter: {$: assignCtrl.search} | limitTo: assignCtrl.query.limit : (assignCtrl.query.page -1) * assignCtrl.query.limit" ng-click="assignCtrl.openAssignment(assignment)">
```

**Comment by daniel-nagy** [comment]
> I tried moving the brackets to just around the results but then it functions the same as before (all filtered results get selected)

This is because you are just assigning results equal to the original array and not the filtered items.

Try only assigning it to the filtered list and see what happens.

```html
<tr ng-repeat="assignment in results = (assignCtrl.assignments | filter: {$: assignCtrl.search}) | orderBy: assignCtrl.query.order | limitTo: assignCtrl.query.limit : (assignCtrl.query.page -1) * assignCtrl.query.limit">
```

**Comment by apat183** [comment]
Sorry I was going to say I did that as well. Same error.

Even tried this:
```
<tr ng-repeat="assignment in (results = (assignCtrl.assignments | filter: {$: assignCtrl.search}) | orderBy: assignCtrl.query.order | limitTo: assignCtrl.query.limit : (assignCtrl.query.page -1) * assignCtrl.query.limit)"> 
```
&
```
<tr ng-repeat="assignment in (results = (assignCtrl.assignments | filter: {$: assignCtrl.search})) | orderBy: assignCtrl.query.order | limitTo: assignCtrl.query.limit : (assignCtrl.query.page -1) * assignCtrl.query.limit">

**Comment by daniel-nagy** [comment]
Hmmm... If you make a Plunker I may be able to help figure out what's going on.

**Comment by apat183** [comment]
Here you go.

It's a bit mess but I created an input (next to nutrition title). 
http://codepen.io/anon/pen/pjRKee?editors=101

Type in "Cupcake", it firsts results to cupcake. But click the select all button and it shows it's selecting 8 items but there is only one filtered result.

**Comment by daniel-nagy** [comment]
Okay I found what was causing the first error but now when I try to filter the results it goes into an infinite digest. I'm going to spend a little more time on this but it is not obvious what is causing the infinite digest and I don't know if I'll be able to fix it.

**Comment by apat183** [comment]
Ok, I tired one way of putting ng-repeat result in function that returned results and used filter in JS but that also causing infinite digest:

```
ng-repeat="assignment in cusFilter(search)"
```
in JS
```
function cusFilter(search) {
return ($filter('filter')(self.assignments, { $: search}));
}

**Comment by PsychicCat** [comment]
Hi, I had this same issue. Select all was selecting everything not the filtered items.

Here is how I fixed it, maybe not the best solution but it works:
http://codepen.io/anon/pen/eJpGze?editors=101

**Comment by Rishabhqleverlabs** [comment]
nothing is there in that codepen link,
it's irrelevant to the discussion
