### ISSUE TITLE
Browserify Support

### ISSUE THREAD

**Issue by brownish** [daniel-nagy/md-data-table#121]
I would love to see support for browserify as I can't for the life of me get it to work with it.

Thanks!

**Comment by daniel-nagy** [comment]
I think Browserify is intended for CommonJS modules (i.e. packages installed using npm that use the `module.exports` syntax) in your web application. Using Browserify to import angular modules is unnecessary because Angular already has a module system, `angular.module`. Here is a good [article](http://benclinkinbeard.com/posts/how-browserify-works/) on how Browserify works and might give you some insight as to why using it for Angular modules is an extra layer that is completely unnecessary. In fact, unless you are using CommonJS modules in your web application I would not use Browserify at all. I would just use a task runner to concatenate your files.

**Comment by brownish** [comment]
Angular and Angular-Material have both [introduced support for browserify](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support). I see your point though, angular itself adds quite a bit of complexity. I've modified [angular-gulp-browserify-boilerplate](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate) to fit my project and after a day of mucking around it's working pretty well. Getting bower_components and node_modules to play well together hasn't worked that well, though. I may end up ditching browserify and using a different builder.

**Comment by daniel-nagy** [comment]
I can put an `index.js` file in the root of the project.

```javascript
// index.js
require('angular-material');
require('dist/md-data-table.min.js');

module.exports = 'md.data.table';
```

Does the package need to be registered with npm for this to work, i.e. the ability to do 

`npm install angular-material-data-table --save`

or will it also work if the package is install using Bower or some other method.

**Comment by brownish** [comment]
I'm not entirely sure, lol. I looked into it yesterday and couldn't find a guide that explicitly detailed the process. 

I was able to install it via npm with `npm install daniel-nagy/md-data-table`. It didn't work with browserify, though.

I'll look into it and let you know what i can find out.

**Comment by brownish** [comment]
Found this [article](https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc) by Kent C. Dodds.
If I understand it correctly, you need to add dependencies, and main to package.json like so:

```
{
  "name": "angular-material-data-table",
  "version": "0.8.10",
  "description": "Material Design data table.",
  "repository": {
    "type": "git",
    "url": "git://github.com/daniel-nagy/md-data-table.git"
  },
  "authors": [
    "Daniel Nagy"
  ],
  "homepage": "http://danielnagy.me/md-data-table",
  "license": "MIT",
  "main": "dist/md-data-table.js",
  "dependencies": {
    "angular": "~1.4.4",
    "angular-material": "~0.10.1"
  },
  "devDependencies": {
    "bower": "^1.3.9",
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^2.1.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-connect": "^0.8.0",
    "grunt-contrib-cssmin": "^0.10.0",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-less": "^0.11.4",
    "grunt-contrib-uglify": "^0.5.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-html2js": "^0.3.2",
    "grunt-processhtml": "^0.3.7",
    "jshint-stylish": "^1.0.0",
    "load-grunt-tasks": "^0.6.0"
  }
}
```

Then, in your gruntfile, you can probably add a task to build to commonjs, as mentioned in that article. That task would build the dist/md-data-table.js pretty much the same way but wrapping it the commonjs stuff, kind of like this:

```
(function (root, factory) {
  'use strict';
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['angular'], factory);
  } else if (typeof module !== 'undefined' && typeof module.exports === 'object') {
    // CommonJS support (for us webpack/browserify/ComponentJS folks)
    module.exports = factory(require('angular'));
  } else {
    // in the case of no module loading system
    // then don't worry about creating a global
    // variable like you would in normal UMD.
    // It's not really helpful... Just call your factory
    return factory(root.angular);
  }
}(this, function (angular) {
  'use strict';
  // create your angular module and do stuff
  var moduleName = 'md-data-table';
  var mod = angular.module(moduleName, []);
  mod.value('linkLoggerOptions', {enabled: true});
  mod.directive('logWhenLinked', ['$log', 'linkLoggerOptions', function($log, linkLoggerOptions) {
    return function() {
      if (linkLoggerOptions.enabled) {
        $log.info('linked!', arguments);
      }
    }
  }]);

  return moduleName; // the name of your module
}));

Looks like [grunt-angular-modularize](https://github.com/ericclemmons/grunt-angular-modularize) could do that for you. I never got into grunt too much so I cant really help there. I've just been learning how gulp works (JS newb here).

**Comment by daniel-nagy** [comment]
If I am understanding correctly how to use Browserify, you execute a command and it packages everything up into one file before anything get shipped to the browser. Therefore putting logic in the module to be executed in the browser to test whether `angular` or `module` is defined is complete overkill and I don't see how this assists with Browserify in any way.

The first article you linked to, [Using Angular’s new improved Browserify support](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support), uses a separate file that will never be executed by the browser called `index.js`, which is the default file `Node.js` will look for in any directory. In this `index.js` file they are requiring any module dependencies and the code for the module itself and then exporting it.

So I believe all that needs to happen is I need to create an `index.js` file, or if I wanted to name it something else I could create a main section in `package.json`, and I need to create a dependencies section as well.

**Comment by brownish** [comment]
I think that first module-checking code is just there so you dont need to rebuild for bower or npm or whatever. I believe you can use one grunt task to build and publish to bower and another to publish to npm so each one has a corresponding dist/md-data-table.js without needing the check. For the `require('dist/md-data-table');` to work in the index.js `dist/md-data-table` needs to export something browserify can read.

If it doesn't have a `module.exports = asdf;` in the file browserify/node wont know what to do with it (I think).

**Comment by daniel-nagy** [comment]
> For `require('dist/md-data-table');` to work in index.js, dist/md-data-table needs to export something.

Ah you may be right. I'll have to try it and see.

**Comment by brownish** [comment]
Great. Thanks!

**Comment by daniel-nagy** [comment]
@brownish sorry I've been away from my computer the past couple days. I was correct, using `require` on a file that doesn't export anything must just concatenate the file or maybe this is something unique that Browserify does. Anyway this should work now and I've updated the installation instructions for [using npm and Browserify](https://github.com/daniel-nagy/md-data-table#using-npm-and-browserify)

**Comment by brownish** [comment]
@daniel-nagy `npm install --save angular-material-data-table` returns:

`Registry returned 404 for GET on https://registry.npmjs.org/angular-material-data-table`

You published it to the npm registry and don't have it marked private in the package.json?

**Comment by daniel-nagy** [comment]
oops no, it should be `npm install daniel-nagy/md-data-table` still. I'll fix the README.

**Comment by brownish** [comment]
I got it to install but but adding `require('angular-material-data-table')` doesn't seem to be working. I'm trying to see if it's on my end.

**Comment by daniel-nagy** [comment]
Okay, I didn't try to execute it in the browser I just saw that it was grabbing the module in the generated file. If you can't get it to work I'll look into it some more tomorrow.

**Comment by brownish** [comment]
Thanks. I'm not sure what's going on. I'll play around with it and see what I can do.

**Comment by daniel-nagy** [comment]
I was able to get this working in the demo app without any problems. My `app.js` looked like this.

```javascript
var angular = require('angular');
angular.module('nutritionApp', [require('angular-material'), require('angular-material-data-table')]);
```

Then I just ran Browserify to create a file called `bundle.js`

`node_modules/.bin/browserify app.js -o bundle.js`

and included that in my `index.html`

```html
<script type="text/javascript" src="bundle.js"></script>
```

**Comment by brownish** [comment]
Interesting. Must be on my end. I was redesigning my site over the weekend and I'm just about to reimplement the tables. I'll let you know if I have any troubles.

**Comment by sombriks** [comment]
hi, 

i can confirm that it works well with brwoserify by following these steps:

```
var angular = require('angular');
angular.module('nutritionApp', [require('angular-material'), require('angular-material-data-table')]);
```
