### ISSUE TITLE
Angular and Angular material fixed version

### ISSUE THREAD

**Issue by williamweckl** [daniel-nagy/md-data-table#122]
Can you consider to unfix version of angular and angular-material?

Both libs are updating constantly, today I wanted to test the new 0.11.0.rc2 version of angular-material and could not. Angular is in 1.4.5 too.

**Comment by daniel-nagy** [comment]
What do you mean unfix? I have no control over what versions of Angular or Angular Material you use in your application.

**Comment by williamweckl** [comment]
```javascript
"dependencies": {
    "angular": "~1.4.4",
    "angular-material": "~0.10.1"
  }
```
So I'm trying to use angular 1.4.5 and angular-material 0.11.0.rc2.

**Comment by daniel-nagy** [comment]
So change the version and do a bower update?

```JSON
"dependencies": {
  "angular": "1.4.5",
  "angular-material": "0.11.0"
}
```

**Comment by williamweckl** [comment]
I understand. Will explain me better. 

I'm not using bower directly, I'm working on a ruby on rails project and for js libs dependencies I'm using this guy: [rails-assets][1]. 

He does a bridge between bower and rails gems.

With this tool I can't just touch lib files. So yes, I could use bower directly and change the file. But, I'm using so many other libs that are not with angular version fixed.

Based on this, I'm asking if you could just use something like this:

```javascript
"dependencies": {
  "angular": "~1.4",
  "angular-material": ">= 0.10.1"
}
```

[1]: https://rails-assets.org

**Comment by williamweckl** [comment]
By the way, it's an amazing lib. All working fine and as expected. Congratulations for the job done. =)

**Comment by daniel-nagy** [comment]
I can add ranges to the versions, I will do this shortly (after class).

Thanks! I wish I had more time to work on this so I could finish up some of the missing features. I have so much coding to do between classes and work. Usually by the time I finish that I don't want to write code anymore haha.

**Comment by daniel-nagy** [comment]
I've changed the dependencies to

```json
"dependencies": {
  "angular": "~1.4.4",
  "angular-material": "0.10.1 || >0.11.0-rc0"
}
```

This should match both Angular v1.4.5 and Angular Material v0.11.0-rc2, if it does not let me know.

**Comment by williamweckl** [comment]
Thank you!

Can you make a release with this changes?

**Comment by daniel-nagy** [comment]
@williamweckl sorry I've been away from my computer the past two days. I just created a release but I changed the dependencies to

```json
"dependencies": {
  "angular": "^1.4.0",
  "angular-material": "^0.10.1"
}
```

Let me know if this doesn't let you install Angular Material 0.11.0-rc2, if it does please close this issue. :)

**Comment by williamweckl** [comment]
Worked! Thank you!

**Comment by williamweckl** [comment]
@daniel-nagy I'm sorry but with the stable 0.11.0 version of angular material it's not working again. Can you fix it?

**Comment by treyhoover** [comment]
+1

**Comment by williamweckl** [comment]
It's working for me now. Thanks.
