### ISSUE TITLE
Using online demo

### ISSUE THREAD

**Issue by mrcel** [daniel-nagy/md-data-table#128]
I want to use the demo (http://danielnagy.me/md-data-table/) in a project and feed it with my own data. I added the custom app.css and also tried to use the nutritionController but my result is as shown below. Where is the error?
![screenshot from 2015-09-08 19 09 38](https://cloud.githubusercontent.com/assets/13166067/9741910/685590d0-565d-11e5-9849-44e4efc40ee3.png)

**Comment by daniel-nagy** [comment]
Its hard to say without looking at any code, are there any errors in the browser's console? Coping my code verbatim will not just magically work, you'll need to modify it to handle your data. I would recommend trying to understand how the demo application works so you can modify it to fit your needs.

**Comment by mrcel** [comment]
I figured out that the templates.md-data-table-progress.html and templates.md-data-table-pagination.html  fail to load. I added them in the correct directory, and I also tried to change them to different directories. But it does not work.
