### ISSUE TITLE
add button to table row in order to open a dialog

### ISSUE THREAD

**Issue by mrcel** [daniel-nagy/md-data-table#131]
Hello,
I want to add a button into each table row in order to open a dialog on click. But if I add the button inside/outside the last <td></td> column, it can not be clicked. Instead, the row is selected. Is there any solution to implement the described behavior?
Thank you, best, Marcel

**Comment by daniel-nagy** [comment]
You'll need to stop the event from propagating when the cell is clicked.

```html
<td ng-click="$event.stopPropagation()"></td>
```

**Comment by Comtravo** [comment]
It works - you made my day! Thanks

**Comment by mrcel** [comment]
It works - you made my day! Thanks
