### ISSUE TITLE
Toggle All returns empty array

### ISSUE THREAD

**Issue by desaurabh** [daniel-nagy/md-data-table#132]
Hello i just landed in a weird scenario, the problem i was facing with the `toggleAll()`.

<h3>Situation</h3>

I've assigned variable name "selected" for `md-row-select` attribute and in the controller this `selected` array comes under the `$scope` variable.

<h3>Issue</h3>

Case 1: This works perfectly fine while selecting each list item separately, it fills the `selected` array with appropriate selected data. :+1: 

Case 2: While selecting the `toggleAll` checkbox the list items in the UI got selected but on the other hand the array `selected` inside the controller is supposed to get filled by all the selected items, whereas it still reflects the length `0`.

I've tried various methods to fix this problem even touched the  `md-data-table.js` but found no success, then i tried to find the bug in the [demo](http://danielnagy.me/md-data-table/) page & realized that the demo page is also struggling with the same error as i am. 
<strong>Ref 1</strong>
 <a href='http://postimg.org/image/s5rs3pmzn/' target='_blank'><img src='http://s29.postimg.org/s5rs3pmzn/one.jpg' border='0' alt="one" /></a>
<strong>Ref 2</strong>
<a href='http://postimg.org/image/icdp72o6j/' target='_blank'><img src='http://s9.postimg.org/icdp72o6j/two.jpg' border='0' alt="two" /></a>
Please help

**Comment by daniel-nagy** [comment]
I'm a little confused as to whats going on. I've created this [pen](http://codepen.io/anon/pen/JYYvjq?editors=101) that will log the selected items to the console from within the controller and it appears to be working fine.

I'll investigate this more when I have time.

**Comment by colintemple** [comment]
I haven't been able to duplicate this in your pen, and it certainly doesn't seem to be a problem in the demos, but I'm experiencing this problem as well in my implementation.

In my case, I can select individual rows, and they get added to the array.

If I select all rows with the top checkbox, the array is empty.

If I touch the top checkbox, the individual row selection never works -- after checking the top checkbox, the array stays empty no matter what I do next.

Same Angular version, same Angular Material version. No idea what might be causing it/interfering with that box.

**Comment by asdiallo** [comment]
I ran to same problem if add ng-if="true" to table element like: <table md-data-table class="md-primary" md-row-select="selected" md-progress="deferred"  ng-if="true">

**Comment by acfscience** [comment]
has anyone found a work around for this?

**Comment by jteresius** [comment]
+1
Adding the ng-if to a table element causes this error.

**Comment by daniel-nagy** [comment]
This may be a natural consequence of the `ngIf` directive.

> Note that when an element is removed using ngIf its scope is destroyed and a new scope is created when the element is restored. The scope created within ngIf inherits from its parent scope using prototypal inheritance. An important implication of this is if ngModel is used within ngIf to bind to a javascript primitive defined in the parent scope. In this case any modifications made to the variable within the child scope will override (hide) the value in the parent scope.

What version of this module are you using? I just tested an `ngIf` directive on the `mdTable` element in version **0.9.4** and the toggleAll feature still work.

If you can't update to version **0.9.4**, or it is still not working for you, try putting the `ngIf`directive on a parent element or use `ngShow`

**Comment by jteresius** [comment]
Thanks for the quick reply, Daniel. I'm using 0.8.14. Changing ng-if to ng-show fixed the problem :+1:

**Comment by colintemple** [comment]
In my case, the table was contained within an element that had an `ngIf` on it.

Updating to 0.9.4 seems to have resolved the issue. Thanks!
