### ISSUE TITLE
Using Track by object.id or $index breaks sort and limit

### ISSUE THREAD

**Issue by apat183** [daniel-nagy/md-data-table#133]
Hi,

I've noticed that when I use track by on my ng-repeat, it breaks sorting and page limits. 

Here is demo modified to use track by object.id. All I did to demo was add id's to all the data objects and add track by id on the ng-repeat. 

http://codepen.io/anon/pen/dYGaXN?editors=101

Am I doing something wrong?

Thanks.

**Comment by TimKlein87** [comment]
I was having the same problem. Track by syntax is very specific and should be at the end (after orderby). The issue is not related to this project.

More info: https://github.com/angular/angular.js/issues/5520

**Comment by apat183** [comment]
Great thanks, I'll update this.

**Comment by pouya-daneshvar-freelands-it** [comment]
hi guys, any update on this ?

**Comment by apat183** [comment]
No real update on this, you need to move the "track by" to end of statement, like noted by @timklein87 above. 

E.g.

'''<tr md-row md-select="assignment" md-select-id="{{assignment.$id}}" ng-repeat="assignment in assignCtrl.filteredAssignments | filter: {archived: assignCtrl.assignmentStatus} | orderBy: assignCtrl.query.order | limitTo: assignCtrl.query.limit : (assignCtrl.query.page -1) * assignCtrl.query.limit track by assignment.$id" ng-click="assignCtrl.openAssignment(assignment)">'''
