### ISSUE TITLE
Getting double extension importing via jspm

### ISSUE THREAD

**Issue by lucalenardi** [daniel-nagy/md-data-table#134]
It seems that loading the module with jspm, generates an exception due to the **extension being added twice**; server responds with `Cannot GET /jspm_packages/github/daniel-nagy/md-data-table@0.8.11/dist/md-data-table.min.js.js`

Removing a `.js` in [index.js#L4](https://github.com/daniel-nagy/md-data-table/blob/master/index.js#L4) actually solves the problem for jspm, but I do not know if it brakes Browserify support.

**Comment by rolandjitsu** [comment]
I think this has been fixed now.

**Comment by daniel-nagy** [comment]
This has been fixed in `0.9.x`
