### ISSUE TITLE
how do we customize rows shown?

### ISSUE THREAD

**Issue by seiyria** [daniel-nagy/md-data-table#141]
For example, the demo shows 5, 10, 15 rows. I want 10, 25, 50.

**Comment by daniel-nagy** [comment]
use the `md-row-select` attribute. [Pagination](https://github.com/daniel-nagy/md-data-table#pagination)

```javascript
<md-data-table-pagination md-row-select="[10, 25, 50]"></md-data-table-pagination>
```

**Comment by seiyria** [comment]
Awesome, thank you!
