### ISSUE TITLE
striped alternate rows?

### ISSUE THREAD

**Issue by seiyria** [daniel-nagy/md-data-table#143]
It might be nice when you have a table with a sizable chunk of info that's scaled down to mobile sizes. This would be implemented similar to bootstrap `table.table-striped`.

**Comment by joshtoo** [comment]
+1 if it is a configuration option

**Comment by daniel-nagy** [comment]
This is not included in the specification from Google and would be trivial to implement on your own using CSS selectors or `ng-class`.

**Comment by seiyria** [comment]
I wouldn't have it for more than a configuration option.
