### ISSUE TITLE
Column Ordering

### ISSUE THREAD

**Issue by daniel-nagy** [daniel-nagy/md-data-table#16]
Column ordering should be enabled or disabled on a per column basis instead of all or nothing. This shouldn't be too difficult to do. Instead of enabling column ordering for each column when the `md-order` attribute is specified, we could instead force explicit `order-by` attributes on the header cells to enable ordering.

**Comment by jameswyse** [comment]
:+1:

**Comment by daniel-nagy** [comment]
@jameswyse please confirm that commit 141aa5d18ae5d7a55082b23f173af01e0c8dc04f has solved this issue.

**Comment by jameswyse** [comment]
Sure does! Thanks a lot man! :beers:
