### ISSUE TITLE
Hiding the checkboxes ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [daniel-nagy/md-data-table#164]
Is there any way we can hide the checkboxes programmatically, I know there is option which says `md-disable-select` but it disables only clicking on the row and user can still select using the checkbox which has use cases in itself and good.

### Is there any way we can hide checkboxes, leaving a plain table with sortable headers ?

I tried using `display:none;` didn't worked out though!

**Comment by mjhasbach** [comment]
Omit the table `md-row-select` attribute.

**Comment by piyushchauhan2011** [comment]
Cool :+1: Works like a charm @mjhasbach
