### ISSUE TITLE
Progress bar of multiple table have conflicts

### ISSUE THREAD

**Issue by fotostat** [daniel-nagy/md-data-table#166]
I have used multiple tables simultaneously in view and it seems that both progress bars conflict with each other. Imho there are two bugs:
1. if I press refresh button of one table both progress bars start to be active.
2. Length of progress bar of first table is smaller than must be
For example look at http://plnkr.co/edit/IIQ37t11GCMzkwbForGd 
I use the last version of md-data-table (v0.8.14).

**Comment by YoungCatChen** [comment]
I'm meeting with the same issue. Would appreciate it a lot if it is solved!
