### ISSUE TITLE
ng-repeat-start and ng-repeat-stop support

### ISSUE THREAD

**Issue by artzub** [daniel-nagy/md-data-table#169]
I occasionally need to use ng-repeat-start.
Can you add support this directive?

**Comment by forcewill** [comment]
+1

**Comment by jchull** [comment]
ng-repeat-end is the end directive
+1

**Comment by DominicGaribaldi** [comment]
+1

**Comment by forcewill** [comment]
+1

Is it just me or it seems this project is starting to stalling :(

**Comment by jchull** [comment]
With all the changes, ng-repeat-start and ng-repeat-end work as expected. Recommend closing this issue.
