### ISSUE TITLE
How to force Single Item Selection

### ISSUE THREAD

**Issue by iyhammad** [daniel-nagy/md-data-table#175]
I needed this feature and I've implemented my own. I thought to share it with you.

```
        self.$scope.$watch(function ()
        {
            return self.selected;
        },
            function (newArray, oldArray)
            {
                if (newArray.length >= 2)
                {
                    for (var counter = 0; counter <= oldArray.length; counter++) {
                        for (var counterinner = 0; counterinner <= newArray.length; counterinner++) {
                            if (angular.equals(oldArray[counter], newArray[counterinner]))
                                newArray.splice(counterinner, 1);
                        }

                    }
                }

            }, true);
```

**Comment by m0rganic** [comment]
+1

**Comment by asdiallo** [comment]
+1

**Comment by thelordgabo** [comment]
+1

**Comment by jbdivups** [comment]
+1

**Comment by daniel-nagy** [comment]
If I understand correctly, you want to deselect the previous value when a new value is selected?

In version 0.9.0 you can achieved this be registering a select callback.

```html
<tr md-row md-select="item" md-on-select="onSelect" ng-repeat="item in items"></tr>
```

```javascript
$scope.onSelect = function (item, key) {
  if($scope.selected.length >= 2) {
    $scope.selected.shift();
  }
}
```

If you are using the new key feature you will need to use the new 'md.table.deselect' event to remove the key as well.

```html
<tr md-row md-select="item" md-on-select="onSelect" md-select-id="item.id" ng-repeat="item in items"></tr>
```

```javascript
$scope.onSelect = function (item, key) {
  if($scope.selected.length >= 2) {
    $scope.broadcast('md.table.deselect', selected[0], selected[0].id);
  }
}
```

**Comment by iyhammad** [comment]
I've Implemented the first solution and it works fine. But, now I've a problem that on the header row I've the select all check box which is inconsistent with the individual row selection mechanism.

**Comment by marcomafessolli** [comment]
@daniel-nagy have any plans for implement single row selection?

**Comment by ghahramani** [comment]
+1

I created my own with css:
I added single-select class to the parent of table and write this css ( SCSS ):

    .single-select {
        cursor: pointer;

        .md-checkbox-column, .md-checkbox-cell {
            display: none;
        }
    }

and then I added on-select callback to do something when the row is clicked

**Comment by Adam-Michalski** [comment]
How can I use single item selection with `md-on-select` and have checkboxes hidden? I think when we can select one item checkboxes are no more needed and I want to hide them.

**Comment by saratbhaswanth** [comment]
+1
