### ISSUE TITLE
ng-Class styling and md-row-select incompatible 

### ISSUE THREAD

**Issue by wengchen93** [daniel-nagy/md-data-table#177]
Implementing a mouseover function which turns table rows into another color as the user moves the cursor around the table. Only works when md-row-select is omitted OR "class" is used instead of "ng-class". Is there a way to keep both ng-class and md-row-select? (Need ng-class to enable conditional styling)

**Comment by gdoerr** [comment]
I needed this too and found a pretty simple way to do this:

In the `toggleRow` method of the `md-table-row` directive, add and remove the `md-selected` class to the row element. Next, in the `md-select-row` directive, comment out the line that adds the `ng-class` directive in the template function.

With this change, the `md-table-row` directive handles the class add/remove without the need for the `ng-class` which leaves it free for you to use.

**Comment by nicgirault** [comment]
+1 I would like to use ng-class in a tr balise

**Comment by daniel-nagy** [comment]
In `v0.9.x` the `.md-selected` class is toggled by the directive so you are free to use `ng-class` on a table row.
