### ISSUE TITLE
Request for Row Detail Section

### ISSUE THREAD

**Issue by yanko** [daniel-nagy/md-data-table#179]
How hard would it be to implement this feature?
something like datatable has, like this
https://www.datatables.net/examples/server_side/row_details.html

thank you!

**Comment by jchull** [comment]
I added support for ng-repeat-start, which was for enabling row details for my current project. 
https://github.com/daniel-nagy/md-data-table/pull/178

You can create multiple <TR> elements per iteration for the repeat and make the non-primary rows toggle pretty easily.
