### ISSUE TITLE
Fixed Header while Scrolling.

### ISSUE THREAD

**Issue by kalokamgit** [daniel-nagy/md-data-table#184]
Better to have a fixed header while scrolling.

**Comment by Pelu2k12** [comment]
+1

**Comment by BobDankert** [comment]
+1

**Comment by tucq88** [comment]
+1

**Comment by michaelkrnac** [comment]
+1

**Comment by b22n** [comment]
+1

**Comment by balakumaran-k** [comment]
+1

**Comment by TroodoNmike** [comment]
+1

Does anyone know what css/style i need to implement to make this work at the moment?

**Comment by dbartumeu** [comment]
+1

**Comment by smkamranqadri** [comment]
+1

**Comment by daniel-nagy** [comment]
What do you guys think? [pen](http://codepen.io/anon/pen/OMWNyj).

It's not quite ready yet. You'll notice the checkbox doesn't work (I know why). Once I fix the checkbox, and make it a little more efficient, I'll offer it as a separate module.

**Comment by BobDankert** [comment]
Looks good, except it's kinda of weird when scrolling down. At least on my phone, when I scroll down the header get really tall then snaps to normal size. It seems like there should be a max-height or something similar to prevent this. 

Nice work! Excited to see this available.

**Comment by daniel-nagy** [comment]
It's probably not behaving correctly on mobile within Codepen.

**Comment by daniel-nagy** [comment]
Let's move the discussion for this [here](https://github.com/daniel-nagy/fixed-table-header).
