### ISSUE TITLE
md-data-table overwrites the ng-class property of the tr element

### ISSUE THREAD

**Issue by aeisenberg** [daniel-nagy/md-data-table#199]
When you add an `ng-class` directive to the `tr` element that is part of the `ng-repeat` of a data table, the `ng-class` directive is overwritten by the md-data-table directive.  Eg, if you change the sample to have ng-class on the tr element like this:

```
      <tr md-auto-select 
      ng-class="{'too-many-calories': dessert.calories.value > 300}"
      md-disable-select="dessert.calories.value > 300" data-ng-repeat="dessert in desserts.data | orderBy: query.order | limitTo: query.limit : (query.page -1) * query.limit">
```

You will notice that this ng-class does not exist when the table is rendered in the browser.

I'll be putting up a pull request for this in a minute.

**Comment by daniel-nagy** [comment]
This shouldn't be an issue anymore.
