### ISSUE TITLE
Table Pagination Label

### ISSUE THREAD

**Issue by Fardinak** [daniel-nagy/md-data-table#20]
The `md-data-table-pagination` label ("Rows per page:") has been hard-coded which is not the ngMaterial way, and specially a problem when creating apps in non-english languages.

**Comment by daniel-nagy** [comment]
This is a valid point. I'll try to fit this in to the next release.

**Comment by daniel-nagy** [comment]
resolved in version 0.4.6 :)

**Comment by Fardinak** [comment]
That looks good; although, I believe that it should extend to the *of* as well! i.e. "x - y **of** n"

**Comment by shivasingh0101** [comment]
Failed to load template: templates.md-data-table-progress.html...
i am getting this error message and also rest of the templates are not being loaded in the local server.

**Comment by daniel-nagy** [comment]
@shivasingh0101 that's strange, what version of Angular are you using?

**Comment by shivasingh0101** [comment]
@daniel-nagy angular 1.4.0

**Comment by shivasingh0101** [comment]
![image](https://cloud.githubusercontent.com/assets/12746995/9085871/4b10b1d2-3b9e-11e5-948d-e60773e4ecf0.png)

This is the error showing on my browser...

**Comment by daniel-nagy** [comment]
Either they are not being loaded into the template cache or the template cache is somehow getting emptied?

**Comment by shivasingh0101** [comment]
Is there any issue with webpack coz we are using webpack to build our app....

**Comment by shivasingh0101** [comment]
And one more thing it worked when i loaded the js and css files into my main js file but still the pagination is not working i mean its redirecting to the next page but date is not rebinding.


![error_image2](https://cloud.githubusercontent.com/assets/12746995/9103550/00cb9cde-3c1d-11e5-8560-976120c1bc2e.png)

**Comment by Fardinak** [comment]
Is having a page number against the guidelines?
If not so, you could provide variables like $start, $end, $count, $total, $page, $totalPages (i.e. $index, $first, $last, etc. in ngRepeat) so the developer can format their own label like this:

```html
<md-data-table-pagination md-label="$start - $end of $total (page $page of $totalPages)">
```

That gives away some flexibility of representation; page numbers are more useful in most cases!

IMO, it would look way better than the current API anyway! :stuck_out_tongue_winking_eye: :

**Comment by Fardinak** [comment]
@daniel-nagy any comments on the latest suggestion?

**Comment by webpartisan** [comment]
I use angular-translate and would be good to use it with md-label together. Now there is no two-way binding with md-label and I can't change translation dynamically

**Comment by felansu** [comment]
+1

**Comment by thelordgabo** [comment]
Agree with @webpartisan I can not change the label dinamically with angular translate.

**Comment by Pelu2k12** [comment]
+1

**Comment by volmerf** [comment]
We also agree with @webpartisan that there is no 2-way binding currently. Switching the language of the website will not switch the language of the mdLabel. Only on refreshing the page the translation is triggered.

This is our code:

```
vm.updateTranslations();
$rootScope.$on('$translateChangeSuccess', updateTranslations);

function updateTranslations(event) {

            $translate(['GENERAL.PAGINATION.PAGE', 'GENERAL.PAGINATION.ROWS_PER_PAGE', 'GENERAL.PAGINATION.OF']).then(function (translations) {
                vm.paginationLabel.page = translations['GENERAL.PAGINATION.PAGE'];
                vm.paginationLabel.rowsPerPage = translations['GENERAL.PAGINATION.ROWS_PER_PAGE'];
                vm.paginationLabel.of = translations['GENERAL.PAGINATION.OF'];
            });
        }
```

Changing the language will trigger the updateTranslations function but will not update the label.

**Comment by raulsperoni** [comment]
@shivasingh0101 could you solve this? i'm facing the same problem...
