### ISSUE TITLE
Using limitBy for local pagination causes the table to briefly show twice the specified rows

### ISSUE THREAD

**Issue by prodonjs** [daniel-nagy/md-data-table#208]
See the following JSFiddle for an example. There are 500 rows and the pagination is happening client side with a default page size of 10. Clicking the next or prev page controls will briefly show double the amount of rows specified.

https://jsfiddle.net/h3mxo5xg/4/embedded/result/

**Comment by prodonjs** [comment]
Interestingly enough, the difference appears to be when using the HTML5 data- prefix in front of ng-repeat.

That example works properly when using ng-repeat:
http://codepen.io/anon/pen/OMMWXp

This example, with the only change being the use of data-ng-repeat on the tr tag exhibits the weird extra row rendering behavior:
http://codepen.io/anon/pen/addpyg

**Comment by daniel-nagy** [comment]
This should be fixed.
