### ISSUE TITLE
update dependency angular-material

### ISSUE THREAD

**Issue by maxime-menard** [daniel-nagy/md-data-table#210]
Not compatible with latest angular-material version : 1.0.0

**Comment by EvanWieland** [comment]
Works for me. What's your error?

**Comment by stefanahman** [comment]
I'm getting a difference:

v0.11.4
![screen shot 2015-12-16 at 16 59 14](https://cloud.githubusercontent.com/assets/1053201/11845903/69c34190-a416-11e5-9086-0328df2d5f60.png)

v1.0.0 (missing page size)
![screen shot 2015-12-16 at 16 58 34](https://cloud.githubusercontent.com/assets/1053201/11845907/6bdc7410-a416-11e5-9f58-145be8529719.png)

**Comment by EvanWieland** [comment]
@stefanahman I'm not using pagination on this current project. I'll enable it an see if mine fails as well.

**Comment by maxime-menard** [comment]
I'm getting an error to upgrade to the new angular-material version when I'm doing a "bower update".
The issue is on the file bower.json

**Comment by karoitay** [comment]
trying to force angular material to be @1.0.0 by running
```
meteor remove angular:angular-material
meteor add angular:angular-material@1.0.0
```

yields the following

```
=> Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint angular:angular-material@0.10.0 is not satisfied by angular:angular-material 1.0.0.
Constraints on package "angular:angular-material":
* angular:angular-material@1.0.0 <- top level
* angular:angular-material@0.10.0 <- dmgxmg:angular-material-data-table 0.7.6
```

**Comment by daniel-nagy** [comment]
This shouldn't be an issue anymore.
