### ISSUE TITLE
md-data-table.min.js.js 404 (Not Found)

### ISSUE THREAD

**Issue by Tyvain** [daniel-nagy/md-data-table#211]
```
Internal Error  Error loading "github:daniel-nagy/md-data-table@0.8.14/dist/md-data-table.min.js" at http://localhost:5000/jspm_packages/github/daniel-nagy/md-data-table@0.8.14/dist/md-data-table.min.js.js
Error loading "github:daniel-nagy/md-data-table@0.8.14/dist/md-data-table.min.js" from "src/bootstrap" at http://localhost:5000/src/bootstrap.js
Not Found: http://localhost:5000/jspm_packages/github/daniel-nagy/md-data-table@0.8.14/dist/md-data-table.min.js.js
```

The problem comes from index.js: ```require('./dist/md-data-table.min.js'); ```
Instead it should be ```require('./dist/md-data-table.min');```

What do you think?

**Comment by brownish** [comment]
Are you using angular 2?

**Comment by daniel-nagy** [comment]
The `.js` extension has been removed in `v0.9.x`. I you are using JSPM I believe it should work now.

**Comment by rudzikdawid** [comment]
**0.9.4** has this problem.
There is no ``dist/md-data-table.min.js`` file

Please change bower.json :
```
  "main": [
    "dist/md-data-table.js",
    "dist/md-data-table.min.css"
  ],
```
or put ``md-data-table.min.js`` into dist direcotry

**Comment by daniel-nagy** [comment]
**0.9.4** has minified version now

**Comment by rudzikdawid** [comment]
If you already installed **0.9.4** don't forget ``bower cache clean``
Anyway thanks for quick fix
