### ISSUE TITLE
Items selection is not maintained

### ISSUE THREAD

**Issue by thelordgabo** [daniel-nagy/md-data-table#214]
Steps to reproduce:
1.- Select some items in the first page.
2.- Navigate to the second page.
3.- Return to the first page.

Current Result:
- The selection is lost.
Expected result (from my point of view):
- The items selected in the first page should appear checked.

tested in: http://danielnagy.me/md-data-table/

**Comment by worldspawn** [comment]
The behaviour i have is the selection is maintained (chrome) between paging changes.

**Comment by thelordgabo** [comment]
Apparently this was fixed in the newest version.

**Comment by JorgeSegtowich** [comment]
@gabrielAnzaldo give a exemple?
