### ISSUE TITLE
Uncaught TypeError -v0.9.2

### ISSUE THREAD

**Issue by guanjinke** [daniel-nagy/md-data-table#218]
When I ran grunt command serve,  I got some errors.

The first is Uncaught TypeError: angular.module(...).decorator is not a function. 

I'm using angular 1.4.7

**Comment by daniel-nagy** [comment]
I get this error in `1.3.x` but I can't reproduce in `1.4.x`

**Comment by guanjinke** [comment]
I google it  and found something 

https://github.com/angular/batarang/issues/275

**Comment by daniel-nagy** [comment]
If you disable Batarang or run it in another browser does it work? I can perhaps decorate the service in a config block.

**Comment by guanjinke** [comment]
It works for me when I disable Batarang.

Thanks!
