### ISSUE TITLE
scope.range NaN

### ISSUE THREAD

**Issue by elasticrash** [daniel-nagy/md-data-table#219]
while everything works fine (like all previous versions) in 0.9x I sometimes get a RangeError: Invalid array length in line 1134 cause for some odd reason in the following function the total sometimes ends up being NaN

    scope.range = function (total) {
      return new Array(total);
    };

But nothing seems buggy or to misbehave in the application

**Comment by daniel-nagy** [comment]
The `total` parameter is the result of a call to the `pages` function to see how many pages there are.

```html
ng-repeat="num in range(pages()) track by $index"
```
```javascript
scope.pages = function () {
  return Math.ceil(scope.total / scope.limit);
};
```

As you can see if `scope.total` or `scope.limit` is not defined, or worse if `scope.limit` is `0` this will probably break.

I can do a little validation to make sure this doesn't happen.

**Comment by daniel-nagy** [comment]
This shouldn't be an issue anymore
