### ISSUE TITLE
md-desc not working as default value

### ISSUE THREAD

**Issue by acidmk** [daniel-nagy/md-data-table#221]
added md-desc to first column of CodePen example and it still sorted ascendant

**Comment by daniel-nagy** [comment]
That is because the controller is telling it to initially sort ascending.

change

```javascript
$scope.query = {
  order: 'name',
  limit: 5,
  page: 1
};
```

to 

```javascript
$scope.query = {
  order: '-name',
  limit: 5,
  page: 1
};
```
and it will sort descending.

**Comment by acidmk** [comment]
awesome, thanks! Since sept version version i used this code as workaround 

in controller ```vm.query.order = 'id' ```
html ``` ng-repeat="item in vm.currentItems | orderBy: '-' + vm.query.order |... ```

should be equivalent to  ```vm.query.order='-id' ``` but it did not work at all
