### ISSUE TITLE
NPM versions behind github

### ISSUE THREAD

**Issue by Andrew1503** [daniel-nagy/md-data-table#224]
I'm unable to get anything newer than 0.8.11 via npm.

Specifying `"angular-material-data-table": "0.9.x"` in my package.json results in the error:
```bash
$ npm install --no-bin-links
npm ERR! Linux 3.10.0-229.14.1.el7.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.10.36
npm ERR! npm  v3.5.2

npm ERR! No compatible version found: angular-material-data-table@0.9.x
npm ERR! Valid install targets:
npm ERR! 0.8.11
```

I checked the package on npmjs.com and it shows 0.8.11 is the latest
[https://www.npmjs.com/package/angular-material-data-table](https://www.npmjs.com/package/angular-material-data-table)

> 0.8.11 is the latest of 2 releases

**Comment by daniel-nagy** [comment]
Hmm... I thought npm would track it but maybe not. I might have to manually push updates to npm.

**Comment by daniel-nagy** [comment]
Okay I had to run the `nom publish` command. Try it now.

**Comment by Andrew1503** [comment]
Yep got the latest version now, thanks!
