### ISSUE TITLE
Parsing Error with Pagination

### ISSUE THREAD

**Issue by CoolestNerdIII** [daniel-nagy/md-data-table#225]
Thank you in advance for the amazing work. 
For me, when trying to implement paging similar to that in the example code, I am struck with the following error:

```
Error: $parse:ueoe
Unexpected End of Expression
```

```Unexpected end of expression: $label['page```

Honestly, I have no idea what I am missing and any help would be greatly appreciated. Thanks!

**Comment by daniel-nagy** [comment]
hmm... what example are you following? And what version of Angular are you using?

**Comment by CoolestNerdIII** [comment]
angular 1.4.8

**Comment by daniel-nagy** [comment]
Can you share some of your code or reproduce the error in the provided [Codepen](http://codepen.io/anon/pen/YwGJVr?editors=101)?

**Comment by CoolestNerdIII** [comment]
Here's the code that messes up, which I made pretty much identical to yours 

```
<md-table-pagination md-limit="query.limit" md-page="query.page" md-total="count" md-on-paginate="onPaginate" md-page-select></md-table-pagination>
```

Everything else works fine.
As for dependencies goes, I also have

**Comment by daniel-nagy** [comment]
You'll want to wrap `count` in angular brackets `md-total="{{count}}"`.

I don't think that is going to fix the error you were getting though.

**Comment by CoolestNerdIII** [comment]
Nice catch! But yeah unfortunately not

**Comment by daniel-nagy** [comment]
Is that the full error the browser spits out? Can you give it to me verbatim? I have a feeling something else may be wrong.

**Comment by CoolestNerdIII** [comment]
Here is a link to the browser error: https://docs.angularjs.org/error/$parse/ueoe?p0=$label%5B%27page

Here is the console error:

**Comment by daniel-nagy** [comment]
wtf? The only thing I can think of is maybe the template is not loaded correctly into the cache and the trailing `]` is stripped from `{{$label[\'page\']}}` [link](https://github.com/daniel-nagy/md-data-table/blob/master/dist/md-data-table.js#L1275). But that seems unlikely. What browser / operating system are you using?

**Comment by CoolestNerdIII** [comment]
Cool so I am not the only one confused

**Comment by daniel-nagy** [comment]
Without being able to reproduce it I don't know if I can help you

**Comment by CoolestNerdIII** [comment]
I figured out the error. Not sure why it took me so long. My project is built using a Django backend, so I am using ``` [[  ]] ``` instead of ``` {{  }} ``` with the command ```$interpolateProvider.startSymbol('[[').endSymbol(']]');``` in my app.js.

By removing this, I fix the error. Not sure if its something that is a bug per-say, or I may just have to use brackets. But thanks!
