### ISSUE TITLE
[Feature] Is Row dirty

### ISSUE THREAD

**Issue by bastienJS** [daniel-nagy/md-data-table#226]
Hello Daniel,

its super that you finally implemented the Large/Small Dialog for cell editing.

I asked myself how can I use this demo application in real life. 

What i want is to enter multiple cell values THEN click a create/add button positioned  on the edited row. This button may only be enabled when the cell values data is valid.

1) Thus I need a md-row isValid() function.
2) Furthermore the content of the invalid cells should not be rejected when I leave the cell or confirma via enter/return key.

Without this new behavior "Row-Inline-Editing" I see only less real world use for the new editing dialogs. Nearly nobody is saving a single cell value to the database. Only a full entity.

**Comment by daniel-nagy** [comment]
I think I know what you mean but if you want to edit multiple cells before saving, I think it would be better to open a custom dialog. You can create a custom dialog using this module's `$mdEditDialog` service or Angular Material's `$mdDialog` service.

You can then place an icon in a table cell to launch a dialog for the item you want to edit.

**Comment by bastienJS** [comment]
Some month later I take back what I said. Modifiying a single field in the UI ;-)

"Nearly nobody is saving a single cell value to the database. Only a full entity."
