### ISSUE TITLE
v0.9.4 - require is not defined

### ISSUE THREAD

**Issue by stefanahman** [daniel-nagy/md-data-table#227]
Getting the following error in v0.9.4.

![image](https://cloud.githubusercontent.com/assets/1053201/12088250/da3907f8-b2d9-11e5-8274-4d2af26cb755.png)

Note, I'm using Rails Assets: https://rails-assets.org/

**Comment by daniel-nagy** [comment]
I'm not sure why your application is looking at `index.js`. That file is for people who need commonJS style module loading.

Looking at Rails Assets' home page,

> You can now require BOWER_PACKAGE_NAME in your stylesheets and JavaScript files—all assets exposed as main in bower.json will be automatically included.

I do have the files exposed as main in [bower.json](https://github.com/daniel-nagy/md-data-table/blob/master/bower.json#L5).

It looks like the require syntax should be,

```javascript
//= require angular-material-data-table
```

**Comment by daniel-nagy** [comment]
Any update on this?

**Comment by stefanahman** [comment]
Closed due to inactivity.
