### ISSUE TITLE
Edit Dialog targetEvent

### ISSUE THREAD

**Issue by pdore-netfore** [daniel-nagy/md-data-table#229]
Why does the $event target need to be restricted in such a way?
```
if(!options.targetEvent.target.classList.contains('md-cell')) {
  return logError('The event target must be a table cell.');
}
```

This check break the case where the cell contains complex content:
``` 
<td md-cell ng-click="showEditDialog(...)">
    <div layout="row">
        Testing
        <div flex></div>
        <md-icon>edit</md-icon>
    </div>
</td>
```
*NOTE: This is pseudo-code*

In this case, the $event.currentTarget isthe div (not the 'md-cell') which shows an error in the console and does not show the dialog.
From a quick investigation, removing the check shows the dialog correctly.

**Comment by daniel-nagy** [comment]
Okay, this is something I will need to fix. The reason I do that check is to make sure the source of the click is a table cell. I need the table cell to position the dialog.

I think I may just need to change `target` to `currentTarget` or something equally as simple. I should be able to get to this later today.

If you get to it before me make a pull request.
