### ISSUE TITLE
The onboard demo with grunt is not working - infinite-earth-4803

### ISSUE THREAD

**Issue by anderskristian** [daniel-nagy/md-data-table#23]
Hi Daniel
The demo is using the resource $resource('http://localhost:3000/nutriton/desserts')
I do not run anytning on port 3000
I find that this link is stopping my attempt to verify the software.
I saw the online version and have downloaded https://infinite-earth-4803.herokuapp.com/nutriton/desserts/:id
There was 50 items. 
I put them into the nutritionResource, changed the controller from "get()" to just let the variable assign to desserts
Now I see the 50 rows.
Now I try to sort the data... But it does not work as I see it.
I have used nearly two hours to figure out this. 
I would be much more happy that the sample was running without having to tweek these things.
Therefore I file the bug.
The problem makes me not get into what I want....
I need to find out if I can make links in the fields. But can I. I don't know because I have to use all my time on just getting the sample to work..

Anyway it is great work you have made.. 
I'm just not total happy about the infinite-earth-4803 stunt. It makes me unpappy.
There is really a lot of good design in using the HTML table, tr,th,td tags.

**Comment by daniel-nagy** [comment]
Sorry, I really should have put more effort into documenting how to run the app locally with the nutrition-app. The nutrition app is a NodeJS server and runs on port 3000, you can start the app by typing `npm start` in the console. The app expects you to have MongoDB installed locally. There is a script included called `desserts.js` that you can run to import test data into your local running database. This requires you to have some knowledge of Node and MongoDB.

I think I may just remove the server interaction from the demo app to make it easier for people who want to contribute and just do the sorting and pagination in the client.

**Comment by anderskristian** [comment]
Thanks a lot
Yes I would like the simple edition :-)

**Comment by daniel-nagy** [comment]
Please see commit f435b0df5a7177093e17a3d75558a344c3726b5b and the update [here](https://github.com/daniel-nagy/md-data-table#contributing). :smiley:
