### ISSUE TITLE
ng-repeat-{start | end} and selection 

### ISSUE THREAD

**Issue by forcewill** [daniel-nagy/md-data-table#232]
I have a table with row, each row can be collapsed/expanded so i have two `tr` like this

    <tr md-select="u" ng-repeat-start="u in data">..</tr>
    <tr ng-show="expanded" ng-repeat-end>....</tr> 

I'm having an issue with that this way i cannot select/unselect all rows properly using the checkbox in the table header i think its because md-data-table thinks that since i use two for each row i have `2 * data.length` rows in my table which is incorrect,  

unless i also place an  ```md-select="u" ```  in the second `tr` however using this aproach i will end up with 2 checkbox for each row in my table which is not intented

**Comment by daniel-nagy** [comment]
Should be fixed in latest patch.

**Comment by forcewill** [comment]
Thanks i temporarily fixed the situation by declaring the md-select on both `tr's` and hiding the even ones in css
