### ISSUE TITLE
mdEditDialog: "type" attribute is not working

### ISSUE THREAD

**Issue by lyschoening** [daniel-nagy/md-data-table#237]
The `type` option is not working as expected. To reproduce specify e.g. `{type: 'number'}`.

The issue is in this line: 
https://github.com/daniel-nagy/md-data-table/blob/0ee26b9b9f03cda3789cfdbf74b3463a4543bd23/app/md-data-table/scripts/mdEditDialog.js#L255

```javascript
var attrs = 'type="' + options.type ? options.type : 'text' + '"';
```
It should read:

```javascript
var attrs = 'type="' + (options.type ? options.type : 'text') + '"';
```

As it reads now, `attrs` is always set to `options.type`, as opposed to ``type="${options.type}"``.

**Comment by daniel-nagy** [comment]
Fixed!
