### ISSUE TITLE
Weird $parse error in v0.8.13

### ISSUE THREAD

**Issue by ihmcjacky** [daniel-nagy/md-data-table#238]
Previously I am using v0.8.10 working pretty well, but I want the infinite scroll feature, so I try to update the version to v0.8.13, with the same code running (see the jsFiddle for the error reproduced), I was kept notified by the following message
```
Error: [$parse:syntax] Syntax Error: Token 'in' is an unexpected token at column 8 of the expression [pDatum in pData] starting at [in pData]
```

JsFiddle (v0.8.13): <a href="https://jsfiddle.net/b7uyc8ms/">https://jsfiddle.net/b7uyc8ms/1/</a>
JsFiddle (v0.8.10): <a href="https://jsfiddle.net/b7uyc8ms/">https://jsfiddle.net/b7uyc8ms/</a>

I found that ever since adding the virtual repeat attribute (infinite scroll feature) this problem arised, as changing back to v0.8.10 (without this feature), the problem is gone, I already stuck in this for a whole day, and appreciate for the help, thanks!

**Comment by daniel-nagy** [comment]
The fork you were pulling from is no longer available it seems. If I change the rawgit to my library it works. [jsFiddle](https://jsfiddle.net/caww3gp4/). I have a different [module](https://github.com/daniel-nagy/fixed-table-header) for fixed table headers you can use to scroll the table.

**Comment by ihmcjacky** [comment]
Hi Daniel, thanks for the kind help, I am able to get the v0.8.13 loaded up and will try to implement the infinite scroll. Thanks for the help!

I have viewed the fixed table headers before, I think that is to prevent the header from being scrolled together after implementing the infinite scroll right?

**Comment by ihmcjacky** [comment]
I can do an infinite scroll in table now, thanks! But I cannot find any checkbox any more, it seems that without ng-repeat, there are no md-checkbox, is there any workaround regarding on this? Thanks!

**Comment by daniel-nagy** [comment]
Are you still having issues? You should update to **0.9.x**.

**Comment by daniel-nagy** [comment]
Closing in favor of newer versions
