### ISSUE TITLE
md-checkbox-column should have a set width

### ISSUE THREAD

**Issue by gligoran** [daniel-nagy/md-data-table#239]
When a table only has a column or two but the table is wide (i.e. full width on 1080p), the ```md-checkbox-column``` grows like so:

![2016-01-10_17-52-20](https://cloud.githubusercontent.com/assets/444829/12222669/163d46fe-b7c3-11e5-8a8e-0126fa6fd81e.png)

I think the checkbox column should have fixed with no matter the number of columns and the contents of cells.

The image above can be recreated by simply deleting all but one column in the codepen demo.

**Comment by daniel-nagy** [comment]
Should be fixed now. Instead of creating a new patch I just moved the last tag **v0.9.7** to the latest comment.

**Comment by gligoran** [comment]
It's in the lines by what I meant, but with this solution it not cuts off the ink ripple effect of Angular Material.
