### ISSUE TITLE
sample with local collection please

### ISSUE THREAD

**Issue by anderskristian** [daniel-nagy/md-data-table#24]
Hi Daniel
I do not understand how I should implement $watchCollection()
I do not have a service I can call to get things sorted etc.
I have an array with data.
I declare where the data is
I declare what key is mapped to what column
From there offf. I expect the md-data-table to take care of the rest

I see the controller uses 'ngResource' .. in my eyes this dramastically reduces the use-cases where md-data-table can be used.

I compare current solution to http://iamisti.github.io/md-data-table/ where the model is very easy to understand. Unfortunally the markup is too limited in iamisti solution. So I need to go with this solution. I just need to understand how to use it.

**Comment by anderskristian** [comment]
Hi Daniel
Thanks a lot. 
Now it is 2^10 times easier to understand

**Comment by daniel-nagy** [comment]
:+1:
