### ISSUE TITLE
Header row disappeared

### ISSUE THREAD

**Issue by f1tech** [daniel-nagy/md-data-table#240]
I just upgraded to the latest and the header rows for both of my datatables disappeared. When I inspect the rendered html they are all present, but have a height of 0 pixels. 

I'm using the latest Angular 1.4.8, Angular Material 1.01 and have duplicated this after eliminating all of my custom css. 

I'm using ui-router and loading the tables within a div. This is the HMTL for the first one:

    <md-data-table-container>
	<table md-data-table md-progress="deferred" class="md-primary">
		<thead md-order="orders.ordersQuery.order" md-trigger="orders.sortOrders" >
			<tr>
				<th name="Sold To" order-by="SAPID"></th>
				<th name="File Name" order-by="FILE_NAME"></th>
				<th name="PO #" order-by="PO"></th>
				<th numeric name="Lines" order-by="ORDER_LINES"></th>
				<th numeric name="Found" order-by="ITEMS_FOUND"></th>
				<th numeric name="Cancelled" order-by="ITEMS_CANCELLED"></th>
				<th numeric name="Prior" order-by="ITEMS_PREVIOUSLY_ORDERED"></th>
				<th numeric name="Dupes" order-by="ITEMS_DUPLICATE"></th>
				<th numeric name="Qty Mistmatch" order-by="ITEMS_QTY_MISMATCH"></th>
				<th numeric name="Wrong Country" order-by="ITEMS_WRONG_COUNTRY"></th>
			</tr>
		</thead>
		<tbody>
			<tr 
				md-auto-select 
				ng-repeat="order in orders.FTPOrderList | orderBy: orders.ordersQuery.order" 
				ng-dblclick="orders.rowDoubleClick(order)"
				ng-click = "orders.onRowClick(order)" 
				ng-class="orders.getRowClass(order)">
				
				<td>{{order.SAPID}}</td>
				<td>{{order.FILE_NAME}}</td>
				<td>{{order.PO}}</td>
				<td>{{order.ORDER_LINES}}</td>
				<td>{{order.ITEMS_FOUND}}</td>
				<td>{{order.ITEMS_CANCELLED}}</td>
				<td>{{order.ITEMS_PREVIOUSLY_ORDERED}}</td>
				<td>{{order.ITEMS_DUPLICATE}}</td>
				<td>{{order.ITEMS_QTY_MISMATCH}}</td>
				<td>{{order.ITEMS_WRONG_COUNTRY}}</td>
			</tr>
		</tbody>
	</table>
    </md-data-table-container>

I don't see anything out of the ordinary here.

**Comment by daniel-nagy** [comment]
If you upgraded from version **0.8.x** to **0.9.x** there are a few syntax changes. Please refer to the documentation.

**Comment by f1tech** [comment]
Thanks, that was indeed the issue. The only thing I can't seem to figure out is what syntax changed with regard to sorting. All of my sortable columns sort properly, but the up arrow icon appears for all of them and doesn't change when the column is clicked.
