### ISSUE TITLE
md-order-by does not work

### ISSUE THREAD

**Issue by Nihn** [daniel-nagy/md-data-table#243]
Hi,

I cannot force md-order-by to work, I've tried to debug a little and it seems that `headCtrl` has isolated scope.

My code (ng-init, ng-click and orderBy are my workaround for this issue):
```javascript
      <md-table-container ng-if="tableVisible">
        <table md-table md-progress="promise">
          <thead md-head>
            <tr md-row>
              <th md-column md-order-by="name" ng-init="attrOrder=false" ng-click="attrOrder=!attrOrder"><span>Attribute</span></th>
              <th md-column><span>Value</span></th>
            </tr>
          </thead>
          <tbody md-body>
            <tr md-row ng-repeat="attr in treeService.getSelectedDetails() | orderBy:'name':attrOrder">
              <td md-cell class="attr-cell"><span class="attr attr-name">{{ attr.name }}:</span></td>
              <td md-cell class="attr-cell"><span class="attr">{{ attr.value }}</span></td>
            </tr>
          </tbody>
        </table>
      </md-table-container>
```

I'm using Angular 1.4.7 Angular-Material 1.0.0 and md-data-table 0.9.7 version.

**Comment by daniel-nagy** [comment]
`ng-if` creates an isolated scope. Variables in the child scope will overwrite variables in the parent scope. I suspect this may be the problem.

**Comment by Nihn** [comment]
@daniel-nagy I tried that, `ng-if` has no influence here.

**Comment by daniel-nagy** [comment]
You are missing the `md-order` attribute on the `<thead>` element.

```html
<thead md-head md-order="myOrder">
```

The `md-order-by` attribute sets the `md-order` attribute.

**Comment by Nihn** [comment]
@daniel-nagy thanks, it worked :).
