### ISSUE TITLE
Select All checkbox is checked if all rows are disabled

### ISSUE THREAD

**Issue by davidcui2** [daniel-nagy/md-data-table#248]
Described in the title. Here's the simple [codepen](http://codepen.io/zhc/pen/KVvaaR?editors=101).

When look into the code `mdHead.js`, it seems that disabled rows have the same effect with selected rows, which is fine for most cases.

    scope.allSelected = function () {
      var rows = tableCtrl.getBodyRows();
      
      return rows.length && rows.map(getController).every(function (ctrl) {
        return !ctrl || ctrl.disabled || ctrl.isSelected();
      });
    };

Maybe the "Select All" checkbox should be disabled if all rows are disabled? Because the current experience just doesn't feel right for me.

**Comment by ghahramani** [comment]
+1

**Comment by daniel-nagy** [comment]
This one should be resolved.
