### ISSUE TITLE
$mdSticky and md-data-table

### ISSUE THREAD

**Issue by f1tech** [daniel-nagy/md-data-table#251]
Late in the game the Angular Material team added $mdSticky to the mix.  I've been using it with a custom directive like this:

    app.directive('sticky', Sticky)

    Sticky.$inject = ['$mdSticky'];
    function Sticky($mdSticky) {
        return {
            restrict: 'A',
            link: function (scope, element) {
                $mdSticky(scope, element);
            }
        }

This generally works ok, but it doesn't handle bindings or things that are styled dynamically well. If I use this directive on either the <thead> or the <tr> within the <thead> it does make the header sticky, but when I scroll far enough, the headers all revert to some ugly fonts and resize. $mdSticky basically makes a clone of an element and then shows that clone when the element is moved off the screen. What's happening is the clone is made too early in the process. If anyone has had any success getting around this with $mdSticky, lmk. It seems like all that's needed to be done is update the clone after the header has completely finished rendering. I don't know where to do that. It'd be great if there was a sticky header option in md-data-table.

**Comment by daniel-nagy** [comment]
I wrote a separate [module](https://github.com/daniel-nagy/fixed-table-header) to fix the table header. May or may not be what you're after.

I'll have a look at the `$mdSticky` service.

**Comment by f1tech** [comment]
Thanks. That looks like the ticket. It seems to do exactly what I expected $mdSticky to do. BTW, are you back in the 419?

**Comment by daniel-nagy** [comment]
By 419 do you mean area code? I'm still in Ohio at the moment.

**Comment by f1tech** [comment]
Yeah, I went to your site and saw your phone # is in the 419 area code and IIRC, that you were going to graduate in December. I’m in Toledo and was curious if you’re local now.

**Comment by daniel-nagy** [comment]
I graduated in December. I will be in Athens till summer (5 months or so). I haven't decided my future beyond that.
