### ISSUE TITLE
md-auto-select md-button

### ISSUE THREAD

**Issue by scriptsure** [daniel-nagy/md-data-table#254]
If i have md-auto-select implemented on a table...and on each row i have a md-button... for a detail view capability... how can i stop the row from being checked/selected when i click the button?

thanks

**Comment by daniel-nagy** [comment]
You will need to stop propagation in your click handler.

```html
<tr md-row ng-repeat="item in items" md-select="item" md-auto-select>
  <td md-cell>
    <md-button ng-click="moreDetails($event, item)"></md-button>
  </td>
</tr>
```

```javascript
$scope.moreDetails = function ($event, item) {
  $event.stopPropagation();
};
```

**Comment by scriptsure** [comment]
ah excellent.. thanks!!!!
