### ISSUE TITLE
page set to NaN in $pagination.limit $watch()

### ISSUE THREAD

**Issue by andryfailli** [daniel-nagy/md-data-table#255]
If `$pagination.limit` changes from `undefined` to a number, calculating the following formula `Math.floor(((self.page * oldValue - oldValue) + newValue) / (isZero(newValue) ? 1 : newValue))` will cause `self.page` to be set to `NaN`.

I've wrapped the formula in an if and it works.

```javascript
$scope.$watch('$pagination.limit', function (newValue, oldValue) {
  if(newValue === oldValue) {
	return;
  }
  
  if(!isNaN(newValue) && !isNaN(oldValue)) {
	// find closest page from previous min
	self.page = Math.floor(((self.page * oldValue - oldValue) + newValue) / (isZero(newValue) ? 1 : newValue));
  }
 
  self.onPaginationChange();
});
```

**Comment by daniel-nagy** [comment]
This change has been added in `v0.10.4`, [mdTablePagination.js:90](https://github.com/daniel-nagy/md-data-table/blob/master/src/scripts/mdTablePagination.js#L90).
