### ISSUE TITLE
When will angular:angular-material@1.0.2 will be supported?

### ISSUE THREAD

**Issue by roytz** [daniel-nagy/md-data-table#257]
This package seems great but it supports angular:angular-material@0.11.4 at most and it's pretty old.
Do you have any prediction when will you release a version that supports angular:angular-material@1.0.2?

**Comment by daniel-nagy** [comment]
Check that you are using the current version, **0.9.8**, which supports angular-material **^1.0.0**

**Comment by f1tech** [comment]
I'm using 1.02 without issue.

**Comment by roytz** [comment]
Thank you.
I've git cloned the fork into my packages folder but when I run the "meteor add angular-material-data-table" command I get a message saying there's no such package. What am I doing wrong?

**Comment by Koslun** [comment]
This and most angular projects officially only support bower, npm and jspm. So though someone here might know or be kind enough to find out I think it's out of scope for this project.

So think you would be better off asking that question at some Meteor blog, forum, etc or stackoverflow. Though I doubt you're the first person having this problem and should thus have it relatively easy to just find the question and answer at some Meteor resource.

**Comment by TrikinCurt** [comment]
roytz,

I am not meteor export (by any stretch), but unless you are running the 1.3 beta, packages come from atmosphere.  So unless someone is making/updating/etc a atmosphere package for this project, it won't be found.

In the short term, you can roll your own, docs are at meteor.  In the medium term, 1.3 thankfully dumps atmosphere and supports npm.
