### ISSUE TITLE
rows lines

### ISSUE THREAD

**Issue by csotomon** [daniel-nagy/md-data-table#261]
Hi, with the new versión, the lines between the rows disapears.

how can I return the lines back?

![error familias](https://cloud.githubusercontent.com/assets/9087039/12497053/791d8a20-c067-11e5-9112-1708c16bedaf.png)

**Comment by daniel-nagy** [comment]
You either have conflicting CSS styles or you do not have all the required attributes. In the new version every element has a required attribute: `md-table`, `md-head`, `md-row`, `md-column`, `md-body`, and `md-cell`. See the template in the [usage](https://github.com/daniel-nagy/md-data-table#usage) example. I probably should do a better job of documenting this.

**Comment by csotomon** [comment]
Hi daniel, thank you for your help, the problem was that a I missed the  md-cell attribute.
