### ISSUE TITLE
mdOptions not binding

### ISSUE THREAD

**Issue by jmorvan** [daniel-nagy/md-data-table#263]
The mdOptions attribute is not working for me.

options is defined on my scope like this 

````
$scope.options = [50,100,500,1000];
```
and my table
```
<md-data-table-pagination 
md-limit="query.limit" 
md-page="query.page" 
md-label="query.label" 
md-options="options" 
md-total="{{data.count}}" 
md-on-paginate="onPaginationChange">
</md-data-table-pagination>
```

actually md-on-paginate also doesnt get triggered, but i solved this with $watch on page and limit.

from the code it seems mdOptions is bound to the controller ($pagination).

Any clues?

**Comment by daniel-nagy** [comment]
I suspect you are using version **0.8.x** and looking at the documentation for **0.9.x**. The attributes `md-options` and `md-on-paginate` are new in version **0.9.x**. Also, the element has been renamed to just `md-table-pagination`.

**Comment by super-coder** [comment]
i am having the same issue, here is a fork of your codepen http://codepen.io/anon/pen/ONVBYa 
i am setting 
`$scope.itemsPerPageSelect = [50,100,500,1000];`
and
`md-options="itemsPerPageSelect" md-table-pagination='itemsPerPageSelect'`
and no reaction

**Comment by super-coder** [comment]
i got it, i needed to put in 
`<md-table-pagination md-options="options"...`
