### ISSUE TITLE
mdOnSelect method does not run if no selection

### ISSUE THREAD

**Issue by hectorgr** [daniel-nagy/md-data-table#264]
I need to execute a function when no row is selected, but the method in md-on-select = "mymethod" is not triggered, this is triggered only when a row is selected. Any solution?

**Comment by daniel-nagy** [comment]
There's a deselect callback, `md-on-deselect`, you could use to check if the number of selected items is zero.

**Comment by hectorgr** [comment]
thanks, it's just what I needed.
