### ISSUE TITLE
Support for material-angular colors

### ISSUE THREAD

**Issue by hectorgr** [daniel-nagy/md-data-table#265]
I'm using the material-angularjs and would like to place background color in the "thead" element, similar to `<md-content class = 'md-hue-3'>` or `<md-toolbar class = 'md-accent md-hue-3'>` .
I've tried unsuccessfully to be nice to support this

**Comment by jmls** [comment]
+1

**Comment by hectorgr** [comment]
With a recent version of Angular Material is not necessary, it is possible solve with md-colors directive.
```
<thead>
  <tr md-row md-colors="{background: 'accent-100'}"> ..... </tr>
</thead>
```
