### ISSUE TITLE
Complete code example

### ISSUE THREAD

**Issue by KalpanaAr** [daniel-nagy/md-data-table#267]
I am new to AngularJS and material. Can some one provide me complete code example? I am especially looking for $nutrition service as this snippet of code in Sample Controller (function getDesserts(query) {
    $scope.promise = $nutrition.desserts.get(query, success).$promise;
  })
is difficult for me to understand. Appreciate your help. Thanks!

**Comment by timmyrosen** [comment]
You should probably read up a bit more on angular itself before you post an issue on a third party library.

**Comment by daniel-nagy** [comment]
https://github.com/daniel-nagy/md-data-table/blob/gh-pages/scripts/nutritionResource.js
