### ISSUE TITLE
How to implement search functionality like shown in demo

### ISSUE THREAD

**Issue by KalpanaAr** [daniel-nagy/md-data-table#268]
Can someone please update documentation for search functionality like shown in demo? I want to filter my list based on input from user. I have implemented like below but it doesn't really work as shown in md-data-table demo. Any help on this is much appreciated. Thanks!

code:

controller
 $scope.filterList = function(searchText){
        if(searchText.length===0) $scope.sample.data = $scope.data;
        else $scope.sample.data = $filter('filter')($scope.sample.data, searchText);
      };

html
  <input ng-model="searchText" type="text" placeholder="search" ng-change="filterList(searchText)">
..
 <tr md-row md-select="s" md-select-id="{{s._id}}" md-auto-select ng-repeat="s in sample.data | orderBy: query.order">

**Comment by daniel-nagy** [comment]
You can view the source code for the live demo in the [gh-pages](https://github.com/daniel-nagy/md-data-table/tree/gh-pages) branch.
