### ISSUE TITLE
Checkbox focus problem

### ISSUE THREAD

**Issue by Knoxvillekm** [daniel-nagy/md-data-table#269]
From demo [Codepen](http://codepen.io/anon/pen/YwGJVr?editors=101)

1. After clicking the top element is highlighted
![1](https://cloud.githubusercontent.com/assets/11072464/12696074/175c4886-c769-11e5-9572-be9e0025d232.jpg)

2. After clicking and return from other tab it focused
![2](https://cloud.githubusercontent.com/assets/11072464/12696073/175bdc02-c769-11e5-999d-eb6b6c9a8665.jpg)

And there are no problems when pressing the row.

**Comment by daniel-nagy** [comment]
> After clicking the top element is highlighted.

I wasn't able to reproduce.

> After clicking and return from other tab it focused.

This is an issue with the checkbox directive from Angular Material.

**Comment by Knoxvillekm** [comment]
> This is an issue with the checkbox directive from Angular Material.

This style fix my problem
```
md-toolbar.md-table-toolbar.ng-hide {
    display: none;
}
```
