### ISSUE TITLE
Client-side sorting directive

### ISSUE THREAD

**Issue by twrk** [daniel-nagy/md-data-table#27]
Having trouble following the client-side sorting example (using `md-order`) outlined in the README. 

Here's a [plunker](http://plnkr.co/edit/LTWBSO2BGx48xuSs1X9z?p=preview) demonstrating that clicking a `<th>` apparently has no effect on the sort order (although watching the `ctrl.order` variable in the `md-data-table` directive proves that it is being updated on click).

Am I missing a step? If so, I'd be happy to submit a PR for the README with additional detail.

**Comment by twrk** [comment]
Might have uncovered another issue with this [plunker](http://plnkr.co/edit/LTWBSO2BGx48xuSs1X9z?p=preview): the `<tbody>` has the `md-auto-select` directive. As intended, clicking anywhere in the row adds the element to the `selected` array; however, the corresponding `md-checkbox` appears to not have the `md-checked` class applied.

**Comment by daniel-nagy** [comment]
@twrk I've [updated](http://plnkr.co/edit/sLw7cwhooidqObv1qdIK?p=preview) the version of Angular in your provided plunker to version 1.4.x and everything seems to be working as expected. I'm not sure what incompatibility is being experienced with Angular 1.3.15. Do you need to use Angular 1.3.15 in your app or are you able to update?

**Comment by twrk** [comment]
Ahh yeah, that'll do it, thanks! And 1.4 works just swimmingly for me :)

**Comment by daniel-nagy** [comment]
:+1:

**Comment by nvme978** [comment]
I'm facing the same issue with Angular 1.3.15. 
Is there any workaround for this version of angular? I cannot update to 1.4.x without getting multiple approvals.
