### ISSUE TITLE
Dropdowns sticks to top of view

### ISSUE THREAD

**Issue by juriw** [daniel-nagy/md-data-table#270]
Hi

I just implemented the md-data-table demo example in my project and everything works great expect the dropdown menus for "row per page" and "page selector". Please see the attached screen shot.

Any ideas on what is causing this behaviour? 

![localhost_admin_index_html__toogle1_item1](https://cloud.githubusercontent.com/assets/7030932/12702450/d53d3a66-c829-11e5-9323-1bf5a00ba8f3.png)

**Comment by daniel-nagy** [comment]
I'm not sure why that would happen. I think this is an issue with the `md-select` directive.

**Similar issues**
* https://github.com/angular/material/issues/5754
* https://github.com/angular/material/issues/5435

**Comment by juriw** [comment]
After I cleaned up in my CSS the problem was gone. It had something to do with my sidenavbar where instead of height:100% on that, I had 100% on the whole body and that messed it up.

**Comment by vapits** [comment]
@juriw can you replicate it somehow and have some code example here to share with us?
