### ISSUE TITLE
Access table options in the template

### ISSUE THREAD

**Issue by bampakoa** [daniel-nagy/md-data-table#273]
Hi,

Is it possible to define options in the table such as: `<table md-table md-options="{order:'name', page: 1, limit: 5}>"` and then reference them in the template html such as : `<md-table-pagination md-limit="options.limit" md-page="options.page">` without set them in the controller?

**Comment by daniel-nagy** [comment]
In order for two way data binding to work you must pass a variable to the `md-options` attribute. You probably get a none assignable error if you try to do it that way. I could use `scope.$eval` to get the value of the attribute but then you wouldn't be able to access, or modify, it within your controller.

You could use `ng-init` to initialize the variable within the template; however, the Angular folks recommend using `ng-init` with caution.

**Comment by bampakoa** [comment]
Ok, I see. Right now, I use it without set **md-options** directly in the table. Instead, I set  it inside the controller and reference it in **md-table-pagination**. So, what is the point of using md-options in the table?

**Comment by daniel-nagy** [comment]
I'm sorry, I wasn't paying close attention to your question. There is no `md-options` attribute on the `md-table` element. There is an `md-options` attribute on the `md-table-pagination` element but that lets you change the select options for the row limit.
