### ISSUE TITLE
Load table with rows pre-selected

### ISSUE THREAD

**Issue by GBora** [daniel-nagy/md-data-table#274]
Hello, I have a situation where I want to arrive at the table and have some rows already selected, I have the array of id's I want to select but when I use it as the model for the row select the rows are not selected.

Is it possible to select some rows from default based on already existing data ?

**Comment by daniel-nagy** [comment]
Yes, the binding goes both ways so all you have to do is put the items into your selected array.

**Comment by GBora** [comment]
Ok thank you for confirming my suspicions, I guess there's some amateur mistake I made in setting up the directives, I'll close this now.

**Comment by JorgeSegtowich** [comment]
u have exemple?
