### ISSUE TITLE
md-label is invisible

### ISSUE THREAD

**Issue by KalpanaAr** [daniel-nagy/md-data-table#275]
md-label appears invisible. However, when I select content around page and limit display, I am able to see the text.

Controller code:
  <md-table-pagination md-label="{page: 'Página:', rowsPerPage: 'Filas por página:', of: 'de'}" ng-if="!noRecords" md-limit="query.limit"
                         md-page="query.page" md-total="{{drbCollection.length}}"
                         md-page-select="options.pageSelector" md-boundary-links="options.boundaryLinks">

Page view with invisible labels

![invisible](https://cloud.githubusercontent.com/assets/8092075/12790593/a57b773e-ca68-11e5-86eb-ee0a019bb899.PNG)

Labels visible once selected

![visible](https://cloud.githubusercontent.com/assets/8092075/12791857/99b066a2-ca6e-11e5-8e55-418277e04eac.PNG)

Can someone help me fix this issue? Thanks!

**Comment by daniel-nagy** [comment]
It looks like your labels are white, the same color as the background (not invisible). Check that you don't have any CSS overriding the color of the labels.

**Comment by VivienZo** [comment]
As daniel-nagy said, it's probably due to the CSS color property of the labels. You can change it with:
`
md-table-pagination span.label {
    color: #757575;
}
`

**Comment by KalpanaAr** [comment]
Thanks @VivienZo ! I was able to change the label's color.
