### ISSUE TITLE
Little correction in the demo CodePen

### ISSUE THREAD

**Issue by VivienZo** [daniel-nagy/md-data-table#287]
Hi!

In the CodePen [http://codepen.io/anon/pen/YwGJVr](http://codepen.io/anon/pen/YwGJVr) at lines 74 and 79 of the HTML, the `<td md-cell>` tags are closed with `</md-cell>` instead of `</td>`.

**Comment by daniel-nagy** [comment]
Indeed they are. Fixing now.
