### ISSUE TITLE
Undesirable position of md-tooltip inside md-cell

### ISSUE THREAD

**Issue by anthonymjones** [daniel-nagy/md-data-table#289]
I am using an md-tooltip inside some md-cells in a column that has the md-numeric attribute. When I hover over the cell, the tooltip comes up below and to the left. 

I know I can set the md-direction to 'top', 'bottom', 'left' or 'right', with the default being 'bottom', and I'd be fine with it being directly below or setting it to 'left', but the width of the md-numeric column pushes the tooltip too far to the left.

Any idea for solving this?

**Comment by vgavro** [comment]
wrap both content and tooltip to span, this will fix your issue. The problem is that they way md-tooltip works is annoying.

**Comment by anthonymjones** [comment]
Thanks for the reply @vgavro, I actually abandoned this module and angular-material for materialize. I've been very happy with that decision.
