### ISSUE TITLE
How to get "right" sorting behaviour

### ISSUE THREAD

**Issue by juriw** [daniel-nagy/md-data-table#290]
Hi

I have some problems with my sorting. It like it sort in "catalog style" so every item that starts with 1 is before 2. Eg. 1,10,13,113,132421 are all before 2.

I would like that is just sorted from lower to higher.

Here is my table
`  <md-table-container>
            <table md-table md-row-select="options.rowSelection" ng-model="selected" md-progress="promise">
                <thead md-head md-order="query.order" md-on-reorder="logOrder">
                <tr md-row>
                    <th md-column md-order-by="name">Gastype</th>
                    <th md-column md-numeric md-order-by="code" md-desc>Kode</th>
                </tr>
                </thead>
                <tbody md-body>
                <tr md-row md-select="gastype" md-on-select="logItem" md-auto-select="options.autoSelect"
                    ng-disabled="selected[0].id != undefined && gastype.id != selected[0].id"
                    ng-repeat="gastype in gastypes | filter: query.filter | orderBy: query.order | limitTo: query.limit : (query.page -1) * query.limit">
                    <td md-cell>{{gastype.name}}</td>
                    <td md-cell>{{gastype.code}}</td>
                </tr>
                </tbody>
            </table>
        </md-table-container>`

Here is my order setting from the ctrl.
`  $scope.query = {
        order: 'code',
        limit: 10,
        page: 1
    };`

Result in the UI is like this
![localhost_admin_index_html__gastypes](https://cloud.githubusercontent.com/assets/7030932/12973295/8eb02862-d0ab-11e5-8d9e-b52ea5ed1d4c.png)

**Comment by daniel-nagy** [comment]
I'm about 90% confident your numbers are stored as strings and that they are being sorted alphabetically. Storing them as numbers should fix this.

You can also pass a function to the [orderBy](https://docs.angularjs.org/api/ng/filter/orderBy) filter.

**Comment by juriw** [comment]
@daniel-nagy is `md-numeric` in `<th md-column md-numeric md-order-by="code" md-desc>Kode</th>` not covering that?

**Comment by daniel-nagy** [comment]
All the `md-numeric` attribute does is right align all the cells in the column.

**Comment by juriw** [comment]
Okay, I had noticed that, but I thought it also sorted. I will try to see if they are strings. Thanks for now.

**Comment by juriw** [comment]
@daniel-nagy you where 100% right! ;) 
I had same problem as this post: http://stackoverflow.com/a/19175678/944670
