### ISSUE TITLE
$scope is missing

### ISSUE THREAD

**Issue by ganySA** [daniel-nagy/md-data-table#293]
Hi

Any reason why i would have $scope missing within methods (onPaginate, onReorder) all i seem to have is the md-data-table object without any scope variables...

originally i thought this might have something to do with controller as syntax but i updated the codepen and that does not seem to be the issue..

**Comment by daniel-nagy** [comment]
Are you injecting `$scope` into your controller? Also, if you are using `controller as` why are you putting variables on the `$scope` instead of on your controller?

**Comment by ganySA** [comment]
Hi Daniel

Yes. I have updated your code pen. 

[http://codepen.io/anon/pen/xZMvPB?editors=1010](url)

1) Select pagination page selector checkbox.
2) Change to page 2
3) Open console which prints "this" - this is no longer the VM object where the scope is but it is an internal object of the md-data-table. There is also no $scope, $parent or any other means to navigate back to the VM controller....

This prevents me from being able to run a function vm.RefreshData() etc. to update data.....

BTW thanks for making such an great control - angular material should include this in their base.

**Comment by daniel-nagy** [comment]
This is because `logPagination` is called within the context of the pagination controller. To fix this use the `bind` [method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind).

```javascript
vm.logPagination = function (page, limit) {
    console.log(this);
    console.log('page: ', page);
    console.log('limit: ', limit);
}.bind(vm);
```

Updated [Codepen](http://codepen.io/anon/pen/adXeQr?editors=1010).

**Comment by ganySA** [comment]
Hi Daniel

Sorry i changed my comment as i realised this was happening. 
My challenge is i am using typescript and i dont have a VM object :/

Hence the concept of (this) refers to the class which is lost as this is now bound to the pagination controller.

**Comment by daniel-nagy** [comment]
> Have you by any chanced used a typescript controller with this?

Yes, and personally, I believe using ES6 style classes with Angular v1.x.x controllers is a nightmare. I would only use ES6 classes for services and use the old convention for controllers or define your controller functions within the class constructor where you can bind to `this` or create an alias.

**Comment by ganySA** [comment]
Hi Daniel - 

The answer is to declare the function using the following syntax which forces it to use the same a bind(vm).

public logPagination = (page, limit) => {

}

Anyone who would like to read more: 
https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript

Thanks a lot for your help and for building such a great control!

**Comment by mervynyang** [comment]
You can try like this:
`constructor() {
  this.log = this.log.bind(this);
}

log() {
}
`
