### ISSUE TITLE
405 error

### ISSUE THREAD

**Issue by Kratos-SA** [daniel-nagy/md-data-table#295]
I am running the code and my URL keep getting forced to do an OPTIONS request instead of a get.

I am not sure why this is happening please help

**Comment by fluffy88** [comment]
The OPTIONS request is sent before the actual request when your doing a
CORS request, Cross origin request.  You need to configure your server to
allow CORS.  This site should help you very it setup,
http://enable-cors.org/

**Comment by Kratos-SA** [comment]
thank you it is all working now.

On 18 February 2016 at 12:24, Seán Dunne <notifications@github.com> wrote:

> The OPTIONS request is sent before the actual request when your doing a
> CORS request, Cross origin request. You need to configure your server to
> allow CORS. This site should help you very it setup,
> http://enable-cors.org/
> On 18 Feb 2016 8:18 am, "Ross Rawlins" <notifications@github.com> wrote:
>
> > I am running the code and my URL keep getting forced to do an OPTIONS
> > request instead of a get.
> >
> > I am not sure why this is happening please help
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/daniel-nagy/md-data-table/issues/295>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daniel-nagy/md-data-table/issues/295#issuecomment-185642289>
> .
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.
