### ISSUE TITLE
My server is different order option

### ISSUE THREAD

**Issue by marcoriesco** [daniel-nagy/md-data-table#296]
Follow the project from the beginning, congratulations!

I have written a server in nodejs and mongodb native driver, and the table sort option works differently than on my server.

Could you send me the server code used in the example? Or send me a link where you relied to write it.

**Comment by daniel-nagy** [comment]
The source code for the server is available in the [nutrition-app](https://github.com/daniel-nagy/nutrition-app) repo. I used Node.js and MongoDB so should it should be helpful. I also used [Mongoose](http://mongoosejs.com) but that was just to enforce a schema as MongoDB does not enforce a schema.

**Comment by marcoriesco** [comment]
Faster response, very thanks!

**Comment by daniel-nagy** [comment]
:+1:
