### ISSUE TITLE
Paginating Through Server-Side Data

### ISSUE THREAD

**Issue by Adam-Michalski** [daniel-nagy/md-data-table#298]
I have query like: 
```
        vm.query = {
            order: "name",
            limit: 5,
            page: 1
        };
```
item methods for test like :
```

        function onPaginationChange(page, limit) {
            vm.query.offset = page * limit - limit;// element to start select from
            vm.query.limit = limit;
            getItems();
        }

        function successCallbackItems(response) {
            vm.items = response.data.responseData;
            vm.items.count = 7;
        }

        function getItems() {
            testService.getItems(vm.query).then(successCallbackItems, errorCallbackItems);
        }
```
On first page i have first 5 elements
I have 7 items in my database table. First page display first 5 elements. When I change page to 2 my query = { page: 2, limit 5, offset: 5} and i receive next 2 elements out of 7 but it is not displayed in md-data-table. Two elements blink when i return to previous page, then first 5 elements are loaded. My items are loaded correctly in my items table but md-data-table does'nt display it.

**Comment by daniel-nagy** [comment]
It sounds like you may need to force a digest when you update your items. I feel like that shouldn't be the case but you can try it to see.

```javascript
// you'll need to inject $scope into your controller
function successCallbackItems(response) {
 $scope.$applyAsync(function () {  
    vm.items = response.data.responseData;
    vm.items.count = 7;
  });
}
```

**Comment by Adam-Michalski** [comment]
This does'nt help. My table had proper values after pagination so I loked inside code where table items are displayed and found cause:
`(table.query.page -1) * table.query.limit` in items table filter, I copy/paste it from your example but it won't work for me.

**Comment by preraksola** [comment]
@Adam-Michalski Did you manage to solve this? If yes could you please let me know?
I am facing the same issue.

**Comment by preraksola** [comment]
Found the answer in #415 !
