### ISSUE TITLE
Pagination and icons templates don't render

### ISSUE THREAD

**Issue by eduardmartinez** [daniel-nagy/md-data-table#305]
Hi. First at all I want to thank you for the effort you have made with this project.

I installed the package as it's suggested in docs and I can use data-table but I can't see the arrows to order it in the header columns. Also, when I add 'md-table-pagination' directive to my code, it is not able to render the template. I checked Network tab in Chrome and I found 'md-data-pagination.html' is '302 found' and this happens with arrow.svg too.

![captura de pantalla de 2016-03-01 17 01 29](https://cloud.githubusercontent.com/assets/7151259/13443499/4c6c67e4-dfcf-11e5-89ba-d03c9765cc97.png)

I just realized the package is setting templates with $templateCache, but this shouldn't be a problem because I did what it's suggested in docs in this plunker ( http://plnkr.co/edit/RStSwDLXAZCZv5Z5Ghch?p=preview ) and everything works fine.

What could be the problem? What am I doing wrong?

Thanks in advance.

**Comment by eduardmartinez** [comment]
Any ideas?

**Comment by eduardmartinez** [comment]
Well, I could solve my problem. I realized the templates were saved into $templateCache using relative without domain and they were requested with domain, so I had to store them again with domain as prefix. Thanks anyway for your help.

**Comment by nathanielrich** [comment]
@eduardmartinez i've got exactly the same problem how do you solve it?
