### ISSUE TITLE
ToggleAll checkbox bug in md-table when i have ng-disabled md-row

### ISSUE THREAD

**Issue by prostoandrei** [daniel-nagy/md-data-table#307]
ToggleAll checkbox always looks like unchecked. Even if i click on it many times.

    <md-table-container>
      <table md-table md-row-select ng-model="codes.helper.selected" md-progress="codes.helper.deferred">
        <thead md-head md-order="codes.helper.query.order" md-on-reorder="codes.helper.onChange">
          <tr md-row>
            <th md-column md-order-by="code" ng-bind="'CATALOG_TYPE_LICENSECODE'|translate">  </th>
            <th md-column md-order-by="activationTime" ng-bind="'STATUS'|translate"></th>
          </tr>
        </thead>
        <tbody md-body>
          <tr md-row ng-disabled="l.activationTime !== null"  md-select="l"
          ng-repeat="l in codes.helper.list track by l.id">
            <td md-cell ng-bind="l.code"></td>
            <td md-cell>
              <span ng-if="l.activationTime !== null" translate="STATUS_ACTIVATED"></span>
              <span ng-if="l.activationTime === null" translate="STATUS_NOT_ACTIVATED"></span>
            </td>
          </tr>
        </tbody>
      </table>
    </md-table-container>

It would be great If i can do something like...

    md-row-select="activationTime === null"

to say what i wanna check

**Comment by bhamon** [comment]
+1 for your reported issue: when there is a disabled row in the table the toggleAll checkbox looks unchecked, thus preventing the uncheckAll feature.

Regarding your suggestion, looking at the doc it's already implemented: https://github.com/daniel-nagy/md-data-table#row-selection. I tested it against the last version and seems to work well.

**Comment by prostoandrei** [comment]
All fixed. Thank's!
