### ISSUE TITLE
md-page loads blank, data isn't binding.

### ISSUE THREAD

**Issue by Derekjohnson277** [daniel-nagy/md-data-table#313]
Here is my ng-repeat

`<tr md-row ng-repeat="link in links | orderBy: query.order | limitTo: query.limit: (query.page - 1) * query.limit">`

The pagination div

`<md-table-pagination md-limit="query.limit" md-page="query.page" md-total="{{count}}" md-page-select></md-table-pagination>`

Data from controller:

`	$scope.count = data.length;
  		$scope.query = {
  			order: 'LinkURL',
  			limit: 10,
			page: 1
  		};`
 Everything renders fine except for the page number, it loads blank but I can still open the select menu and select a page to view. Could you help me figure out why it's doing this?

**Comment by daniel-nagy** [comment]
Hmm... Any chance you could reproduce this in a [Codepen](http://codepen.io/anon/pen/BjvLVJ?editors=1010) so I can take a look?

**Comment by Derekjohnson277** [comment]
I tried reproducing it in Codepen with some static data and everything worked fine... I'm getting my data through an AJAX call so maybe that is causing it, but I don't see why. Do you have any ideas, here's the CodePen with the exact same code just static data, not dynamic. 

http://codepen.io/Derekjohnson277/pen/ZWOOpZ?editors=1010

**Comment by Derekjohnson277** [comment]
Alright I figured it out, I had to put the $scope.query options outside of the ajax call in the controller and it worked just fine!
