### ISSUE TITLE
progress bar not hide when promise has been reject

### ISSUE THREAD

**Issue by zack24q** [daniel-nagy/md-data-table#316]
Hi
I modified demo code to reproduce this behavior.Please see this example http://codepen.io/anon/pen/WwxXLL?editors=1010.
Is this default behavior or bug? I think when table's promise getting rejected, the progress bar should be hidden automatic and the programmer can prompt user what happened.

**Comment by zack24q** [comment]
seems modify this [function](https://github.com/daniel-nagy/md-data-table/blob/master/src/scripts/mdTable.js#L75) can fix this problem if it is a bug.

**Comment by daniel-nagy** [comment]
I believe you are right, I think I need to change line [80](https://github.com/daniel-nagy/md-data-table/blob/master/src/scripts/mdTable.js#L80) to

```javascript
queue[0].finally(function () {
  queue.shift();
  resolvePromises();
});
```

**Comment by daniel-nagy** [comment]
Should be fixed now.

**Comment by zack24q** [comment]
Thanks!
