### ISSUE TITLE
mdOptions not working

### ISSUE THREAD

**Issue by nbartley** [daniel-nagy/md-data-table#320]
I've set mdOptions	and md-options in the pagination area with both a manually made array, and a variable.

Currently it is not allowing an override of the standard 5,10,15 paging. 

Can we have an example in the code pen specifying the 5-10-15 setting with the ability to modify it?

**Comment by daniel-nagy** [comment]
```html
md-options="[10, 50, 100]"
```

[Codepen](http://codepen.io/anon/pen/wGzpbV?editors=1010)

**Comment by nbartley** [comment]
I appreciate the demonstration. 

Coulda swore I did exactly that, but now it works. Cheers.
