### ISSUE TITLE
orderBy: notarray issue with angular 1.5 components

### ISSUE THREAD

**Issue by f1tech** [daniel-nagy/md-data-table#323]
I'm plugging an instance of md-data-table into a page I'm creating using the new component feature in angular 1.5. I'm basically doing everything exactly the same as I did with regular template views previously. When my page renders I receive several errors that read orderyBy: notarray which gets linked to this page: https://docs.angularjs.org/error/orderBy/notarray?p0=%7B%22$$state%22:%7B%22status%22:0%7D%7D

My data table has md-order="ftpUsers.gridOptions.order" md-on-reorder="ftpUsers.sortGrid" on its thead. 

My controller initializes the gridOptions property like this:
```
var ctrl = this;
ctrl.gridOptions = { order: 'MSTRSAPID' };
```

sortGrid looks like this:
```
        function sortGrid(order) {
            ctrl.gridOptions.order = order;
            setLocation();
        };

        function setLocation() {
            // $location.search({ key: ctrl.gridOptions.order, id: ctrl.ftpUserId })
            $location.search({ key: ctrl.gridOptions.order })
        };
```

There's really nothing different from this instance of <md-data-table> other than the use of component. 

Any ideas?

**Comment by daniel-nagy** [comment]
I'm guessing it is complaining about the `orderBy` property of your `ng-repeat` statement. You haven't shown me you `ng-repeat` statement so I don't know whats going on., but I'm also guessing you're attempting to sort the items on the server so you shouldn't have an `orderBy` property in your `ng-repeat` statement.

**Comment by f1tech** [comment]
I don't think so. My ng-repeat looks like this: 
''' ng-repeat="customer in ftpUsers.customerList | orderBy: ftpUsers.gridOptions.order" 

which is basically the same thing I do elsewhere.

**Comment by daniel-nagy** [comment]
What are you doing with `$location.search({ key: ctrl.gridOptions.order })`? Also, you don't need the line `ctrl.gridOptions.order = order;`. The module will update this property for you, it just won't happen till the next digest cycle unfortunately.

**Comment by f1tech** [comment]
I'm not currently doing anything with the $location.search code, but in other controllers I use this to restore the sort order when I return to the view and will eventually do this here as well.

**Comment by f1tech** [comment]
Well, at any rate, this appears to be an issue with ng-repeat itself, not md-data-table. If I eliminate md-data-table and all of the calls to it, I still get the same error. I'm still stumped, because there's nothing different in this particular ng-repeat that I can see to other places I use it, but it doesn't appear to be your issue at all.

**Comment by daniel-nagy** [comment]
It looks like you are somehow passing a promise the the `orderBy` property.

```javascript
{"$$state":{"status":0}} // <- this resembles an Angular promise object
```

Are you executing any asynchronous code that may return promise for `ftpUsers.gridOptions.order`?

**Comment by f1tech** [comment]
Hit me up next time you're in the 419 - I owe you many beers!

**Comment by daniel-nagy** [comment]
lol, did you get it to work?

**Comment by f1tech** [comment]
Yeah. I'm more or less following John Papa's style guide and started implementing returning promises from my activate function in my controllers. Although I do that elsewhere and don't have this issue, eliminating that solved it in this instance.
