### ISSUE TITLE
Toggle sort direction default via directive in <th>

### ISSUE THREAD

**Issue by twrk** [daniel-nagy/md-data-table#33]
Feature request - would be nice to specify the default sort direction for a column via a directive in the `<th>`, as an example (note the **`order-direction`** attr):

    <md-data-table-container>
          <table md-data-table md-row-select="tableConfig.selected">
              <thead md-trim-column-names md-order="tableConfig.order">
                  <tr>
                      <th order-by="name">Report Name</th>
                      <th numeric order-by="views.value" order-direction="descending">Visits</th>
                      <th numeric order-by="users.value" order-direction="ascending">Unique Users</th>
                  </tr>
              </thead>
              <tbody md-auto-select>
                  <tr ng-repeat="report in reports_data | orderBy: tableConfig.order">
                      <td>{{report.name}}</td>
                      <td>{{report.views.value}}</td>
                      <td>{{report.users.value}}</td>
                  </tr>
              </tbody>
          </table>
      </md-data-table-container>

**Comment by daniel-nagy** [comment]
I can see why this would be desirable. Are you thinking the attribute should restrict the direction to only sort descending or ascending, or just the default direction? `order-direction` makes it seem like it can only sort in that direction.

**Comment by twrk** [comment]
Thanks for the prompt response. Yeah, in my experience the user usually wants to see text columns alphabetically (so default ascending works well) and numeric columns from highest to lowest (or biggest to smallest). And to clarify, it would be the default sort direction, but the user could still toggle between either state. So `order-direction` is not a great name - perhaps `order-default-direction` or the like?

**Comment by daniel-nagy** [comment]
Okay, `order-default-direction` is a little verbose. We can probably think of something sorter that makes sense. I've been thinking of shortening some of the other attributes as well. For example, `md-data-table-*` would become `md-table-*`; `md-data-table-pagination` could just be `md-pagination`. I guess that is a personal preference but I think most people would prefer shorter attribute names. I'd end up breaking everyone's tables tough :stuck_out_tongue:
