### ISSUE TITLE
Clicking on a button in a row selects row

### ISSUE THREAD

**Issue by Sarpedion** [daniel-nagy/md-data-table#338]
Greetings,

if I add a button in a datatable row while auto-selection is active, clicking on a button will select a row.
I'd guess this is not exactly a wanted behaviour for any CRUD-ish GUI, and datatables often come with CRUD.
Is there any workaround for this?

Here is a quick example, just to clarify on what I meant:
http://codepen.io/Sarpedion/pen/ZWyVYJ?editors=1010

**Comment by daniel-nagy** [comment]
You just need to stop the event from propagating. I updated you [Codepen](http://codepen.io/anon/pen/GZEzMv?editors=1010)

**Comment by Sarpedion** [comment]
That is indeed the solution, thank you
