### ISSUE TITLE
Strange issue with multiple attribute and checkAll

### ISSUE THREAD

**Issue by prostoandrei** [daniel-nagy/md-data-table#339]
I'm put multiple attribute in md-table, but checkAll checkbox isn't appearing.
But the ability to select more than one check box appears.

What can be wrong?

I have code like this. 

    <md-table-container>
        <table md-table md-row-select multiple ng-model="codes.helper.selected" md-progress="codes.helper.deferred">
        <thead md-head md-order="codes.helper.query.order" md-on-reorder="codes.helper.onChange">
        <tr md-row>
          <th md-column md-order-by="code" ng-bind="'CATALOG_TYPE_LICENSECODE'|translate"></th>
          <th md-column md-order-by="activationTime" ng-bind="'STATUS'|translate"></th>
          <th md-column md-order-by="activationTime" ng-bind="'CATALOG_LICENSECODE_ACTIVATION_DATE'|translate"></th>
          <th md-column md-order-by="activationAccount.name" ng-bind="'CATALOG_LICENSECODE_ACTIVATED_BY'|translate"></th>
        </tr>
        </thead>
        <tbody md-body>
          <tr md-row
          md-select="l"
          md-select-id="l.id"
          ng-repeat="l in codes.helper.list track by l.id"
          ng-disabled="l.activationTime">
            <td md-cell ng-bind="l.code"></td>
            <td md-cell>
              <span ng-if="l.activationTime" translate="STATUS_ACTIVATED"></span>
              <span ng-if="!l.activationTime" translate="STATUS_NOT_ACTIVATED"></span>
            </td>
            <td md-cell>
              <span ng-if="!l.activationTime">-</span>
              <span ng-if="l.activationTime" ng-bind="l.activationTime|date:'dd.MM.yyyy HH:mm'"></span>
            </td>
            <td md-cell>
              <span ng-if="!l.activationAccount.name">-</span>
              <span ng-if="l.activationAccount.name" ng-bind="l.activationAccount.name"></span>
            </td>
          </tr>
        </tbody>
      </table>
    </md-table-container>
    <md-table-pagination md-label="codes.helper.label"
                         md-limit="codes.helper.pagination.limit" md-page="codes.helper.pagination.page"
                         md-total="{{codes.helper.pagination.total}}" md-on-paginate="codes.helper.onPaginate"
                         md-limit-options="codes.helper.paginationOptions">
    </md-table-pagination>

**Comment by daniel-nagy** [comment]
One error I do see is your `md-select-id` attribute should just be `md-select-id="id"` not `md-select-id="l.id"`. I don't think this is the cause of the issue and I don't see anything else wrong with your markup.

If you open the developer tools and look at your table's header do you see this as the first child element?

```html
<th class="md-column md-checkbox-column"></th>
```

While your in the developer tools, if you can get to the source code, put break points on lines `714` and `718` (should be inside the `addCheckboxColumn()` and `attatchCheckbox()` methods respectively). And let me know if you successfully get into both methods.

**Comment by prostoandrei** [comment]
Sorry, there was a problem with my app. Crazy cache :)

Thank's for md-select-id :+1:

**Comment by prostoandrei** [comment]
Unfortunately forced to reopen the issue.
Bug [screenshot](http://joxi.ru/MAjl0d7fvX1PZm)
This is not the cache. This happens often enough.
Here is a [screenshot](http://joxi.ru/n2Y58LRSjd7zQ2) of devTools with data.
`addCheckboxColumn` ' isn't called on `794` line
It's happening in mdDialog's.
On second mdDialog initialization, checkAll appears.

**Comment by daniel-nagy** [comment]
Can you update to `v0.10.2` and tell me if that resolves this issue?

**Comment by prostoandrei** [comment]
Yep, it's resolved! Nice work :)
