### ISSUE TITLE
Some error with ng-if

### ISSUE THREAD

**Issue by hinablue** [daniel-nagy/md-data-table#340]
```
<md-content ng-if="show">
  <md-table-container>
    // more code here.
  </md-table-container>
</md-content>
```

If switch the `show` from `true` to `false` and switch back. There are some `$watch` issue.

https://github.com/daniel-nagy/md-data-table/blob/master/dist/md-data-table.js#L791
https://github.com/daniel-nagy/md-data-table/blob/master/dist/md-data-table.js#L1250

There are two `$watch` get error `Watchers fired in the last 5 iterations` if the element use `ng-if`.

And `md-limit-options` in `md-table-pagination` directive also get the same error, but I think maybe is the angular material javascript framework issue.

So, maybe make a trigger function to manual watch the `rowSelect`, `enableRowSelection` and `tableCtrl.enableMultiSelect` will be better.

**Comment by daniel-nagy** [comment]
Hmmm... I wasn't able to reproduce this error. See this [Codepen](http://codepen.io/anon/pen/RaZRwx?editors=1010). Observe that I put a show/hide toggle in the table toolbar.

**Comment by hinablue** [comment]
I used the ngRoute with complex directives I wrote, I am trying to figure it out and make it simple to reproduce the error.

If I can make it happen, I will let you known. Thanks for your quickly response :-)

**Comment by daniel-nagy** [comment]
Okay, I had a feeling something else was going on. If you manage to reproduce it I'll take a look.

**Comment by hinablue** [comment]
I found this is about `$rootScopeProvider.digestTtl`, if TTL less than 5, `ngRoute` will failed. So all the directives or modules will failed with this error `Watchers fired in the last 5 iterations`.

This is my fault, I'm sorry to bother you this issue. Have nice day :-)
