### ISSUE TITLE
md-order not being recognized  - help please

### ISSUE THREAD

**Issue by toberyn** [daniel-nagy/md-data-table#341]
Hi, first of all thanks for this great contribution to the angular community.

I am having problems trying to make the md-order works, I think it is not being recognized by the directive. I am doing this in the template: 

`<thead md-head md-order="vm.query.order">`

and in the controller: 

`vm.query = {
            order: '-taskName',
            limit: 5,
            page: 1
        };`

I tried to implement the example you have in documentation but the order didn't work neither so I am thinking that maybe I am missing something.

Here you can find the code http://plnkr.co/edit/wO0gVUcSkP3ti0U8WTlz

Thanks.

**Comment by daniel-nagy** [comment]
It looks like you are not using `vm.query.order` in your `ng-repeat` expression.

```html
<tr md-row ng-repeat="task in vm.tasks | filter: vm.filterByStatus(criteria) | orderBy: vm.query.order">
```

**Comment by toberyn** [comment]
@daniel-nagy wow amazing, thank you very much, i guess i am one of the many that owe you a beer.
Cheers!
