### ISSUE TITLE
select all check box is not coming for the second table in the same page.. 

### ISSUE THREAD

**Issue by fkmnawaz** [daniel-nagy/md-data-table#342]
In the same html page I have two tables. For the first table everything is fine but for the second table the select all check box is not coming although I am able to select rows and do multi selection also..  and one more thing the column headers are shifting one place left as the selectall checkbox is not there 

Here is the pen for this problem ..  http://codepen.io/fnawaz/pen/EKvwRY

**Comment by daniel-nagy** [comment]
Should be fixed in `v0.10.2`

**Comment by fkmnawaz** [comment]
awesome . .solved . . super. .. thanks
