### ISSUE TITLE
Row selection: ngModel is not defined.

### ISSUE THREAD

**Issue by ameer157** [daniel-nagy/md-data-table#343]
Throws an error in the console even though I have an ng-model defined:

`<table md-table md-row-select multiple ng-model="selected" md-progress="promise">`

**Comment by khanhdd123** [comment]
Same my problem.Please give me a reson.

**Comment by daniel-nagy** [comment]
What is the error?

**Comment by khanhdd123** [comment]
I can not display select,it show ngModel is undefine?

Vào 20:58 T.5, 31 Th3 2016 Daniel Nagy <notifications@github.com> viết:

**Comment by khanhdd123** [comment]
When I press F12,it show error like this 
Row selection: ngModel is not defined

**Comment by khanhdd123** [comment]
How to show select checkbox??? I tried but not working

**Comment by daniel-nagy** [comment]
In you controller you need to define the model, so if you have

```html
<table md-table md-row-select multiple ng-model="selected" md-progress="promise">
```

In you controller you will need to define `selected`.

```javascript
$scope.selected = [];
```

**Comment by khanhdd123** [comment]
Why?? I am working with angular-formly,it seem like bad solution for angular-formly

**Comment by khanhdd123** [comment]
I don't know why it not working??I tried define selected but it not resolve my problem

**Comment by daniel-nagy** [comment]
> Why?? I am working with angular-formly,it seem like bad solution for angular-firmly

Otherwise two-way data binding will not work, i.e. you will not be able to access the selected items from your controller.

> I don't know why it not working??I tried define selected but it not resolve my problem

You're either going to need to reproduce the error in a Codepen or provide more information for me to help.

**Comment by khanhdd123** [comment]
OK,i will show you soon

**Comment by khanhdd123** [comment]
Wait me 1 hour

**Comment by khanhdd123** [comment]
Now you can see
http://codepen.io/duykhanhbkk57/pen/xVLvPz

**Comment by daniel-nagy** [comment]
@khanhdd123 because you're using formly, you will need to define any variables you want the table to see in the scope of formly. I've updated you [Codepen](http://codepen.io/anon/pen/jqLgXm)

**Comment by khanhdd123** [comment]
Can you explain for me??What is I need to define??

**Comment by khanhdd123** [comment]
How do I use key in angular formly as ng-model like this : ng-model="model[options.key]"

**Comment by jitendrathakur** [comment]
I got same error Row selection: ngModel is not defined. Using angular1.5

**Comment by tanfeiqi** [comment]
Me, too. Using angular 1.4.7

**Comment by ganeshghalame** [comment]
Same error Row selection: ngModel is not defined. Using angular 1.5 and Angular material 1.1.0

**Comment by Calrain** [comment]
I had this problem as well but the solution was to initialize the ng-model variable to an empty array.

As @daniel-nagy said, in your controller you have to define the ng-model variable:
`$scope.selected = [];`

If you are using a variable such as `vm.selectedRow` then in your controller you will need:
`vm.selectedRow = [];`.

If you only define `vm.selectedRow;` in the controller and don't make it an empty array, it will give you the `Row selection: ngModel is not defined` error.

**Comment by manumohant** [comment]
I also have the same issue. Everything was fine and table was displaying correctly. I inculded "ui.router" instead of ngRoute and there after it starts showing the above error. Any idea???
