### ISSUE TITLE
[Feature] Row drag and drop (reordering)?

### ISSUE THREAD

**Issue by nicolae-olariu** [daniel-nagy/md-data-table#344]
Hi,

Is there any way we could easily integrate a plugin or "make" the md-table offering access to row reordering? Any ideas?

Thanks!

**Comment by daniel-nagy** [comment]
I've actually already written a directive that does this. I'll see if I can get permission to release it.

**Comment by nicolae-olariu** [comment]
Thanks for your quick response!

**Comment by bokzor** [comment]
So, Do you have permission ? :-)

**Comment by daniel-nagy** [comment]
I've been given the green light. I might put it up this weekend.

**Comment by bokzor** [comment]
Great ! Thanks for your amazing work !

**Comment by nicolae-olariu** [comment]
Cool! Can't wait! Thanks!

**Comment by sam1360** [comment]
Any update on this??

**Comment by mattbogado** [comment]
@daniel-nagy Do you have an ETA on this? this would be very super useful for my current project.

**Comment by ChBernat** [comment]
Any update on this?

**Comment by alexcwatt** [comment]
@daniel-nagy If you need someone to generalize the code or anything, I'd be glad to take a look at it (email on profile). I have a project for which I'll need drag-and-drop with md-data-table in the next week or so, and would need to implement myself without the directive. Thanks for all your work on this project; it's awesome! :+1:

**Comment by Steingate** [comment]
Hello, any update ? :/

@daniel-nagy

**Comment by daniel-nagy** [comment]
This will be available soon https://boulevard.github.io/sortable

**Comment by Steingate** [comment]
Cool ! Have you a date for the release ?
thanks

**Comment by daniel-nagy** [comment]
This is now available. Please move the discussion to https://github.com/Boulevard/sortable.

**Comment by eniniz** [comment]
but how can sortable used with md-data-table, I try it and its works but for example if I have a table with thead 'a' and 'b' I can reorder the heads 'a' and 'b' but the data of each one doesn't follow him I get

**Comment by jackdclick** [comment]
Hi @daniel-nagy .  Love this module.  Any chance you have the source for your demo posted somewhere?  Am I not seeing it?  Thanks!
