### ISSUE TITLE
Pagination displays incorrect page number & record range when there are zero results.

### ISSUE THREAD

**Issue by Martaver** [daniel-nagy/md-data-table#345]
Here's an example CodePen (http://codepen.io/martaver/pen/xVXONL) where the pagination has zero total results, and the current page number is zero.  Pagination doesn't display the page number, and results are shown as -4 to 0 of 0.

If the current page is changed to 1 (makes sense, I suppose) then Pagination correctly displays 1 as the page number, but the results are shown as 1 to 0 of 0.

I think when either the page number or total results are zero, the Pagination should default to displaying Page: 1 and results 0 to 0 of 0.

**Comment by daniel-nagy** [comment]
The directive expects pages to start at 1. I can fix the count so it displays 0 - 0 of 0.

**Comment by Martaver** [comment]
Sounds good to me!

**Comment by daniel-nagy** [comment]
Should be fixed now 👍

**Comment by Martaver** [comment]
Thank you!
