### ISSUE TITLE
The word "Page" is sticking out

### ISSUE THREAD

**Issue by super-coder** [daniel-nagy/md-data-table#347]
from http://danielnagy.me/md-data-table/

![image](https://cloud.githubusercontent.com/assets/2155554/14229349/b0f22bea-f929-11e5-92c9-137fddbecff1.png)

![image](https://cloud.githubusercontent.com/assets/2155554/14229357/cb639464-f929-11e5-9369-ce81b5be97bc.png)

**Comment by super-coder** [comment]
first screen is iPhone5 mode in Chrome

**Comment by daniel-nagy** [comment]
pagination should be usable on mobile now
