### ISSUE TITLE
Adding new row to table

### ISSUE THREAD

**Issue by sachq** [daniel-nagy/md-data-table#349]
I've implemented md-data-table to my application sucessfully, But One issue i'm facing is _adding new row_ to the table. I've list of _candidates_ in the **$scope.candidates**

```
$scope.candidates = [
      {
        name: 'John Doe',
        experience: 3,
        current_ctc: 8,
        expected_ctc: 12,
        location: 'Bangalore'
      },
      {
        name: 'Joey Doe',
        experience: 1.5,
        current_ctc: 2.5,
        expected_ctc: 6,
        location: 'Bangalore'
      },
      {
        name: 'Frank Doe',
        experience: 2,
        current_ctc: 4,
        expected_ctc: 10,
        location: 'Guragon'
      }
    ];
```

Added **md-progress="promise"**.
I've a form which lets you add new candidates which pushes an object into the candidates array. It's not async adding it to the table.

```
$scope.addCandidate = function(obj) {
  var deferred = $q.defer();
  $scope.promise = deferred.promise;
  $scope.candidates.push(obj);
  deferred.resolve($scope.iScoreCandidates);
};
```

Adding candidate method

```
$scope.instantScoreAdd = function(candidateObj) {
  $scope.addCandidate(candidateObj);
};
```

Thank you

**Comment by daniel-nagy** [comment]
I'm guessing you're using `ng-repeat` to loop over `$scope.candidates` but I don't see where you are adding the new candidate to the `$scope.candidates` array. I see `$scope.iScoreCandidates.push(obj)` but that is not the same array.

**Comment by sachq** [comment]
That's just editing mistake. That's is `$scope.candidates`. So what should i do rather than `ng-repeat`?

**Comment by sachq** [comment]
@daniel-nagy Is there any solution for this?

**Comment by daniel-nagy** [comment]
All you have to do is push the new item onto the array. Here is a [Pen](http://codepen.io/anon/pen/PNEqWw?editors=1010), click the "Add Banana Split" button and it will add it to the table.
