### ISSUE TITLE
Pagination with dynamic data

### ISSUE THREAD

**Issue by MemoLabra** [daniel-nagy/md-data-table#35]
Hi first of all thank for this module have a nice look and feel as material design.

I have a project what involve in collect data from sensors through MQTT protocol to the server and proportionate to front end with Socket.io, i need this data to be displayed in a table and users can interact with them so this module fits perfect as data table.

the data from Socket.io are saved in a ```$scope.array``` object so in the front is called with a ```ng-repeat ```in the tbody dynamically while these data arrives from sensors.

The problem comes when table begins to fill, i know the implementation and the manipulation with the data have another approach but i want to know if i can sort the data in pages somehow or  if can be implemented this feature since md-limit is not working with this way of collecting data.

Sorry if something is not understood English is not my mother tongue.

**Comment by daniel-nagy** [comment]
Are you trying to achieve pagination on the server side or client side? As long a `$digest` is performed when new data is pushed from Socket.io to the client I believe `ng-repeat` should be able to handle that just fine.

I think the problem might be that you are not actually implementing the pagination. Simply assigning values to the attributes on the `md-data-table-pagination` directive will not enable pagination. The easiest way to do pagination is in the client using the built in pipe functionality of `ng-repeat`. For example, 

```html
<tr ng-repeat="item in array | orderBy: myOrder | filter: mySkip | limitTo: myLimit">
```

You can implement a simple skip function in your controller like so,

```javascript
$scope.mySkip = function (item, index) {
    return index >= ($scope.myLimit * ($scope.myPage - 1));
  };
```

The demo provided takes advantage of `ng-repeat` to do client-side pagination.

Your english is better than some people I know who speak it natively :)

**Comment by MemoLabra** [comment]
Thank you ! completely forget about ng-repeat filters ...sometimes just have to see bigger lol, in a complement way you can point this on documentation maybe can help people who is starting with angular like me :smiley:

**Comment by daniel-nagy** [comment]
I'm happy you got it working! I can provide this code in the documentation for pagination.
