### ISSUE TITLE
Object doesn't support property or method 'decorator'

### ISSUE THREAD

**Issue by rafaelvioleta** [daniel-nagy/md-data-table#350]
![image](https://cloud.githubusercontent.com/assets/18256473/14240105/b76cc0b0-fa74-11e5-9978-415d7d0484a4.png)

Hi, I have encountered this error after manually installing the md-data-table. I followed the installation instructions. Any help/solution regarding this issue? I am quite new at AngularJS.
Thanks!

**Comment by daniel-nagy** [comment]
What version of Angular are you using? You should be using `v1.4.0` or greater.

**Comment by rafaelvioleta** [comment]
I am using v1.3.2. If that's the case, then I can't use this module? :(

**Comment by taxpayer** [comment]
Yes, you need at least the version 1.4 to use this table component. Can't
you update your Angular version? You'll have some other benefits on doing
that besides using this excellent component. 😉
Em 05/04/2016 6:00 AM, "rafaelvioleta" <notifications@github.com> escreveu:

**Comment by daniel-nagy** [comment]
@rafaelvioleta yes, you will need to update to at least `v1.4.0`.

**Comment by rafaelvioleta** [comment]
@daniel-nagy Hi daniel-nagy, I just upgraded angular from v1.3.8 to v1.4.0.
Here is the step-by-step process that I did since our company network blocks bower from downloading the necessary files.

1. I downloaded the files(angular, angular-animate, angular-mocks) using NPM.
2. I copied the downloaded files from the 'node_modules' folder to the 'bower_components' folder and updated the bower.json with their respective versions.
3. I followed the instructions for installing the md-data-table

After doing all of this, I still get the error:
![image](https://cloud.githubusercontent.com/assets/18256473/14600732/db25bc6a-0590-11e6-9819-637f438464e4.png)

Please help me on how to properly migrate/update angular from one version to another so I can finally use md-data-table. Thanks!

**Comment by daniel-nagy** [comment]
If you open up the developer tools and look at the version of Angular loaded by the browser is it indeed `>=1.4.0` ? You should see a comment block at the top of the file like,

```javascript
/*
 AngularJS v1.4.9
 (c) 2010-2015 Google, Inc. http://angularjs.org
 License: MIT
*/
```
