### ISSUE TITLE
mdDsec in column - default sorting

### ISSUE THREAD

**Issue by ilyatrunov** [daniel-nagy/md-data-table#353]
The code is checking if md-dec is present in md-column or not, but not the value, this makes it difficult to set it in runtime (having some columns default asc, and some desc).

Possible solution:
scope.getDirection = function () {
      if(!isActive()) {
        if (attrs.mdDesc) {
          return 'md-desc';
        } else {
          return 'md-asc';
        }
      }

      return headCtrl.order === '-' + scope.orderBy ? 'md-desc' : 'md-asc';
    };

**Comment by daniel-nagy** [comment]
From what I understand you want to use an expression to enable the `md-desc` attribute?

The `getDirection` method now evaluates the the `md-desc` attribute on the scope, [mdColumn.js:87](https://github.com/daniel-nagy/md-data-table/blob/master/src/scripts/mdColumn.js#L87). This was an undocumented change in one of the recent updates.

```javascript
scope.getDirection = function () {
  if(isActive()) {
    // if we are already sorted by this column we only care what direction
    // we are currently sorted
    return headCtrl.order.charAt(0) === '-' ? 'md-desc' : 'md-asc';
  }

  // Sort descending if the mdDesc attribute is present and empty
  // or evaluates to something truthful
  return attrs.mdDesc === '' || scope.$eval(attrs.mdDesc) ? 'md-desc' : 'md-asc';
};
```

This may not work as intended though, I may have to bind to the `mdDesc` attribute instead evaluating it. Let me know if this what you were after and if it works for you.

**Comment by ilyatrunov** [comment]
this should work, thank you!
