### ISSUE TITLE
mdt-cell not able to handle complex ng-repeat

### ISSUE THREAD

**Issue by khanhdd123** [daniel-nagy/md-data-table#354]
I had a same problem : 
https://github.com/iamisti/mdDataTable/issues/79
please help me!
Thank !

**Comment by khanhdd123** [comment]
Sorry,I am wrong

**Comment by daniel-nagy** [comment]
Should this be closed?

**Comment by khanhdd123** [comment]
Yes,please answer me in angular formly issue
