### ISSUE TITLE
Bug in pagination page select

### ISSUE THREAD

**Issue by fredjrlabanda** [daniel-nagy/md-data-table#359]
There is a bug in **md-page-select** instead of showing the number of pages, it shows the dropdown list of how many records i have.

**Comment by daniel-nagy** [comment]
The pagination directive is going to use the following method to calculate the number of pages.

```javascript
self.pages = function () {
  return isPositive(self.total) ? Math.ceil(self.total / (isPositive(self.limit) ? self.limit : 1)) : 1;
};
```

The only way it would think you have the same number of pages as records is if your limit is `NaN` or less than or equal to `1`.

**Comment by daniel-nagy** [comment]
You were right, see #360.

**Comment by fredjrlabanda** [comment]
Cool, thanks @daniel-nagy

**Comment by daniel-nagy** [comment]
@fredjrlabanda were you able to get the correct version and did it solve this issue?

**Comment by fredjrlabanda** [comment]
@daniel-nagy  works perfect now, thanks a lot
