### ISSUE TITLE
npm package error

### ISSUE THREAD

**Issue by qihaiyan** [daniel-nagy/md-data-table#365]
the md-data-table.js in the package get from npm registry is error, in this line of code:
`isPositive(self.total) ? Math.ceil(self.total / (isPositive(self.limit) ? 1 : self.limit)) : 1;`
the right on should be:
`isPositive(self.total) ? Math.ceil(self.total / (isPositive(self.limit) ? self.limit : 1)) : 1;`

**Comment by daniel-nagy** [comment]
I fixed this not to long ago [mdTablePagination.js#L65](https://github.com/daniel-nagy/md-data-table/blob/master/src/scripts/mdTablePagination.js#L65) but I overwrote the last tag so I think npm's cache is stale. Let me just go ahead and release another version.

**Comment by daniel-nagy** [comment]
Okay I just published `v0.10.5` to npm.

**Comment by qihaiyan** [comment]
it's ok now,thanks.
