### ISSUE TITLE
md-order-by expression change inserts duplicates sort arrows and breaks functionality

### ISSUE THREAD

**Issue by ilovett** [daniel-nagy/md-data-table#373]
```
      <table md-table>
        <thead md-head md-order="ctrl.query.order">
          <tr md-row>
            <th md-column md-numeric md-order-by="collection[{{ key }}].{{ mySelectedDynamicProperty }}" ng-repeat="(key, col) in ctrl.data[0].collection">Title</th>
          </tr>
        </thead>
```

when `mySelectedDynamicProperty` changes a duplicate arrow is inserted in the TH, and loses clicking functionality

**Comment by ilovett** [comment]
nevermind it was something else in my code

**Comment by ilovett** [comment]
Seems to insert duplicate sort arrow but resets to working state if the data collection changes

**Comment by daniel-nagy** [comment]
Would you mind putting a demo together so I can take a look at it?

**Comment by ilovett** [comment]
http://codepen.io/ilovett/pen/BKVpeK

![image](https://cloud.githubusercontent.com/assets/1776100/14648947/a58003e8-0619-11e6-807f-03974a74a297.png)

Change the select in the top left, then hover on the column header

**Comment by daniel-nagy** [comment]
Okay this should be fixed now.

**Comment by ilovett** [comment]
Awesome dude thanks for the quick fix!
