### ISSUE TITLE
rows per page disappeared after upgraded from 0.9.12

### ISSUE THREAD

**Issue by lolaswift** [daniel-nagy/md-data-table#383]
Tried 0.10.5, 0.10.7 and 0.10.9. Same issue. Any idea?

**Comment by daniel-nagy** [comment]
You need to opt into displaying the rows per page now. You do this by passing an array to the `md-limit-options` attribute.

```html
<md-table-pagination md-limit-options="[5, 10, 15]"></md-table-pagination>
```

**Comment by lolaswift** [comment]
Thanks Daniel. That works!

**Comment by daniel-nagy** [comment]
No problem!
