### ISSUE TITLE
not responsive

### ISSUE THREAD

**Issue by razzbee** [daniel-nagy/md-data-table#40]
I tried using it in my project , it works fine, but its not responsive, I dont know if I am missing out something??

**Comment by daniel-nagy** [comment]
What exactly do you mean by not responsive? Is there something specific you see in the demo that you cannot replicate in your project?

**Comment by razzbee** [comment]
The table doesnt resize in mobile view,the demo works fine, I dont know about mine.

**Comment by daniel-nagy** [comment]
hmm... The table is going to have a natural width based on the largest cell in each column. The table will not shrink beyond this natural width and will scroll horizontally on smaller screens.

If this doesn't describe what your'e experiencing, it may be a problem with the general layout of your application. If your not familiar with how flexbox works it can be tricky to achieve your desired layout.

**Comment by razzbee** [comment]
Thank You very much , since I am pretty new to angular and material angular ,I guess that might be the problem. I will check my layout again and give you feedback

**Comment by razzbee** [comment]
I think the the problem is not from my layout but from the module. This is how the error can be reproduced. If you wrap your app in a div with layout row or body with layout = 'row' then data-table which is needed by md-sidenav then the problem is caused

**Comment by razzbee** [comment]
I have been able to fix it by adding conditional layouts : 
 <div layout="column" layout-gt-md="row">
<md-sidenav>
</md-sidenav>

.....
</div>

I lock the sidenav at  layout-gt-md , so I have to set it to row to align the sidenav and the main content side by side , else the default layout should be column.
Thank You so much.
