### ISSUE TITLE
Allow binding of 'this' to the onReorder callback

### ISSUE THREAD

**Issue by AnimaMundi** [daniel-nagy/md-data-table#404]
I would like to be able to bind my controller to `this` in the `onReorder` callback.
At the moment I'm using TypeScript and all my controllers are classes,
I pass the callback as `transactionsCtrl.onReorder` into the `onReorder` attribute and then try to  reference a variable that is bound to the controller inside that callback, but naturally it is undefined due to the execution context.

**Comment by daniel-nagy** [comment]
I believe Typescript allows you to bind to the lexical `this` using the arrow syntax. I'm not too familiar with Typescript but I believe the syntax is along the lines of

```javascript
class MyClass {
   public myMethod = () => {
     // do something with this
   }
}
```

**Comment by AnimaMundi** [comment]
Yeah you're right,
I also found another way of doing it.
`this.onReorder = this.findTransactions.bind(this);`
Both achieve the same effect, thanks for your help.
