### ISSUE TITLE
md desc does not work

### ISSUE THREAD

**Issue by kxgoto1927** [daniel-nagy/md-data-table#406]
In the forkable demo, the calories column has md-desc directive yet the data does not come in descending order.  Am i missing something here?

**Comment by Koslun** [comment]
The codepen demo starts out with:
```javascript
$scope.query = {
    order: 'name',
    limit: 5,
    page: 1
  };
```
and

```html
 md-order="query.order"
```
in the thead tag. Meaning that the order of the table is enforced to be by name. The md-desc directive does however seem to change the default direction of the given column. Where clicking the calories column the first time will give you that descending order while the default seems instead for the others to be the ascending order. Can also be seen by the different directions the arrows are pointing at the start.

**Comment by kxgoto1927** [comment]
Thank you Koslun!!
