### ISSUE TITLE
How to add vertical lines to md-data-table

### ISSUE THREAD

**Issue by jvieyra92** [daniel-nagy/md-data-table#407]
Is there an easy way to add vertical lines to the table for each column?

**Comment by hectorgr** [comment]
In usability is not recommended, because the Horizontal lines helps to lead the eye along the line, while Vertical lines become a barrier along the eye path.
But try use this CSS code:
`table.md-table td.md-cell {border-left: 1px rgba(0, 0, 0, 0.12) solid; padding: 0 24px !important;}`

**Comment by jvieyra92** [comment]
Thanks that worked! I agree about that the usability might suffer but in my case I'm not displaying a lot of records per page and I'm graying the even rows as well.
