### ISSUE TITLE
Multiple tables and md-selected

### ISSUE THREAD

**Issue by twrk** [daniel-nagy/md-data-table#41]
Try using the select all checkbox in either table of [this plunker](http://plnkr.co/edit/qFA9Nts7MTXuMoR3B73a?p=preview), note that the md-selected arrays for the separate tables exhibit unexpected behavior.

**Comment by daniel-nagy** [comment]
This is strange, looking into it.

**Comment by daniel-nagy** [comment]
It's a scoping issue. I [forked](http://plnkr.co/edit/Kl9M3eDt6JWp4JAp7hcG?p=preview) your Plunker to demonstrate. I created an `isolate` directive that creates a new scope and attached it to the cards. I honestly don't know why this is an issue. the `md-data-table` directive should create a new isolated scope.

It's getting late enough too where I don't feel like looking at code anymore. I'll see about fixing this tomorrow. :)

**Comment by daniel-nagy** [comment]
@twrk sorry I haven't been able to get to this yet. I've been pretty busy this week, I may not have a solution for this until this weekend sometime. I know what the problem is and I think it may take a little bit of refactoring to fix it properly.

**Comment by twrk** [comment]
@daniel-nagy No problem, you've been quick to respond and address issues, keep up the great work!

**Comment by enthalpy-yan** [comment]
I also had some scope issue. I always get not defined as an array error even though it's an array in my controller.

**Comment by daniel-nagy** [comment]
@enthalpy-yan It sounds like your controller's scope may not be visible to your table. Make sure the scope of your table is a descendent of your controller's scope.

**Comment by enthalpy-yan** [comment]
@daniel-nagy yea, I was thinking the same thing but the data(same scope) in the table rendered correctly.

**Comment by daniel-nagy** [comment]
Interesting, have you tried using object notation for your selected items? Something like,

```javascript
var items = {
  selected: []
};
```

Sometimes this fixes issues with scope inheritance. If that doesn't work, if you could create a codepen, plunker, fiddle, etc. recreating the issue I would be happy to fix it for you.

**Comment by gerbil** [comment]
How can i use different md-row-select arrays for ng-repeat created tables?

**Comment by gerbil** [comment]
I've tried md-row-select=" '{{server.name}}' ", but no i got errors like:
rror: [$compile:nonassign] Expression ' 'TESTF' ' used with directive 'mdDataTable' is non-assignable!

**Comment by daniel-nagy** [comment]
@gerbil strings are non-assignable, the syntax should be `md-row-select="server.name"` where `server.name` is an array in your controller. When you select a row it will be pushed onto this array.

**Comment by gerbil** [comment]
I have 10 tables on one page, how can i use 10 different 'selected' arrays?

**Comment by daniel-nagy** [comment]
##### Solution One

Use the ng-controller syntax.

```html
<md-card ng-controller="myController" ng-repeat="table in tables"></md-card>
```

> The ngRepeat directive instantiates a template once per item from a collection. Each template instance gets its own scope.

[Codepen](http://codepen.io/anon/pen/NqLMer?editors=101)

##### Solution Two

Put the array on the variable you are repeating.

```html
<md-card ng-repeat="table in tables">
  <md-data-table-container>
    <table md-data-table md-row-select="table.selected">
   <md-data-table-container>
</md-card>
```

##### Solution Three

Create an array of arrays and access them by index.

```javascript
// in you controller
scope.selected = [[],[],[]]
```

```html
<md-card ng-repeat="table in [1, 2, 3]">

  <md-data-table-toolbar class="alternate" ng-show="selected[$index].length">
    <div>{{selected[$index].length}} {{selected[$index].length > 1 ? 'items' : 'item'}} selected</div>
  </md-data-table-toolbar>

  <md-data-table-container>
    <table md-data-table md-row-select="selected[$index]"></table>
  </md-data-table-container>

<md-card>
```

**Comment by Synturas** [comment]
Tested solution two, works absolutely fine as far as i can see.

**Comment by gerbil** [comment]
Solution number two gives me:

`md-row-select="server.selected" : server.selected is not defined as an array in your controller, i.e. server.selected = [], two-way data binding will fail.`

**Comment by daniel-nagy** [comment]
@gerbil to use solution two you would need to explicitly define the property selected as an array on your server object,

```javascript
server = {
  selected: []
};
```

Your solution works too though.

**Comment by duongtdvn** [comment]
Sorry for digging this up but I'm currently had an weird issue with the checkbox. Please take a look at this codepen which using the solution two: http://codepen.io/duongtd/full/Qjjadm

**Comment by daniel-nagy** [comment]
You're not using solution two correctly. You're using the same array to select items in both tables. You need to either attach the array to the objects you're repeating over or create a separate object of arrays and index them by key.

```javascript
$scope.selected = {
  eligendi: [],
  doloremque: []
};
```

```html
<table md-data-table md-row-select="selected[key]"></table>
```

**Comment by duongtdvn** [comment]
Thank you, I have tried with the selected[key] before, but I have no idea about the controller since the <code>key</code> is dynamically.

**Comment by duongtdvn** [comment]
I'm just modified the code a little bit so the selected[key] will match the key in the controller since it is dynamically. However i met this error:
<pre>Cannot set property 'eligendi' of undefined</pre>
can you please take a look? http://codepen.io/duongtd/pen/Qjjadm?editors=101

**Comment by duongtdvn** [comment]
Okay, I got it fixed! Instead of create the groupBy in the view, I made it in the controller and then do the ngRepeat in the view.
http://codepen.io/duongtd/full/Qjjadm
Hope someone if facing issue like me find the solution.

**Comment by parassanghani** [comment]
Hi there, i love this datatable, though i am having a problem when using multiple tables on a single page, all instances has stopped to sort and paginate. do you have any idea what could be wrong?
