### ISSUE TITLE
md-label for pagination uses white font

### ISSUE THREAD

**Issue by nordtorp95** [daniel-nagy/md-data-table#419]
Im using the pagination for my site, but the label displays the md-label in white font. if i select the text i can see it.
This is my pagination in as Jade.
md-table-pagination(md-label="{page: 'Page:', rowsPerPage: 'Rows per page:', of: 'of'}",md-limit='$ctrl.query.limit', md-limit-options='$ctrl.limitOptions', md-page='$ctrl.query.page', md-total='{{$ctrl.ingredients.length}}',  md-page-select='true', md-boundary-links='false')

**Comment by poojanbabu** [comment]
I also am facing the same issue. The pagination labels fail to show up inside a `ui-view`. Otherwise, they are displayed just fine.

This is the plunk - https://embed.plnkr.co/Nak4XVp4PkJW1EFZUug4/
Both 'username' and 'password' for login are "test".

Is this a bug or am I missing something?

**Comment by daniel-nagy** [comment]
@poojanbabu In your case there is a stylesheet called `labels.less` that is overriding the color of the label. If you don't have control over the stylesheet you can manually correct the color.

```css
.md-table-pagination .label {
  color: rgba(0, 0, 0, 87%) !important;
}
```

**Comment by nordtorp95** [comment]
Thank you, this solved the issue
