### ISSUE TITLE
Conflict between numeric columns and Angular's built-in number filter

### ISSUE THREAD

**Issue by twrk** [daniel-nagy/md-data-table#42]
When using both, the resulting behavior can be seen in [this plunker](http://plnkr.co/edit/qFA9Nts7MTXuMoR3B73a?p=preview) - any digits after the comma separator are truncated.

**Comment by daniel-nagy** [comment]
This is because Angular's filter is going to filter the number first and then parseFloat will try to parse the resulting string and will only read up to the first non-digit character, in this case the ','. I think I will just remove the precision attribute and advocate Angular's number filter.

**Comment by daniel-nagy** [comment]
You should be able to use Angular's number filter now.
