### ISSUE TITLE
Sticky header and footer

### ISSUE THREAD

**Issue by Justkant** [daniel-nagy/md-data-table#43]
Hi, it would be nice to have a sticky header and footer. I'll work this feature if I have time.

Nice work :)

**Comment by daniel-nagy** [comment]
@Justkant I've implemented a sticky header in the past for an interface library I wrote in Angular for work.

**Tricky things**
* Keeping the width of the header cells and the body cells the same without hacky code and registering a bunch of resize watch listeners for each column.
* Horizontally scrolling the header with the table.

The solution I eventually came up with involved cloning the original header and positioning it outside the table and then cloaking the original header by setting its height to 0. Then I could let the browser calculate the width of the columns for me. I was never able to find a solution for scrolling the header horizontally with the table body using this method.

Feel free to give this a try :) I'm going to warn you though, it's going to be a headache and you my never find a good solution.

**Comment by leocaseiro** [comment]
I was going to suggest for columns as well, but I believe wouldn't be that easy.

I'll might try somehting with [<md-subheader>](https://material.angularjs.org/latest/demo/subheader)

**Comment by leocaseiro** [comment]
Update:

> I'm actually working on this sticky header with the $mdSticky service, however I'll need to re-compile it before "clone".

> I'm loosing $scope with this service, hope the PR [/angular/material/pull/7151](https://github.com/angular/material/pull/7151) will help.

**Comment by leocaseiro** [comment]
I've just found this repo https://github.com/daniel-nagy/fixed-table-header, no way LOL!
