### ISSUE TITLE
Hide selection checkboxes

### ISSUE THREAD

**Issue by ConnorGBrewster** [daniel-nagy/md-data-table#45]
Hi would it be possible for you to add a directive to hide the checkboxes on the table?

**Comment by daniel-nagy** [comment]
Do you mean hide the checkboxes and still have selectable rows? If you don't want selectable rows you can remove the `md-row-select` attribute and the checkboxes will go away.

**Comment by ConnorGBrewster** [comment]
Ahhh I feel really stupid :( No idea why I didn't try that. 
By the way, nice work on the project, it is working perfectly for me!

**Comment by daniel-nagy** [comment]
@ConnorGBrewster Thanks!

Be sure to reference the [API Documentation](https://github.com/daniel-nagy/md-data-table#api-documentation) for usage.
