### ISSUE TITLE
Hide checkbox?

### ISSUE THREAD

**Issue by samster** [daniel-nagy/md-data-table#47]
Thanks for this great module!  I'm wondering if there is a way to disable showing the checkbox if I'm allowing "md-auto-select".  Essentially, I want to go to a different view once a user clicks on a row.  On that note, is there a event handler for the on-click event or just ng-click?  Thanks again!

**Comment by daniel-nagy** [comment]
I'm not entirely sure what you're trying to accomplish. If you just want to route the user to another view when they click a row I wouldn't use row select, I would just use `ng-click`. For example,

```html
<tr ng-repeat="item in items" ng-click="myRouterFunction(item)"></tr>
```
