### ISSUE TITLE
Losing reference to this on md-on-reorder callback with ES2015 class based controller

### ISSUE THREAD

**Issue by Zmixon** [daniel-nagy/md-data-table#471]
Similar to the issue linked here #430. I'm using an ES2015 class based controller (following Todd Motto's new angular style guide) and I lose reference to `this`, and I'm unable to `bind()` since it's being passed as a variable and the method is being called from the directive itself.

```
  getItems(order) { // Not using order yet as I can't even get this.item to fire correctly
    this.Item.fetch((this.query.page - 1) * this.query.limit, this.query.limit).then(res => this.success(res));
  }
```

**Comment by daniel-nagy** [comment]
@Zmixon see my comment [here](#400)
