### ISSUE TITLE
Get Selected Row

### ISSUE THREAD

**Issue by Synturas** [daniel-nagy/md-data-table#48]
Hello, i'm still wondering how i can access the selected rows, it says, my "selected" array is always undefined.

**Comment by daniel-nagy** [comment]
The variable you assign to the `md-row-select` attribute must be defined as an array. For example, in your template

```html
<table md-data-table md-row-select="selected"></table>
```

and in your controller,
```javascript
$scope.selected = [];
```

If you've done this and it is still not working, it may be that your controller's scope is not visible to the table directive. You need to be sure that your controller is an ancestor of the table directive.

If you're sure that the scope of your controller is visible to the table directive, you can try placing your array inside an object. Sometimes this will fix scope inheritance issues,

```javascript
$scope.selected = {
  items: []
};
```

Beyond that I would need to see some code to further assist you.

**Comment by Synturas** [comment]
It works now, after adding this line to my dialog controller:

locals: {selected: $scope.selected},
