### ISSUE TITLE
Unknown provider $nutritionProvider

### ISSUE THREAD

**Issue by gerbil** [daniel-nagy/md-data-table#49]
I'm facing this error in console after install + controller (layout) implementation:
Error: [$injector:unpr] Unknown provider: $nutritionProvider <- $nutrition <- nutritionController

**Comment by gerbil** [comment]
Also, you forgot to add to your docs that 'md.data.table' must be included in .module section.

**Comment by daniel-nagy** [comment]
@gerbil Are you trying to run the demo app? The nutrition controller exist only in the demo app and is not a part of the module. So if you are trying to use the nutrition controller in your own app, it's not going to work.

**Comment by gerbil** [comment]
Sure, thnx)
