### ISSUE TITLE
Pagination: issue when changing the page

### ISSUE THREAD

**Issue by floriaan** [daniel-nagy/md-data-table#497]
When I change the page of the table (with pagination) the table is showing the rows of the current page **with the rows of the previous page for 2s**. My limit is set to 5, thus the page is showing 10 rows instead of 5 for a moment.

Has anyone the same problem?

Any help will appreciated.

(Sorry for my broken english)

**Comment by daniel-nagy** [comment]
Sounds like something in your app is overwriting these styles on the table row, https://github.com/daniel-nagy/md-data-table/blob/master/src/styles/md-table.less#L119

**Comment by floriaan** [comment]
@daniel-nagy

**Comment by floriaan** [comment]
Thanks, I have found the problem. I had set a transition rule to the rows for background-color for 2s. That was the problem.

Many thanks!
