### ISSUE TITLE
Enable/Disable Multiple selection with expression

### ISSUE THREAD

**Issue by giquo** [daniel-nagy/md-data-table#503]
Hi
I been using your directive and is very nice.
I want to enable or disable the multiple selection conditionally with something like
`multiple="booleanVariable"`
but i didn't realize that in the documentation the multiple attribute is "expression" nor "[expression]"

Is the a way to do so?

**Comment by daniel-nagy** [comment]
You can enable/disable multiple selection with an expression, take a look at the [codepen](http://codepen.io/anon/pen/BjvLVJ?editors=1010).

```html
<table md-table multiple="{{options.multiSelect}}">
```

**Comment by giquo** [comment]
Oh! [goes-and-test-it]
Great! works like a charm. I didn't use the double {{variable}} 
Thanks man!
