### ISSUE TITLE
Pagination Styling

### ISSUE THREAD

**Issue by kelleysy** [daniel-nagy/md-data-table#504]
Hi, 

I was wondering if there was a way to style the pagination features so that text can be in between the arrows? Something like the screenshot..

![screen shot 2016-11-11 at 11 29 31 am](https://cloud.githubusercontent.com/assets/5864695/20227692/41d12a4e-a802-11e6-9fc0-b758193aba73.png)

**Comment by daniel-nagy** [comment]
You can use the flex `order` property, here is an example, http://codepen.io/anon/pen/gLPNVN

**Comment by kelleysy** [comment]
Thanks! 

I styled it using CSS:
.md-table-pagination > .buttons > .md-button.md-icon-button:first-of-type {
  order: -1;
}
