### ISSUE TITLE
Colum sorting (md-order) doesnt work as expected

### ISSUE THREAD

**Issue by mustafabereket** [daniel-nagy/md-data-table#509]
Hey There,

I am pretty sure I am doing something wrong, but for some reason I couldnt find it. 

Expected Behavior:

When you click sort icon next to the column name, it should sort the table in 'Ascending' order first.
Click it second time, it should order 'Descending' order.

Behavior I get:

Doesnt sort at all.

Code I have:

<md-table-container>
                <table md-table>
                    <thead md-head md-order="tsCtrl.query2.order" >
                    <tr md-row style="background-color: #e9e2e4">
                        <th md-column >
                        </th>
                        <th md-column md-order-by="task_id">
                            Task ID
                        </th>
                        <th md-column md-order-by="task_name">
                            Task Name
                        </th>
                        <th md-column>
                            Device Name
                        </th>
                        <th md-column>
                            Source Probs
                        </th>
                    </tr>
                    </thead>
                    <tbody md-body>
                    <tr md-row ng-repeat="item in tsCtrl.savedTasks | limitTo: tsCtrl.query2.limit: (tsCtrl.query2.page - 1) * tsCtrl.query2.limit">
                        <td md-cell>
                            <img src="assets/global/img/Icon_Check_35x35.png" style="width: 35px;height: 35px; float: left;border-radius: 50%;">
                        </td>
                        <td md-cell>
                            {{item.task_id}}
                        </td>
                        <td md-cell>
                            {{item.task_name}}
                        </td>
                        <td md-cell>
                            {{item.device_name}}
                        </td>
                        <td md-cell>
                            {{item.probs}}
                        </td>
</tr>
                    </tbody>
                </table>
            </md-table-container>
            <md-table-pagination md-limit="tsCtrl.query2.limit" md-limit-options="[5,10,25]" md-page="tsCtrl.query2.page" md-total="{{tsCtrl.savedTasks.length}}" md-page-select></md-table-pagination>

Does anyone see what I might possibly be missing?

Thanks,

**Comment by jansen07** [comment]
md-on-reorder -- you have to create a function that request JSON data from the server w/ paging and Sorting Capability in JSON format. the ordering takes place in server side. or just add Filter on the header.

**Comment by mustafabereket** [comment]
"you have to create a function that request JSON data from the server w/ paging and Sorting Capability in JSON format."

I can re-fill my array with same information, but what did you mean by "with paging and sorting capability"? if I am going to sort my array in the server side, what is the whole point using md-table's sorting functionality?

**Comment by daniel-nagy** [comment]
You need to pipe your repeater through `orderBy`.

```html
<tr md-row ng-repeat="item in tsCtrl.savedTasks | orderBy: tsCtrl.query2.order | limitTo: tsCtrl.query2.limit: (tsCtrl.query2.page - 1) * tsCtrl.query2.limit" >
```

If you are pulling items down from the server in chunks (i.e. paginating on the server) then @jansen07 is right, you will need to utilize `md-on-reorder` and dispatch a query to the server to sort the items.

**Comment by mustafabereket** [comment]
Thank you so much @daniel-nagy ! this solves my problem. I appreciate it!
