### ISSUE TITLE
Select all checkbox missing on gulp build

### ISSUE THREAD

**Issue by jammed343** [daniel-nagy/md-data-table#513]
After minification in gulp build, select all checkbox goes missing and all that is there is:

`<th class="md-column md-checkbox-column"></th>`

However each checkbox in each row in the body of the table is still there and working fine.

Any ideas?

**Comment by daniel-nagy** [comment]
What is the value of the `multiple` attribute after minification? #363

**Comment by jammed343** [comment]
That solved the issue
