### ISSUE TITLE
New release with latest changes?

### ISSUE THREAD

**Issue by christophercr** [daniel-nagy/md-data-table#522]
Hi,

I just want to know when do you plan to do the next release?

In my case I'm interested in the changes about the mdTableProgress as attribute directive instead of class directive.

Do you think it will be released soon?

Thanks

**Comment by daniel-nagy** [comment]
I released it but npm is not letting me publish it. If you install via Bower then it should be available. I don't think npm recognizes `v0.10.10` is a new version and not the same as `v0.10.1` but I'm not really sure.

**Comment by daniel-nagy** [comment]
nvm I forgot to update the version number in `package.json`
