### ISSUE TITLE
CodePen is broken

### ISSUE THREAD

**Issue by beazergood** [daniel-nagy/md-data-table#523]
Is anyone else having trouble getting the codepen to work? Page just continuously reloads for me with no console errors.

**Comment by daniel-nagy** [comment]
The [codepen](http://codepen.io/anon/pen/BjvLVJ?editors=1010) is working for me.

**Comment by beazergood** [comment]
I've just tried it in Safari and it's working, perhaps just an issue with Chrome (i'm running 55.0.2883.95 on Mac osx).

**Comment by daniel-nagy** [comment]
Just updated Chrome and it works for me. Maybe something weird is going on with your browser cache? Try opening it in an incognito window?

**Comment by beazergood** [comment]
Yep that must've been it. Worked in incognito and then in normal browser after I nuked my cache.  Thanks for taking the time to check. I'll try that first next time :)
