### ISSUE TITLE
Normalized Attribute Names

### ISSUE THREAD

**Issue by Synturas** [daniel-nagy/md-data-table#54]
Hello, i got a problem with filling the datatable rows dynamically:

right now i got this line, to fill each line with data:

header:

`<tr data-ng-repeat="selection in config.configs">
    <th order-by="name" data-ng-repeat="entry in selection">{{entry.attributeName}}</th>
</tr>`

body:

`<tr data-ng-repeat="selection in config.configs | orderBy: query.order | filter: skip | limitTo: query.limit">
    <td data-ng-repeat="entry in selection">{{entry.valueName}}</td>
</tr>`

It fills the data the right way, but it doesn't provide the selection options anymore.

When i provide the checkboxes by myself they aren't connected to the rows, as well as the select all function doesn't work properly. Is there a solution for this ?

**Comment by daniel-nagy** [comment]
Does your table have multiple header rows? This module is not designed for tables with multiple header rows and I think I would advise against it. It might be confusing for a user to see a table with multiple header rows and I'm not sure what meaning that would have.

Anyways, I just tried this in the demo app and using `ng-repeat` on a table header row resulted in each header row getting a master checkbox but row selection still worked. I don't see anything else that would break row selection.

For me to help you further I would need to see a plunker, code pen, etc. that clearly demonstrates the issue.

**Comment by Synturas** [comment]
No i dont have multiple header rows, my markup looks like this right now:

`<md-data-table-container>
            <table md-data-table md-row-select="selected">
                <thead md-order="query.order">

                    <tr data-ng-repeat="selection in config.configs">
                        <th order-by="name" data-ng-repeat="entry in selection">{{entry.attributeName}}</th>
                    </tr>

                </thead>
                <tbody md-auto-select>
                    <tr data-ng-repeat="selection in config.configs | orderBy: query.order | filter: skip | limitTo: query.limit">
                        <td data-ng-repeat="entry in selection">{{entry.valueName}}</td>
                    </tr>
                </tbody>
            </table>
        </md-data-table-container>`

while configs looks like this:

`[
   {
      "productId":175,
      "productName":"B.Lee",
      "configs":[
         [
            {
               "attributeId":"176",
               "attributeName":"Durchmesser",
               "valueId":180,
               "valueName":"25cm"
            },
            {
               "attributeId":"177",
               "attributeName":"Lichtstärke",
               "valueId":181,
               "valueName":"50l"
            },
            {
               "attributeId":"178",
               "attributeName":"Radius",
               "valueId":183,
               "valueName":"10cm"
            },
            {
               "attributeId":"179",
               "attributeName":"Preis",
               "valueId":182,
               "valueName":"300€"
            }
         ]
      ]
   }
]`

**Comment by daniel-nagy** [comment]
In your `thead` element, you are using `ng-repeat` on the `tr` element. This could potentially produce multiple header rows if you had more that one object in your `configs` array. I might suggest reconsidering the format of your object or to not use `ng-repeat` to access the first object in an array.

I've created a fork-able Codepen under the [Demo](https://github.com/daniel-nagy/md-data-table#demo) section in the `README`. Please use this to reproduce the issue and I will try to fix it for you.

**Comment by Synturas** [comment]
For me it's not possible not to use ng-repeat, because the table head has a dynamic parameter size.

I forked your Codepen http://codepen.io/anon/pen/OVoWbE

**Comment by daniel-nagy** [comment]
The reason row selection is not working is because you are using `data-ng-repeat` instead of `ng-repeat` in the table body. In the module I'm checking if the `ng-repeat` attribute exists.

I updated your [Codepen](http://codepen.io/anon/pen/vOzxBz).

Do you need to validate your HTML? For now you can use `ng-repeat` and row selection should work. I'm going to rename this issue to normalized attribute names.
