### ISSUE TITLE
Incorrect values for search with pagination client side

### ISSUE THREAD

**Issue by tejasrivastav** [daniel-nagy/md-data-table#544]
http://codepen.io/anon/pen/LxOKZd?editors=1010,

Enable search with client side pagination.
The pagination values are incorrect.

**Comment by ielektronick** [comment]
Pagination values ARE correct, because you assign `filteredDesserts` to `desserts.data`.
This works:
`... ng-repeat="dessert in (filteredDesserts = (desserts.data | filter: search | orderBy: query.order | limitTo: query.limit : (query.page -1) * query.limit))" ...`

**Comment by tejasrivastav** [comment]
Even in that case the resultant array has only 5 values.

http://codepen.io/anon/pen/LxOKZd?editors=1010

**Comment by ielektronick** [comment]
Sorry, but I don't see any changes in your codepen. Did you update it with recommend ones?

**Comment by tejasrivastav** [comment]
sorry, updated link http://codepen.io/anon/pen/RpJwqd?editors=1010

**Comment by ielektronick** [comment]
You need to put a bracket not at the end, but after 'filter:search'. Take a look st recommended changes in my comment :)

**Comment by ielektronick** [comment]
Like that:
`(filteredDesserts = (desserts.data | filter: search) ...`

**Comment by tejasrivastav** [comment]
My bad. Noob Me.
Thanks a ton. :)
