### ISSUE TITLE
Tag Latest Build

### ISSUE THREAD

**Issue by cah-alexsukhodolsky** [daniel-nagy/md-data-table#55]
Please tag your latest build as there is currently no way for me to specify a version of md-data-table in my project's bower.json. I have to set the version to "*" but prefer to specify an actual build number "0.7.6" so future changes don't break the functionality.

Per Bower's documentation for the bower.json file (http://bower.io/docs/creating-packages/):

### Version
**Ignored by Bower as git tags are used instead.**

*Intended to be used in the future when Bower gets a real registry where you can publish actual packages, but for now just leave it out.*

**Comment by daniel-nagy** [comment]
@cah-alexsukhodolsky I will do this tonight after work. Nice avatar btw, I just finished season one of Silicon Valley.

**Comment by cah-alexsukhodolsky** [comment]
Awesome--thanks!
The first season of Silicon Valley was great.
