### ISSUE TITLE
Select All using md-virtual-repeat issue

### ISSUE THREAD

**Issue by maxalencar** [daniel-nagy/md-data-table#554]
When we are using md-virtual-repeat-container and click on select all, it's not selecting every single element on the list, for example my list contains 100 elements but it's selecting only 10. If I'm not using virtual repeat it work perfectly, is there any solution for it?

Cheers,

**Comment by lievenjanssen** [comment]
@maxalencar did you find a workaround for this?

**Comment by ArvindNikam76** [comment]
did u get solution for above

**Comment by maxalencar** [comment]
@lievenjanssen, @ArvindNikam76,
Nope, unfortunately
