### ISSUE TITLE
Multiple Tables on one Site

### ISSUE THREAD

**Issue by Synturas** [daniel-nagy/md-data-table#56]
Hey, 

i got an issue with the selected items, when having multiple tables at the same page.
Unfortunately i'm not able to write the "md-row-select" value by hand, because im creating the tables with ng-repeat. How do i refer to an array for each generated table in a dynamic way?

**Comment by daniel-nagy** [comment]
I'm actually working on answering this question right now. This same quest was asked in hour ago, see #41. I'm going to post the answer there.
