### ISSUE TITLE
Not sort all page, just only one page

### ISSUE THREAD

**Issue by zzjustinzz** [daniel-nagy/md-data-table#565]
Dont know why my table is order in only one page, not all page.

![image](https://cloud.githubusercontent.com/assets/4983541/24191358/2a2b0864-0f1e-11e7-8b67-72f72593f189.png)

Anyone can help me :( 

My code:
- HTML:
![image](https://cloud.githubusercontent.com/assets/4983541/24191427/68936bb4-0f1e-11e7-83f8-8eba75858cf4.png)

- Controller:
![image](https://cloud.githubusercontent.com/assets/4983541/24191459/808f50ac-0f1e-11e7-83eb-3e49110e77d8.png)

**Comment by ielektronick** [comment]
For md-head there's an attribute: `md-on-reorder="getItems"`. Did you try it?
Also delete orderBy from ng-repeat.

**Comment by ielektronick** [comment]
Just to provide a working example.
Mark-up:
![2017-03-22 13_48_10-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/24196405/5f2c5d32-0f06-11e7-88ba-305f8db638cf.png)
Code:
`self.$scope.manufacturers = [];`
`self.$scope.query = { filter: '', limit: 15, order: 'name', page: 1 };`
`self.$scope.getManufacturers = function () {`
`    self.$scope.promise = self.manufacturerService`
`        .get(self.$scope.query, function (response) {`
`            self.$scope.manufacturers = response.items;`
`            self.$scope.manufacturers.count = response.itemsCount;`
`        });`
`};`

**Comment by zzjustinzz** [comment]
![image](https://cloud.githubusercontent.com/assets/4983541/24229730/a375d778-0fad-11e7-8a91-a21002b41a45.png)

I have tried follow your instruction, but it's not still working. :(

**Comment by zzjustinzz** [comment]
[image: Inline image 1]

I have tried follow your instruction, but it's not still working. :(
ᐧ

**Comment by ielektronick** [comment]
Okay, as far as I can see, you load items from the API. At least I see `md-progress` usage, which should be used only for that. :)
Let me share a working example. So here's a mark-up:
![2017-03-23 11_04_49-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/24239956/919e365c-0fb8-11e7-8d59-1f2a37767be6.png)
Here's an initial state inside controller:
![2017-03-23 11_05_19-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/24239981/a7e5ef36-0fb8-11e7-80fa-158c3ee6db37.png)
Here's a code for `getManufacturers` method:
![2017-03-23 11_06_18-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/24240016/ce582d0a-0fb8-11e7-8f55-4402441713a3.png)
Now, all together. Page 1:
![2017-03-23 11_10_21-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/24240201/6fa40292-0fb9-11e7-8ea1-661e8089dee6.png)
Page 2:
![2017-03-23 11_10_41-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/24240207/74d2a0ac-0fb9-11e7-922f-4515e8aaae27.png)

In case you're using pagination on a front-end, then it should be done a bit in another way. :)

**Comment by muscaiu** [comment]
Does your Search filter work for the current page only or for the whole data?

**Comment by zzjustinzz** [comment]
My Search filter is working for the whole data, but order is just only current page.

**Comment by ielektronick** [comment]
For the whole data.

**Comment by zzjustinzz** [comment]
Dont know why, but it's not work for me:

My HTML:
![image](https://cloud.githubusercontent.com/assets/4983541/24241116/5e540fa0-0fe6-11e7-9fde-b2b40759032c.png)

My controller:
![image](https://cloud.githubusercontent.com/assets/4983541/24241133/6b19296e-0fe6-11e7-8313-9f472eab4a1a.png)
![image](https://cloud.githubusercontent.com/assets/4983541/24241148/760a83d6-0fe6-11e7-8667-fd1b3562586a.png)

My page:
- Page 1
![image](https://cloud.githubusercontent.com/assets/4983541/24241208/9be49c7c-0fe6-11e7-84a2-6eef5a50b501.png)

-Page 2
![image](https://cloud.githubusercontent.com/assets/4983541/24241234/acd07e98-0fe6-11e7-93ad-0188d382cb50.png)

**Comment by ielektronick** [comment]
I see. So you load all the items and try to sort them and paginate? :)

**Comment by zzjustinzz** [comment]
Yep. I load all item first and sort, paging them then.

**Comment by ielektronick** [comment]
Okay, I assume that data is not ordered from the beginning thus you have such strange pagination with ordering. Try to order the data right after you received it:
`$scope.kaizens = kaizens.result.map(function(k1, k2) {`
`if (k1.name > k2.name) {`
`return 1;`
`}`
`if (k1.name < k2.name) {`
`return -1;`
`}`
`return 0;`
`}`;

**Comment by ielektronick** [comment]
So, as a summary. Return to original mark-up and code and put `orderBy` before `limitTo`.

**Comment by zzjustinzz** [comment]
Thanks its worked.
