### ISSUE TITLE
Progress bar wrong column count

### ISSUE THREAD

**Issue by Synturas** [daniel-nagy/md-data-table#57]
Hey,

when creating the header elements in a dynamic way, the column counter function returns a wrong value, it seems, that the function counts the rows, before "ng-repeat" finishes it's work.

**Comment by daniel-nagy** [comment]
Okay, I think you're right. It will need to wait for `ng-repeat` to finish.

**Comment by Synturas** [comment]
What about just setting 

`<td colspan="100%"></td>`

**Comment by daniel-nagy** [comment]
Using percentages in `colspan` is invalid syntax. The `colspan` attribute only accepts numbers. There is a special syntax to tell the column to span the entire `colgroup` but that only works in Firefox. [Reference](http://www.w3schools.com/tags/att_td_colspan.asp).

**Comment by daniel-nagy** [comment]
Another problem with using `ng-repeat` on header cells is that body cells in numeric columns are not right aligned. I'm going to need to do something similar to what I did in the table body and check for an `ng-repeat` directive on a header cell and tag it with my own directive that can notify the rest of the directives when `ng-repeat` has finished.
