### ISSUE TITLE
Translate (Page: Rows per page:) to another language

### ISSUE THREAD

**Issue by muscaiu** [daniel-nagy/md-data-table#575]
How can i translate this to another language?

![2017-04-04_11h41_18](https://cloud.githubusercontent.com/assets/11426309/24648304/e5d5fb16-192b-11e7-9234-e0050af1ff2d.png)

```
<md-table-pagination md-limit="sort.limit" md-limit-options="limitOptions" md-page="sort.page" md-total="{{int.interviewsList.length}}"
    md-on-paginate="promiseInterviews" md-page-select></md-table-pagination>
```

**Comment by ielektronick** [comment]
Hi muscaiu
As far as I can see there's a `mdLabel` attribute available. It accepts an object with 3 possible properties: `page`, `rowsPerPage` and `of`.
So, the mark-up is:
```html
<md-table-pagination md-limit="query.limit" md-limit-options="[5, 10]" 
        md-page="query.page" md-total="{{items.length}}"
        md-page-select md-label="{ page: 'Сторiнка', rowsPerPage: 'Кiлькiсть на сторiнку', of: 'з' }">
</md-table-pagination>
```

**Comment by muscaiu** [comment]
Thanks brother!

**Comment by marceloavan** [comment]
Is there some way to translate these informations in config phase using something like a provider?
