### ISSUE TITLE
How to remove the blue line made by ng-click

### ISSUE THREAD

**Issue by waitingduck** [daniel-nagy/md-data-table#582]
Hi,

I would like to know is it possible to remove the blue line made by ng-click because this blue line render not as expected. I cannot reproduce it on your demo, but maybe is similar to the result when you double click the row and the left and right line will disappear(in live demo).

After add ng-click to \<tr\>. It shows blue line when you click the row.
![screen shot 2017-04-20 at 3 40 01 pm](https://cloud.githubusercontent.com/assets/6858982/25255637/824613e4-25e0-11e7-8067-28729064702c.png)
If you double click, left and right line disappear.
![screen shot 2017-04-20 at 3 40 09 pm](https://cloud.githubusercontent.com/assets/6858982/25255646/8d199444-25e0-11e7-9969-45b3505aaa93.png)

Mine is worse, it some time looks like this
![screen shot 2017-04-20 at 3 40 56 pm](https://cloud.githubusercontent.com/assets/6858982/25255659/a27fa92c-25e0-11e7-942d-8b1d61839c4b.png)
or
![screen shot 2017-04-20 at 3 41 04 pm](https://cloud.githubusercontent.com/assets/6858982/25255662/a6061766-25e0-11e7-93ce-4a8cdc9a20be.png)

Here is my code
```
<md-table-container>
  <table md-table md-row-select="true">
    <thead md-head md-order="myOrder.order">
    <tr md-row>
      <th md-column ng-repeat="(index, col) in requestTable.data.header"
          md-order-by="{{requestTable.data.keys[index]}}">{{col}}
      </th>
    </tr>
    </thead>
    <tbody md-body>
    <tr md-row ng-repeat="data in requestTable.data.data | orderBy: myOrder.order" ng-click="">
      <td md-cell ng-repeat="col in requestTable.data.keys" >{{data[col]}}</td>
    </tr>
    </tbody>
  </table>
</md-table-container>
```
Not sure what happened here. So my first thought is  to disable the blue line. Any suggestion is welcome.

Thanks.

**Comment by ielektronick** [comment]
Hi @waitingduck 
The issue is completely CSS. :)
So, I assume you're using Chrome. Chrome adds `outline` styles for focused elements depending device (mobile or desktop). Please take a look:
![2017-04-21 09_40_16-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/25265673/76cf61a8-266e-11e7-8574-3e2efecd26d3.png)
And in computed:
![2017-04-21 09_40_45-cphdev7 - remote desktop connection](https://cloud.githubusercontent.com/assets/889454/25265683/7fdcdcd0-266e-11e7-88d8-777a66458589.png)
To fix that just add:
```css
tr.md-row:focus {
    outline: none;
}
```
PROFIT :1st_place_medal:

**Comment by waitingduck** [comment]
Hi @ielektronick 

That's a good suggestion and fix my problem. But wondering do you know why is that happen? 

Thanks!

**Comment by AntonisFK** [comment]
@waitingduck Its a default browser outline its supposed to help keyboard users and users with reduced vision where there currently are on the page.

**Comment by waitingduck** [comment]
I see. Thank you @AntonisFK and @ielektronick. Problem solved:)
