### ISSUE TITLE
md-single-select

### ISSUE THREAD

**Issue by Robbio** [daniel-nagy/md-data-table#59]
I'm not sure if this is the right forum to ask, so please direct me accordingly.

I was looking at the source, and wondered if it would be possible to update the table to be configured to only allow single selection of a given row in the table.  Additionally, if the table is defined as md-single-select="selected" then no check boxes are really needed, but the selected row remains highlighted...  and only one row is selectable.

I really like this library, and plan to follow it's updates.

All the best.

~Rob.

**Comment by daniel-nagy** [comment]
@Robbio

You may conditionally disable row selection; however, the checkboxes will remain in a disabled state. Here is a [link](https://github.com/daniel-nagy/md-data-table#row-selection) to the section on row selection. You will see an example for conditionally disabling rows.

From your description, I'm not sure if this exactly what you are looking for or not. Without a checkbox, it may not be obvious to the user that the row is selectable. In addition, tables are intended for efficient manipulation of large data sets. If the user can only select one row maybe you should consider a different UI for what you are trying to achieve?

**Comment by Robbio** [comment]
Thanks for the response.
I only suggested adding support for single selection as I'm thinking of the use case where the user selects a given row to open (a dialog) an "Edit" view
en row to open (a dialog) an "Edit" view of the record that the row represents.  In this case, multi-selection in a large set doesn't necessarily make sense.

I managed to add in single row (only) selection into the table.  Effectively I followed some of your boolean logic on the ng-class setting.  However I mainly just stuck to the base Angular hooks and didn't turn on md-row-select at all.  

Nothing fancy.  I was just thinking it'd be a nice feature to add to the library is all, in terms of flipping a flag to supporting single row selection as opposed to assuming only use of multi-selection.

For example:
In the html I added:

<tr ng-repeat="item in items" ng-click="rowSelection(item.id)" ng-class="{'md-selected':wasSelected(item.id)}">


In the controller class I added: 

$scope.selectedRow = null;
$scope.rowSelection = function rowSelection( id ) {
    $scope.selectedRow = id;
}
$scope.wasSelected = function wasSelected( id ) {
    return $scope.selectedRow === id;
}

**Comment by daniel-nagy** [comment]
This is pretty trivial using `ng-click` as you just demonstrated. Editing dialogs to manipulate individual cells is planned for future releases.

**Comment by gaboAcosta** [comment]
On the material design manual, it states that for edition the row should be selected with the checkbox and a controll will appear on the header to open the edition. (this is just an option is not mandatory but I think it is the best UX)

https://www.google.com/design/spec/components/data-tables.html#data-tables-tables-within-cards

**Comment by daniel-nagy** [comment]
@gaboAcosta valid point.

I'm Closing this issue as I don't believe this is something that should be handled internally by the module. If you want to do something other than select a row when clicked you can use `ng-click` to capture the event.
