### ISSUE TITLE
mdOnSelect calling a function multiple times

### ISSUE THREAD

**Issue by marcio-eric** [daniel-nagy/md-data-table#592]
When I create a table and set it to call a callback function when an item is selected and reload the page, even with NO item selected it invokes the function several times until the window hangs.
![image](https://cloud.githubusercontent.com/assets/26447587/26509733/7a79b820-4230-11e7-9359-38e94bc7aa02.png)
![image](https://cloud.githubusercontent.com/assets/26447587/26509740/84706d74-4230-11e7-8c47-ece5e3f9babb.png)
![image](https://cloud.githubusercontent.com/assets/26447587/26509748/90cb7e1a-4230-11e7-811f-b363226823bf.png)

**Comment by ArvindNikam76** [comment]
did you get solution for this

**Comment by marcio-eric** [comment]
@ArvindNikam76 Yes, in my partial view I had this:

```
<tbody md-body>
    <tr md-row md-select="flow" md-select-id="flow.id" md-auto-select md-on-select="onSelectItem()" ng-repeat="flow in flows">
        <td md-cell>{{flow.step}}</td>
        <td md-cell>{{flow.desc}}</td>
        <td md-cell flex>
            <md-button ng-if="editItem" class="md-fab md-primary md-mini" aria-label="Profile" ng-click="editItem($event, flow)">
                <md-icon md-font-set="material-icons">create</md-icon>
            </md-button>
            <md-button ng-if="removeItem" class="md-fab md-warn md-mini" aria-label="Profile" ng-click="removeItem($event, flow, mainList)">
                <md-icon md-font-set="material-icons">delete_forever</md-icon>
            </md-button>
        </td>
    </tr>
</tbody>
```

I have the md-on-select () method, but it should only be passed the method name, ie:  
 md-on-select = "onSelectItem" no md-on-select = "onSelectItem ()"

**Comment by ottort-23** [comment]
Thanks for the solution! this is i was looking for days.
