### ISSUE TITLE
User Interface Lag

### ISSUE THREAD

**Issue by dschreck17** [daniel-nagy/md-data-table#602]
I have an array of 1000 records (pretty large JSON objects though) and whenever I use the pagination or sort by one of the column headers the table takes a few seconds to respond. The data is all client side. Is there any solution for making the sort/pagination respond faster or display an activity indicator while it is processing?

**Comment by Satif** [comment]
yeap. You must use server side pagination, i.e.:
page=1&top=10&skip=0

**Comment by dschreck17** [comment]
ahh okay thanks @Satif
