### ISSUE TITLE
How to select all rows?

### ISSUE THREAD

**Issue by diegoberges** [daniel-nagy/md-data-table#639]
When I have a lot of rows, and I have pagination, y can only check the rows in the active view.

How can I select all rows? it's possible?

**Comment by dang-toan** [comment]
Set:
`<table md-table multiple="true">`
View more demo here: https://codepen.io/anon/pen/OZVMJg?editors=1010

**Comment by dBer** [comment]
What I need is to be able to select all the elements of all the pages, not just the first one.

**Comment by dang-toan** [comment]
Not support now. You have to do it by yourseft.

**Comment by deyvidfk** [comment]
@dBer a simple example:
vm.selectAllRows = function () {
	// pre selection of all rows                
	vm.dataGrid.dataSet.forEach(function (item) {
		// set value in mdTableNgModel;
		vm.selectedRow.push(item);
	});

	// 
	// Do not do this: angular.copy (vm.dataGrid.dataSet, vm.selectedRow);
	// Also do not do this: vm.selectedRow = vm.dataGrid.dataSet;
	// I had referral issues between the instances of the dataset object when I assigned the value to the NgModelAttribute of mdTableElement because when I unchecked the row mdRowCheckbox 
	// the item was automatically removed from the table.	
};

**Comment by deyvidfk** [comment]
@dBer  simple example:


vm.selectAllRows = function () {
     // pre selection of all rows                
	vm.dataGrid.dataSet.forEach(function (item) {
		// set value in mdTableNgModel;
		vm.selectedRow.push(item);
	});
};

	// Do not do this: angular.copy (vm.dataGrid.dataSet, vm.selectedRow);
	// Also do not do this: vm.selectedRow = vm.dataGrid.dataSet;
	// I had referral issues between the instances of the dataset object when I assigned the value to the NgModelAttribute of mdTableElement because when I unchecked the row mdRowCheckbox 
	// the item was automatically removed from the table.

**Comment by dBer** [comment]
Sorry, you can explain your idea?

I'm editing the file _md-data-table.js_ but I can`t select all rows, I can only select the raws that there are in the first page of table.

Thanks

**Comment by deyvidfk** [comment]
@diegoberges
The variable assigned to the ngModel attribute contains all selected rows from the table, so the idea is basically to copy all items from the dataSource to ngModel, this will tell the table that such rows are selected.

**Comment by diegoberges** [comment]
Thanks!
