### ISSUE TITLE
Live Demo has security breach (Kinda)

### ISSUE THREAD

**Issue by ScriptKiddy99** [daniel-nagy/md-data-table#657]
With some small manipulation you are able to delete database entries without entering a valid "Secret", this needs looking into, or else someone could wipe the whole DB/Enter more malicious code :)

**Comment by daniel-nagy** [comment]
Can you email me the method to delete items or run malicious code? My email is is on my github account.

**Comment by ScriptKiddy99** [comment]
Sorry never got the notification for the response! see your email :)

**Comment by daniel-nagy** [comment]
Thanks, this has been fixed
