### ISSUE TITLE
I'm curies to know the date on the changelog

### ISSUE THREAD

**Issue by jimmywarting** [daniel-nagy/md-data-table#66]
Could you include the date when you wrote the new updated version please?

**Comment by daniel-nagy** [comment]
Where do you want to see the date, in the change log of the README? You can always look at the commit history for a particular branch, the dates of the commits are shown there.

**Comment by jimmywarting** [comment]
I know, but that is kind of annoying.
Would be easier to see that in the log of the README.

You don't have to do it on all previous commits, but just for a feature reference

**Comment by daniel-nagy** [comment]
Okay, I'll start putting dates in the change log.
