### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by tiltshiftfocus** [daniel-nagy/md-data-table#68]
May I know how does the client side pagination work exactly?
What function do I have to create for the md-trigger?

The page doesn't seem to change although the page number does change.

**Comment by daniel-nagy** [comment]
You do not need a trigger function if you are doing pagination in the client. If your `ng-repeat` looks like this,

```html
<tr ng-repeat="item in $items | orderBy: $order | limitTo: $limit: ($page - 1) * $limit">
```

and your `md-data-table-pagination` element looks like this,

```html
<md-data-table-pagination md-limit="$limit" md-page="$page" md-total="{{$items.length}}"></md-data-table-pagination>
```

where `$items`, `$order`, `$limit`, and `$page` are defined on the scope, then pagination should work without needing to do any extra work.
