### ISSUE TITLE
Editing Dialogs

### ISSUE THREAD

**Issue by daniel-nagy** [daniel-nagy/md-data-table#7]
Table cells can display editing dialogs to do inline changes of data.

**Comment by cleydsonjr** [comment]
@daniel-nagy I was thinking about the best markup approach and came up with this solution:
```html
...
 <td md-edit-dialog ng-model="dessert.comment">Add a comment</td>
...
```
and for the large option:

```html
...
 <td md-edit-dialog="large" md-dialog-title="Add a title" ng-model="dessert.comment">Add a comment</td>
...
```

Whats your opinion?

**Comment by daniel-nagy** [comment]
A few things.

* For large dialogs, we will need attributes for the cancel and save events. Something that will allow the developer to execute their own functions when the buttons are clicked.

* For large dialogs, we will need attributes that allow the developer to change the text for the cancel and save buttons for non-English applications.

* We might want to consider making two separate directives, `md-edit-dialog-small` and `md-edit-dialog-large`. This way we can separate the logic and templates for small and large edit dialogs.

**Comment by cleydsonjr** [comment]
I agree with you. But we should have default save/cancel events. Only set the value to the model when save and do nothing when cancel.

Anyway.. I'm gonna focus just on `md-edit-dialog-small` for a first submission.

**Comment by daniel-nagy** [comment]
Okay. Another thing to think about is attributes for input validation. Things like `max-length` and `required`.

**Comment by jimmywarting** [comment]
There is alot of things you would like to be able to control in the dialog, such as the text translation, type of input, validation, step, title, placeholder, error message, ng-model-options.

Maybe we should do what `$mdDialog` are able to do: use a templateUrl or a template string. then md-edit-dialog is only responsible for showing a nice dialog at the correct position and a developer can control the dialog as much as he wants. then resolve or reject the dialog

**Comment by daniel-nagy** [comment]
@jimmywarting that might be a good solution.

**Comment by jimmywarting** [comment]
one thing i also was thinking of was that the small and large dialog can be smart enough to figure out what kind of input type should be used.

if `thead>tr th` is numeric or the `typeof value` are number show a `input type=number` or if the typeof value are boolean show a checkbox and so on

**Comment by HBO2** [comment]
Hi,

I am searching for the option to have an edit action on each row. I mean by having an edit icon at the end of the row with action to edit the cell's in a row. So, not by selecting the row first and then have an action to edit the the cell's of the row, but directly a dialog after clicking on the edit pencil. 
In case no i could ask some developers to help you, but it would be graet if you can guide them while developing this function.

Let me know what you think.

Greetings and my compliments for this very good data table. In my opnion one of the best in the sense of following the google guideleines.

**Comment by lily93** [comment]
Hi,
(sry for bad engilsh in advance)
i'm quite new to angular and this module in particular..
i just wanted to know some things to get an edit dialog (does not matter if small or large) work, i could neither find any examples in the api documentation nor any clear explanation via google regarding the html specs.... soo:
- how is the tag specified? (md-edit-dialog/ class="?" ... )
- how does the binding to a function via click on the row work? (ng-click)
- is it working within ng-repeat?

i would really appreciate your help :)

**Comment by daniel-nagy** [comment]
@lily93 

> how is the tag specified? (md-edit-dialog/ class="?" ... )

Edit dialogs are an Angular service not a directive. You do not use HTML tags to create an edit dialog, you must use Javascript. There is an example, along with a description of each option, included in the documentation for [edit dialogs](https://github.com/daniel-nagy/md-data-table#edit-dialogs). There is also a live example in the [Codepen](http://codepen.io/anon/pen/BjvLVJ?editors=1010).

> how does the binding to a function via click on the row work? (ng-click)

At the very bottom of the **Edit Dialogs** section you will see a snippet of HTML that looks like

```html
<td md-cell ng-click="editComment($event, dessert)" ng-class="{'md-placeholder': !dessert.comment}">
  {{dessert.comment || 'Add a comment'}}
</td>
```

`ng-click` is a wrapper around HTML's `onclick` attribute that essentially allows Angular to be notified of the click event. In order to bind to a function it must be available in the current scope. For edit dialogs the click handler must be placed on a table cell.

> is it working within ng-repeat?

Yes, `ng-repeat` should be okay.

**Comment by lily93** [comment]
@daniel-nagy 
thanks for the reply!
everything is working now, the Codepen example was just what i was looking for :)

**Comment by offwork** [comment]
TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function...

**Comment by offwork** [comment]
TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function, TypeError: $mdEditDialog.small is not a function.........................................

**Comment by daniel-nagy** [comment]
@offwork did you inject the `$mdEditDialog` service into your controller?

**Comment by offwork** [comment]
It was already there, but it fixed when adding $timeout....

**Comment by nani3105** [comment]
For the large dialog , is passing in the message array resolved for ng messages, currently this doesn't work. I do not want to roll a custom dialog just for this case
