### ISSUE TITLE
descendFirst on $scope.query

### ISSUE THREAD

**Issue by PatrikLythell** [daniel-nagy/md-data-table#74]
Would be nice if you could choose descendFirst on initial $scope.query in controller. Useful for dates.

```javascript
$scope.query = {
    order: 'name',
    descendFirst: true,
    limit: 5,
    page: 1
};
```

**Comment by daniel-nagy** [comment]
Does using a minus sign work?

```javascript
$scope.query = {
  order: '-name',
  limit: 5,
  page: 1
};
```

Then you can put the `descendFirst` attribute on the column header to have it sort descending by default when the user clicks it. Let me know if this works for you.

I found a bug while testing this for you. When you hover a column header with the descend first attribute the arrow icon should point downwards. The column will still sort descending though.

**Comment by PatrikLythell** [comment]
Ah! You my friend are a genius, thanks! Sorry for taking up your time.

**Comment by daniel-nagy** [comment]
No problem! This issue lead me to discover that other bug, which should be fixed now. :+1:
