### ISSUE TITLE
header title not showing

### ISSUE THREAD

**Issue by Synturas** [daniel-nagy/md-data-table#76]
After updating to the newest version the header titles are not showing up anymore.

**Comment by daniel-nagy** [comment]
Do you know which version you were using before you updated? In version 0.8.0 there were some syntax changes to column headers. You must now use an attribute to specify the column name.

```html
<th name="name"></th>
<!-- or if name is a scope variable -->
<th ng-repeat="column in columns" name="{{column.name}}"></th>
```

**Comment by Synturas** [comment]
I didn't recognize the syntax changes, thanks alot!
