### ISSUE TITLE
how to put the header attributes

### ISSUE THREAD

**Issue by checherman** [daniel-nagy/md-data-table#77]
`<md-data-table-container>
  <table md-data-table >
    <thead >
      <tr>
        <th hide-sm width="45px" name="ID" ></th>`

the hide -sm and width attributes once the page loads disappear.

**Comment by daniel-nagy** [comment]
I'm actually working on this right now, should have a fix soon. The problem is I'm replacing the `<th>` element with a template that I manufacture and I'm not preserving the attributes of the original element.

**Comment by checherman** [comment]
I have added an attribute to pass attributes to the temple in this way in the directive function mdColumnHeader

`var attrib = '';
	if(angular.isDefined(attrs.attrs)){
      attrib = attrs.attrs;
    }
    var template = angular.element('<th ' + attrib + '></th>');`

in view `<th attrs="hide-sm" name="ID" order-by="id"></th>`

**Comment by daniel-nagy** [comment]
I was just going to keep any attributes defined on the element

```javascript
angular.forEach(element.prop('attributes'), function (attr) {
  // we can't compile the element with the attribute for the directive attached to it
  // or we will infinite loop
  if(attr.name !== 'md-column-header') {
    template.attr(attr.name, attr.value);
  }
});
```

I don't believe your solution would work for all attributes.

**Comment by daniel-nagy** [comment]
Can you confirm that version 0.8.5 resolves this issue?

**Comment by checherman** [comment]
It works all Attributes are obtained But stop work order effects

**Comment by daniel-nagy** [comment]
Can you be more specific when you say the order effects stop working?

**Comment by checherman** [comment]
It works great version 0.8.5

**Comment by daniel-nagy** [comment]
Awesome!
