### ISSUE TITLE
Checkbox color

### ISSUE THREAD

**Issue by jsenecal** [daniel-nagy/md-data-table#78]
Hello there,

As per https://www.google.com/design/spec/components/data-tables.html#data-tables-interaction it seems like you are using the wrong color for the checkbox... `md-primary` class is used while I think it should be `md-accent` or nothing at all as `<md-checkbox>` is in the accent color by default. 

Another idea would be to enable a way to change the checkbox classes.

**Comment by daniel-nagy** [comment]
This is undocumented but you can change the color of the checkboxes. Any `md-*` classes you put on the `<table md-data-table></table>` element will be applied to the checkboxes and I think the progress indicator as well.

The default is to use the accent color of your application. I put an `md-primary` class on the `table` element in the demo app.

I'd like to use Angular Material's `$mdTheming ` service as it would be a much better approach, this is sorta why I haven't documented this.

**Comment by jsenecal** [comment]
Ah! Thanks for the explanation! much appreciated :)

**Comment by phamtuananh791994** [comment]
I can't fix it. Are you sure this working in the lastest version

**Comment by daniel-nagy** [comment]
@phamtuananh791994 I got rid of the theming classes on the table element. If you want to change the checkbox color to something other than your apps theme color you will need to do it manually.

**Comment by phamtuananh791994** [comment]
I use md-primary in my app themes but this show md-accent color. Orther way ?. Thanks you

**Comment by daniel-nagy** [comment]
The default behavior of the checkbox component is to use the accent color of your app's theme.

**Comment by KelvinOm** [comment]
Hi!

Can i set «md-primary» class for checkboxes?
