### ISSUE TITLE
creating columns with ngRepeat

### ISSUE THREAD

**Issue by ricardobfa** [daniel-nagy/md-data-table#80]
Well, thare is no errors in console.

reproduce: http://codepen.io/anon/pen/vOMWbq?editors=101

What i'm missing?

**Comment by daniel-nagy** [comment]
You're not doing anything wrong, I'm doing something wrong. I'll have it fixed in a minute.

**Comment by daniel-nagy** [comment]
Your [pen](http://codepen.io/anon/pen/vOMWbq?editors=101) should be working now.

**Comment by ricardobfa** [comment]
Its working.

Will be a new release for this?

**Comment by daniel-nagy** [comment]
I made a new release, [version 0.8.6](https://github.com/daniel-nagy/md-data-table/releases/tag/v0.8.6). Here is a link to the [change log](https://github.com/daniel-nagy/md-data-table#change-log). I'll need to modify the `mdColumnHeader` directive in the future to make sure something like this never happens again but it should be safe for now.

**Comment by ricardobfa** [comment]
Cool, thanks.
