### ISSUE TITLE
Selecting row don't updating array

### ISSUE THREAD

**Issue by cupideias** [daniel-nagy/md-data-table#81]
My select array updates only when I select all rows, clicking on the thead checkbox.

When I select or deselect direct on the row, the array don't update.

**Comment by daniel-nagy** [comment]
Oh, that sounds really bad. Does it only happen when you click on the row or is clicking the checkbox in the first column of the row broken as well?

Can you fork the [demo app](http://codepen.io/anon/pen/EjOobZ?editors=101) and reproduce this issue?

**Comment by cupideias** [comment]
@daniel-nagy is the Angular-Meteor package outdated? Maybe this is the problem, I'm using it.

The `md-auto-select` here only works on `<tbody>`, for example.

**Comment by daniel-nagy** [comment]
Yeah it sounds like you might be using an old version. Are you using bower to install this module or some other package manager?

if you're using bower and you always want the latest version you can do

```json
"dependencies": {
  "angular-material-data-table": "master"
}
```

or you can specify the tag of the version you want

```json
"dependencies": {
  "angular-material-data-table": "0.8.6"
}
```

**Comment by cupideias** [comment]
I'm using Meteor package manager.
Is there a plan to update the Angular-Meteor package? If not, I will use bower instead.

Thanks for helping.

**Comment by daniel-nagy** [comment]
Oh, I didn't know meteor had its own packaging system, I've never used it before and I certainly don't release packages for it. Someone else must of created a package for an older version?

**Comment by cupideias** [comment]
Yes, the `angular-material-data-table` for Meteor was released at July 20 and never was updated.
You can se here: https://atmospherejs.com/dmgxmg/angular-material-data-table

Anyway, you can close this, but was not an actual issue. I installed using Bower and it works well.
By the way, great job done here, congratulations, it's very useful.

**Comment by daniel-nagy** [comment]
I guess anyone in the community can create a meteor package for open source code. If you use meteor and want to maintain a package of this repository, you are more than welcome to do so. It appears other people are using it as well. I would think there would be a way to create a package so that it watches for updates when new version are released. If not, that would be a big flaw in meteors packaging system.

Thanks! I'm happy to hear this module has been helpful in your project.

**Comment by cupideias** [comment]
I started learning and using Meteor a couple weeks ago, so by now I don't know how to create and maintain packages. In the future if no one have made that, I'll do. Thanks.
