### ISSUE TITLE
Header column multiplied when try change it

### ISSUE THREAD

**Issue by GrafRaf** [daniel-nagy/md-data-table#82]
Hi 

http://codepen.io/anon/pen/MwRmXY?editors=101

On start table has 6 columns
  name, carbs, protein, sodium, calcium, iron

After i'm click DataSet1 ( try set columns to [name, type, calories, fat ] ) in table now 9 columns
  name, type, calories, fat, carbs, protein, sodium, calcium, iron 

Then  i'm click DataSet2  ( try set columns to [name, carbs, protein, sodium, calcium, iron ] ) and in table now 14 columns
  name, carbs, protein, sodium, calcium, iron, type, calories, fat, carbs, protein, sodium, calcium, iron

And so on

**Comment by daniel-nagy** [comment]
I working on making some changes to the `mdTableColumn` directive that should hopefully fix this.

**Comment by daniel-nagy** [comment]
Please see version 0.8.7, your [Pen](http://codepen.io/anon/pen/MwRmXY?editors=101) should be working now.

**Comment by GrafRaf** [comment]
All work fine
Thank you for nice component :-)
