### ISSUE TITLE
change pagination md-label

### ISSUE THREAD

**Issue by ricardobfa** [daniel-nagy/md-data-table#83]
Cant put this to work.

Setting a inline label or from an object, the label dos not change, and if a put more then one word (white spaces), console will show some errors.

demo
http://codepen.io/anon/pen/vOMVRp?editors=101

**Comment by daniel-nagy** [comment]
The [pagination](https://github.com/daniel-nagy/md-data-table#pagination) label is an object. I did this so non-english apps could also change the 'of' text. I've updated your [Pen](http://codepen.io/anon/pen/JdVmBW?editors=101)

**Comment by ricardobfa** [comment]
Oh, right. 

Thanks!
