### ISSUE TITLE
checkbox with angular 1.4.4

### ISSUE THREAD

**Issue by ricardobfa** [daniel-nagy/md-data-table#84]
To simulate this issue, select the checkbox that select all rows and uncheck a single row right after, using angular 1.4.4

http://codepen.io/anon/pen/mJgzQK?editors=101

**Comment by daniel-nagy** [comment]
Oh wow, that's a problem.

**Comment by gligoran** [comment]
I've just hit this problem as well, but it doesn't stop there. It gets weirder. Here's an example scenario using @ricardobfa's pen:

1. select all
2. uncheck one of the checked ones; *bug 1: select-all checkbox becomes unchecked, but the row's checkbox doesn't*
3. go to page 2 and back to page 1; *the unchecked item is not shown as unchecked*
4. click select all; *bug 2: all rows are checked, but the select-all checkbox isn't*
5. click select all again; *bug 3: all rows are unchecked, but the select-all checkbox is checked*

After that is all mayhem. I did notice that backgrounds of rows show the correct state of row being selected or not. Just move the mouse so the :hover background isn't in effect.

**Comment by daniel-nagy** [comment]
The logic for row selection seems to still be working but the `md-selected` class is not being applied appropriately. I think this issue may be internal to the `ng-class` directive. I've opened an issue for this on Angular's Github page, [#12601](https://github.com/angular/angular.js/issues/12601).

**Comment by twrk** [comment]
+1

**Comment by pavelhoral** [comment]
It seems that you are controlling `checked` state with a CSS class. 

    checkbox.attr('ng-class', '[mdClasses, {\'md-checked\': isSelected(' + ngRepeat.item + ')}]');

That seems like an anti-pattern to me and Angular can not be held responsible for instability of this approach.

I was able to make it work by switching to `ngChecked`:

    checkbox.attr('ng-class', 'mdClasses');
    checkbox.attr('ng-checked', 'isSelected(' + ngRepeat.item + ')');
