### ISSUE TITLE
Ng-show not working on th

### ISSUE THREAD

**Issue by vautrinr** [daniel-nagy/md-data-table#86]
Hi ! Awesome work, I am very impressed !!! :+1:  

However, I am facing a little problem with the th and ng-show attribute : it's not working at all, the attribute seems to be removed...

Regards, Rémi

**Comment by daniel-nagy** [comment]
Are you using the latest [version](https://github.com/daniel-nagy/md-data-table#change-log)? This should of been fixed in version 0.8.5

**Comment by vautrinr** [comment]
Thanks so much !!!! It's working :) :+1:  :+1:  :+1:
