### ISSUE TITLE
Responsive md-data-table

### ISSUE THREAD

**Issue by vautrinr** [daniel-nagy/md-data-table#87]
Hello, 
I have written a little code to make the md-data-table responsiveness looks like this one : http://filamentgroup.github.io/tablesaw/demo/swipe.html 
If you're interrested, I could fork the repo and add my code, no jQuery needed.

Rémi

**Comment by daniel-nagy** [comment]
The swipe and stack features look pretty neat. Do you have a demo?

**Comment by vautrinr** [comment]
Not yet. Actually, I only made the swipe one. :/

**Comment by daniel-nagy** [comment]
Okay, one problem with the swip is if tables scroll horizontally you may not be able to tell if the user is trying to scroll the table or swipe to the next page

**Comment by vautrinr** [comment]
http://codepen.io/anon/pen/doLxgo?editors=101
I have added two buttons (the ng-icon doesn't seems to work though). on the top

The code is far away from perfect, I warn you, I am still a junior...

**Comment by daniel-nagy** [comment]
I think something like this has potential. I'm sure some people would like to have this feature.

**Comment by vautrinr** [comment]
So, I fork the repo ?

**Comment by daniel-nagy** [comment]
You are more than welcome to fork the repo and add any features. Don't expect me to merge it into master until it is perfected though :)

**Comment by vautrinr** [comment]
Ok, I'll improve my code this week, thanks :) :+1:

**Comment by vautrinr** [comment]
I have a working example on my branch features/responsive from my repo. I would like to add the ng-show ng-hide animations and the ng-animate module. Do you see any problems with that?

**Comment by daniel-nagy** [comment]
I don't have a problem with that, within the directive I would use `$injector.get('ngAnimate')` and if it is `null` just return. We don't want to force people to install extra dependencies.

**Comment by daniel-nagy** [comment]
**Column Stacking**

I think it would be neat if the table collapsed into multiple cards on small devices. I see some potential issues with column ordering and pagination. Maybe we could add a separate card that controlled the ordering and pagination

**Comment by vautrinr** [comment]
##ng animate
the fix for the awfull display is to include ng-animate, and to make this one in the css : 
`.ng-hide-add, .ng-hide-add-active {
  display: none;
}`

Should I make a pull request? 
##Column stacking 
It's a great idea ! However I am still looking for how to do this. 

Btw, do you intend to add this directive to the official repo ? :+1:

**Comment by daniel-nagy** [comment]
If you think it's ready you can make a pull request and I will take a look at your code (probably not right away, maybe later today). Be sure to include documentation for how to use it.

There is this [pen](http://codepen.io/zavoloklom/pen/IGkDz) of someone attempting this in the past. I wouldn't require people to add attributes for the column names on cells in the body. This redundant and can be automated in a directive. It also needs to be pretty flexible becuase there is no restriction on the content that is in a cell, it could be text or a drop down menu etc.

If everything works well I will merge it yes. I'll likely have some critiques when I look at your code so I wouldn't expect your pull request to be merged right away.

**Comment by vautrinr** [comment]
Ok, I'll make the doc, and after I'll make the pull request. 

I meant on the official md-repo (the one held by google) ?

However, any critiques is more than welcome !! I still need to improve my coding style

**Comment by daniel-nagy** [comment]
Oh sorry I didn't realize what you meant. I believe Google likes to begin a component internally before open sourcing it and allowing the community to improve it. So honestly I don't know. I think the data table component has been postponed till after the release of version 1.0.0. They may or may not have started working on it internally.

I think if they haven't started working on it yet, they may reach out to me when they do depending on how complete this module is and if they agree with my solution. I know they will not except code without unit tests and currently I have none. They also use Sass instead of Less but that wouldn't be difficult to convert.

To be honest I have a feeling they will design their own component but who knows. I don't think version 1.0.0 is going to be released for some time still.

**Comment by vautrinr** [comment]
Ok nice ! :+1: 
Let's hope they will find you !

**Comment by vautrinr** [comment]
<img width="265" alt="screen shot 2015-08-16 at 19 01 47" src="https://cloud.githubusercontent.com/assets/7830183/9294582/9856363e-4449-11e5-8504-1406818dab9d.png">

Indeed, the order could be a problem lol

**Comment by laicosly** [comment]
great thread, enjoyed much, would read again  :smile_cat:
