### ISSUE TITLE
<th> with multiple rows

### ISSUE THREAD

**Issue by dmastag** [daniel-nagy/md-data-table#89]
I would like to achieve something like this

![image](https://cloud.githubusercontent.com/assets/5745805/9290203/0a2d1228-43b4-11e5-905c-d6b5923663bc.png)

But md-data-table is adding the all checklist on the Left
![image](https://cloud.githubusercontent.com/assets/5745805/9290222/a980888c-43b4-11e5-937a-b95228269005.png)

Weird thing is that this is not happening on this codepen.

http://codepen.io/dmastag/pen/bdybvQ

**Comment by daniel-nagy** [comment]
Okay, I'm by the pool not getting sober. I shall have more to say tomorrow. :)

**Comment by daniel-nagy** [comment]
Changes would need to be made to properly support multi-row headers. I think just placing the checkbox on the last row might be the best option.

**Comment by dmastag** [comment]
That would work with me for the time being. I should afterwards be able to make the multi-row headers work for my use case myself using css.

**Comment by daniel-nagy** [comment]
Okay, another thing is if you have numeric columns you will need to add the `numeric` attribute to all headers in that column in order for the cells to align properly. I think I will just use the last column again to control the alignment of cells in the body of the column but putting `numeric` on a column header in any row will still right align that cell.

**Comment by dmastag** [comment]
Well, I am using colspan. How would that work out?

**Comment by daniel-nagy** [comment]
Continue to use `colspan` that won't effect anything. I'm talking about the text alignment within an individual cell.

I figured out what I'm going to do, I'm going to add an optional attribute to the header that lets you specify the major row, if no row is specified it will default to the last row.

**Comment by daniel-nagy** [comment]
You can control which row in the column header gets the checkbox in [version 0.8.8](https://github.com/daniel-nagy/md-data-table#change-log). I noticed an issue with using `colspan` though, see issue #90
