### ISSUE TITLE
Table Progress

### ISSUE THREAD

**Issue by daniel-nagy** [daniel-nagy/md-data-table#93]
I think I may have broken the `md-progress` attribute.

**Comment by pavelhoral** [comment]
Table controller is watching on incorrect attribute [`tableCtrl`](https://github.com/daniel-nagy/md-data-table/blob/master/app/md-data-table/scripts/mdDataTable.js#L73) where the controller is currently named [`$mdDataTableCtrl`](https://github.com/daniel-nagy/md-data-table/blob/master/app/md-data-table/scripts/mdDataTable.js#L135).

**Comment by daniel-nagy** [comment]
Ah yes, I renamed the controllers in the last update. Thank you for finding this!

**Comment by jazalizil** [comment]
Are you sure that it is fixed ? I cloned this code today and it seems like it's still broken

**Comment by daniel-nagy** [comment]
@jazalizil I just did a fresh clone of the repo and verified this is working. If you click the button in the table footer that says trigger outside event you should see the progress indicator. If this is not the case, please let me know.

**Comment by jazalizil** [comment]
Yes it works in this case, but not when I pass a promise as the md-progress attribute  on a table.

**Comment by daniel-nagy** [comment]
That is exactly what the button is doing if you look at the source code for the nutrition controller.

```html
<!-- table element -->
<table md-data-table md-row-select="selected" md-progress="deferred">

<!-- button in table footer -->
<md-button ng-click="loadStuff()">Trigger Outside Event</md-button>
```

```javascript
$scope.loadStuff = function () {
    var deferred = $q.defer();
    
    $timeout(function () {
      deferred.reject();
    }, 2000);
    
    $scope.deferred = deferred.promise;
  };
```
