### ISSUE TITLE
client side pagination doesn't work

### ISSUE THREAD

**Issue by colinshen** [daniel-nagy/md-data-table#94]
```
<tr ng-repeat="value in values| orderBy: $order | limitTo: $limit: ($page - 1) * $limit">
    	<td>{{value.value}}</td>
    	<td>{{value.date}}</td>
</tr>
<md-data-table-pagination md-limit="$limit" md-page="$page" md-total="{{values.length}}"></md-data-table-pagination>
```
i can see the number(pages) of the pagination changes but, the data doesn't change

**Comment by daniel-nagy** [comment]
Unable to reproduce, what version of the data table and what version of Angular are you using? Can you reproduce this issue in the [Codepen](http://codepen.io/anon/pen/zGXWWp?editors=101)?

**Comment by daniel-nagy** [comment]
@colinshen are you still having issues with this?

**Comment by daniel-nagy** [comment]
closing for inability to reproduce and lack of activity

**Comment by mustafabereket** [comment]
I am having the same problem, can you please take a look at it again?

**Comment by daniel-nagy** [comment]
@mustafabereket can you make a demo so I can take a look at whats going on?

**Comment by mustafabereket** [comment]
okay so my problem is, I plug in my data with ng-repeat like this

`<tbody md-body>
                    <tr md-row ng-repeat="user in usersCtrl.userList | limitTo: usersCtrl.query.limit: (usersCtrl.query.page - 1) * usersCtrl.query.limit">
                        <td md-cell>
                            {{user.name}}
                        </td>
                        <td md-cell>
                            {{user.firstName}}
                        </td>
                        <td md-cell>
                            {{user.lastName}}
                        </td>
                  .........

            </md-table-container>

`

and then I configure my paginator like this:

`     <md-table-pagination md-limit="usersCtrl.query.limit" md-limit-options="[5,10,15]" md-page="usersCtrl.query.page" md-total="{{usersCtrl.deviceList.length}}" md-page-select></md-table-pagination>`


but I can never go to next page, page number is always 1.

I am pretty sure I am doing something wrong, but I dont know where.

**Comment by daniel-nagy** [comment]
Hmmm... One thing I see is in your `ng-repeat` expression you are using `usersCtrl.userList` and in you pagination directive you have `md-total="{{usersCtrl.deviceList.length}}"`. That doesn't seem intentional to me.

I don't see anything else popping out at me though. Is the next button disabled or just not going to the next page?

**Comment by mustafabereket** [comment]
Oh my gosh! You are totally right. I missed that, sorry about that.
and Thank you!
