### ISSUE TITLE
Order trigger doesn't work

### ISSUE THREAD

**Issue by ozasadnyy** [daniel-nagy/md-data-table#95]
Hello, I have met an issue with ordering.

When I click on column name it just does nothing, even order icon doesn't change.

Here is my code:
 ```
<md-card-content>
            <md-data-table-container>
                <table md-data-table>
                    <thead md-order="home.query.order" md-trigger="home.search">
                    <tr>
                        <th name="Name" order-by="lastName"></th>
                        <th name="Left company" order-by="endDate"></th>
                        <th name="Current Job" order-by="organizationName"></th>
                        <th name="Industry" order-by="industry"></th>
                        <th name="Locality" order-by="locality"></th>
                        <th name="Social networks"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr ng-repeat="person in home.persons">
                        <td><a ng-link="person({id: person.id})">{{person.firstName + " " + person.lastName}}</a></td>
                        <td>
                            <span am-time-ago="person.jobs[person.jobs.length - 1].endDate"></span>
                            <span ng-hide="person.jobs[person.jobs.length - 1].endDate">Currently working</span>
                        </td>
                        <td>{{person.jobs[person.jobs.length - 1].position + ", " + person.jobs[person.jobs.length -
                            1].organization.name}}
                        </td>
                        <td>{{person.industry}}</td>
                        <td>{{person.locality}}</td>
                        <td>
                            <a href="https://www.linkedin.com/{{person.linkedinProfileId}}">Linkedin</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </md-data-table-container>

            <md-data-table-pagination md-limit="home.query.limit" md-page="home.query.page"
                                      md-total="{{home.persons.length}}"
                                      md-trigger="home.search"></md-data-table-pagination>

        </md-card-content>
```

And controller:
```
vm.query = {
            organizationName: '',
            order: 'lastName',
            limit: 10,
            page: 1
        };

vm.search = search;

function search() {
                vm.persons = [];

                PersonsSearchFactory.query(vm.query,
                    function (data) {
                        vm.persons = data;
                    }, function (e) {
                        console.error(e);
                    });
}
```

**Comment by dmastag** [comment]
HI @ozasadnyy ,
Could you try to replicate this on the codepen?
Here is the link http://codepen.io/anon/pen/zGXWWp?editors=101

Julian

**Comment by ozasadnyy** [comment]
I have edited your codepen, and it's working. I have no idea why it doesn't work for me.. Can you suggest where to start looking for issue?

**Comment by daniel-nagy** [comment]
```html
<thead md-order="home.query.order" md-trigger="home.search">
```
is your search function on the scope?

```javascript
vm.search = function () {
  var self = this;
  self.persons = [];

  PersonsSearchFactory.query(vm.query,
    function (data) {
      self.persons = data;
    }, function (e) {
      console.error(e);
  });
};
```

**Comment by daniel-nagy** [comment]
@ozasadnyy are you still having an issue with this? I didn't see in your controller you were assigning `vm.search = search`. I don't think it should matter that you are assigning it before you define it. Can you provide the link to your edited codepen?

**Comment by ozasadnyy** [comment]
@daniel-nagy it's definitely defined, because it's triggers on pagination.
```
<md-data-table-pagination md-limit="home.query.limit" md-page="home.query.page"
                                      md-total="{{home.persons.length}}"
                                      md-trigger="home.search"></md-data-table-pagination>
```

**Comment by daniel-nagy** [comment]
@ozasadnyy I don't see anything wrong with your code. If you can use the un-minified version of the library, put a break point on line [31](https://github.com/daniel-nagy/md-data-table/blob/master/dist/md-data-table.js#L31) in the `setOrder` function. This is the function that should executed when a column header is clicked. Let me know if

1. This function is never called
2. `headCtrl` and `scope.order` are undefined
3. `headCtrl.pullTrigger` is undefined

**Comment by ozasadnyy** [comment]
@daniel-nagy `headCtrl.pullTrigger` is undefined. Everything else is fine.

**Comment by daniel-nagy** [comment]
Okay this may be a scoping issue unique to your application. Can you now place a break point on line [330](https://github.com/daniel-nagy/md-data-table/blob/master/dist/md-data-table.js#L330)? it should say

```javascript
if(angular.isFunction(scope.trigger)) {
```

and tell me if `scope.trigger` is defined. I suspect it is not which would mean that your `vm.search` function is not visible within scope of the `<thead>` element.

**Comment by ozasadnyy** [comment]
'function postLink(scope, element, attrs, tableCtrl) ' doesn't even invoking.

**Comment by daniel-nagy** [comment]
Okay wow, if you open the developer tools and look at the `thead` element does it have the `md-table-head` attribute?

**Comment by ozasadnyy** [comment]
Yes, it has.

**Comment by ozasadnyy** [comment]
Okay I have tried again it calls `function postLink(scope, element, attrs, tableCtrl)` once on initialization.

**Comment by daniel-nagy** [comment]
okay, for whatever reason `home.search` is not defined in the scope of the `thead` element. I'm guessing you are using the `controller as` syntax, are there any new or isolated scopes between where this controller is defined and the data table?

I don't know if I will be able to debug this unless you can reproduce it in the codepen, it is important that you try to replicate the layout of your application as much as possible.

**Comment by ozasadnyy** [comment]
Yeah, I am using [new router](https://github.com/angular/router), which uses `controller as` syntax by default. No another controller is defined in that file. I am curious why `home.search` invokes in pagination...

**Comment by daniel-nagy** [comment]
The pagination directive is outside the scope of the table and the table creates an isolated scope. The table doesn't actually need to create an isolated scope because I am using the `bindToController` syntax. I may need to remove its isolated scope. Can you try to reproduce this in the codepen? You don't need to pull in new router you can just create a controller that uses the `controller as` syntax.

**Comment by ozasadnyy** [comment]
After bower_components updating it has started to work. Thanks for you help.

**Comment by justcald** [comment]
I am having a very similar problem, where my 

    `md-trigger='onOrderChange'`

function never even gets hit when I click on the headers. The Icon on the header is there and recognizes that it's clicked but my function in my directive never runs. I have the table inside of a directive and my function is inside of link in my directive . I think it might be a scope issue. 
When I put a breakpoint just after 

`    function postLink(scope, element, attrs, tableCtrl) {`

attrs show that mdTrigger has been assigned onOrderChange, but nothing happens.
