### ISSUE TITLE
can we hide the md-checkbox

### ISSUE THREAD

**Issue by loganfreeman** [daniel-nagy/md-data-table#97]
can we add an attribute so that we can remove the md-checkbox from the row

**Comment by daniel-nagy** [comment]
Do you want to remove all checkboxes or just one? If just one, why would you want to remove just one?

**Comment by shrutiaggarwal3012** [comment]
i want to remove all checkboxes from the table.

**Comment by dmastag** [comment]
Hi shrutiaggarwal3012,
You should be able to do this by removing md-row-select from your table as explained in #45.

Thanks
Julian

**Comment by shrutiaggarwal3012** [comment]
Yeah thanks i figured it out that's why deleted the comment.
